### ISSUE TITLE
Unable to Submit a Review

### ISSUE THREAD

**Issue by nobicycle** [joomla/jed-issues#1]
Hi,

My username is nobicycle on joomla.org. I would like to submit a review
for Breezing Forms Pro. Though my review appeared to be accepted, in
that it appeared as the latest review on the page, today I see it has
disappeared. I understand your system may consider reviews written in
the middle of Borneo as spam, but really it was a genuine review
following 3 months of usage. Please advise.

Best wishes

**Comment by JazParkyn** [comment]
Hi,

Please open a support ticket on JED so that the issue can be looked into by the Review Manager. Include the title and date of your review.

Regards
