### ISSUE TITLE
JEDCA is not longer available

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#10]
Hi,

Writing the notes from JAB17, JEDCA is not longer available. Something about a Javascript snippet that it is not on the page. 

https://extensions.joomla.org/support/knowledgebase/item/contributing-code-to-the-jed/

**Comment by jeckodevelopment** [comment]
trying to find the solution to that.

**Comment by anibalsanchez** [comment]
JEDCA is back! https://extensions.joomla.org/support/knowledgebase/item/contributing-code-to-the-jed/

I've restored locally a backup from the previous month, and found the script there.

Now, it's in a custom module, so we are not going to lost it again when the article is modified.
