### ISSUE TITLE
I'd like to delete my JED account. How do I do this?

### ISSUE THREAD

**Issue by level420** [joomla/jed-issues#100]
I found no possibility to remove my account from JED.
How can I do this?

Thanks in advance

**Comment by anibalsanchez** [comment]
Hi,

You have two alternatives:

- Send us a ticket to remove your account from the site
- Send a "Right to be Forgotten" from all Joomla site: https://www.joomla.org/right-to-be-forgotten.html

Hope this helps! Let us know if there is anything else we can do.
