### ISSUE TITLE
JED Login Issue

### ISSUE THREAD

**Issue by rajeshnanda33** [joomla/jed-issues#103]
Greetings Team,

Irrespective of what, I am not able to log in into JED.
Changed passwords many times, checked username many times, still can't log in.

I also contacted the team with support tickets, support team answered as fixed 2 times.
However, I can't log in.

My last support ticket was on April 29th. 
Till waiting for the fix.

My JED profile id: 190870
I am desperately waiting for the solution to my situation.

Best Regards.
Rajesh

**Comment by anibalsanchez** [comment]
Your user looks fine. 

Please, try to access the site with a different browser. Maybe cookies, redirections or something like that is playing tricks on your connection.

**Comment by rajeshnanda33** [comment]
It's nice to hear from You :)  Thank you.

I tried in a different browser, still, I can't.

I can log in from another new account which I had created to contact the support team in the same browser.

So the browser is no issue.

Please HELP.

**Comment by anibalsanchez** [comment]
Hi,

There was an inconsistency in your user. I've just reset it and sent you the reset emails. Please, try now.

Regards

**Comment by swifthunk** [comment]
Hi Anibal,

**I didn't receive the reset mail.**

Also tried the forgot password link, there didn't receive any mail.
Regards.

**Comment by rajeshnanda33** [comment]
**Thank you, Anibal.**

**You are the BEST.**
