### ISSUE TITLE
Extensions names with leading space(s)

### ISSUE THREAD

**Issue by slashdottom** [joomla/jed-issues#105]
Possible a moot point, but the following extensions have either a double space (first extension in list below only) or single space before the extension name on the extension’s page (in both h1 and h2 tags), although it displays correctly on page, the code contains the space(s).

Ext. ID - Extension Name
----------------------------------
13337 -   Bulk Product Upload for Virtuemart
12997 -  Abandoned Cart for VirtueMart
12275 -  Animated Pinterest &quot;Pin It&quot; Button for Images
12502 -  Ark Media Manager Pro
14112 -  DatsoGallery pictures for Geommunity maps
13090 -  DD GMaps Locations
11884 -  DPCalendar for AcyMailing
11765 -  EasyCalc Financial Calculators: Cost of Living 
9437 -  Encrypted Contact Form for Joomla!The
10501 -  Floating YouTube Video Anywhere 
9157 -  Fotorama Responsive Gallery
9111 -  Login as User
10240 -  Menu Search for vRestaurant
10536 -  Promo Notice Message with Timer 
13265 -  Remove article Id from sef url
10771 -  Responsive Accordion Image Slider
9541 -  Responsive Pricing Table Maker
9445 -  Responsive Tables - Editor
11395 -  TC Price Table 
10967 -  Video Background Anywhere

**To Reproduce**
1. Go to 'https://extensions.joomla.org/'
2. Search for extension name listed above
3. Open the extension's page
4. Highlight the H1 tag at the top or the H2 tag in the extension meta box, then right click mouse and select 'view selected source'.
5. The text prior to the title should be tabs only.

**Comment by anibalsanchez** [comment]
I've just run a query to trim the titles of extra spaces and added a query to the cron to keep it.

Solved!
