### ISSUE TITLE
Deadlink

### ISSUE THREAD

**Issue by nallias** [joomla/jed-issues#108]
Hi all,

About the page https://extensions.joomla.org/extensions/extension/mobile/qr-code/qr-code-friendly/
tab "full description"
the content is wrong:
(please see http://docs.joomla.org/HowtooverridetheoutputfromtheJoomla!core).

should be:
(please see <a href="https://docs.joomla.org/How_to_override_the_output_from_the_Joomla!_core">How to override the output from the Joomla! code</a>)

Thanks

**Comment by anibalsanchez** [comment]
Hi,

This ticket system is for JED system issues. For support questions about content updating or how to use an extension, please contact the developer directly via their website.

Best Regards

**Comment by nallias** [comment]
@anibalsanchez Hi, you should then change the footer link "Report an Issue" into "Report an JED Issue not related to any content" ; I have found no way to contact the developer, Marco Molina.
Keep up the good work!

**Comment by anibalsanchez** [comment]
Thank you!

You could report the extension with the "Report!" button. But, the download is still available. So, it could be still useful, even if the extension description is outdated.
