### ISSUE TITLE
AZDirectory

### ISSUE THREAD

**Issue by becgirl** [joomla/jed-issues#109]
I'm trying to leave AZDirectory a very positive review because he was extremely helpful.  The module is wonderful.  When I try to leave a review I get an error message.  I've left reviews for other modules so I'm not sure what the problem could be.  Is this the correct place to report this?  He really deserves to get reviews.

**Comment by anibalsanchez** [comment]
Hi,

Please, check the previous response #85 about a similar topic.

Closing this issue as a duplicate.

Best Regards
