### ISSUE TITLE
Data cleansing on duplicated published extensions

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#110]
There are duplicated published extensions. Only the last one is shown due to the router showing the last extension matching an alias.

Some manual work is needed to unpublish the old duplicated extensions.

**Comment by tassosm** [comment]
I am not sure I understand this 100%.

If you go to https://extensions.joomla.org/instant-search/ you will notice Breezing Forms Pro and RSForm! Pro extensions still appearing 3 times.

Does it mean that these extensions are appearing in the DB 3 times too? If so why this issue doesn't happen in the category view here: https://extensions.joomla.org/category/contacts-and-feedback/forms/ ?

**Comment by anibalsanchez** [comment]
No, it seems that Algolia has changed the indexing process and the latest update yesterday applied the new logic. It seems that they are enforcing unique IDs to avoid duplication of records... may be due to communication or indexing issues.

In any case, I'm preparing a library update to clean the duplicates.

**Comment by anibalsanchez** [comment]
The indexing issue has been solved. Please, check #111 for more information.

The data cleansing is still needed on the extensions table. So, #110 is still open.

**Comment by tassosm** [comment]
Confirmed! The issue is now resolved :)
