### ISSUE TITLE
Can't leave a review on Extensions

### ISSUE THREAD

**Issue by mbennett417** [joomla/jed-issues#112]
When trying to leave a review, I get the following screen:
![image](https://user-images.githubusercontent.com/14099932/60833285-88d5a000-a183-11e9-92eb-d50efbf82f5b.png)
I'm using a different ISP than I have previously, and have a 192.168.x.x private address, but not running a VPN or server.  Don't know what server it might be referring to.

I'm not going back to DSL when I now have fiber service. If you need additional information let me know.

**Comment by anibalsanchez** [comment]
Please, follow the original issue #85 

Closing this issue as a duplicate.
