### ISSUE TITLE
Data Issue: JED Search does not always match match title first nor sort by default nor display categories and tags of results

### ISSUE THREAD

**Issue by beat** [joomla/jed-issues#113]
**Describe the bug**

I'm listing 4 sub-bugs here, as I believe that they are related:

1. Search doesn't put title matches first
2. Default search result sorting is not by ratings/reviews
3. Category and sub-category of search results don't appear.
4. Tags of search results don't appear.

Community Builder is under category "Clients and communities", sub-category "Communities":  https://extensions.joomla.org/category/clients-a-communities/communities/ with tags "Social Web, Communities, User Management, Membership & Subscriptions, Teams".

**To Reproduce**

1. Go to https://extensions.joomla.org/instant-search/
2. Type in search 'Community Builder'
3. Expect exact title match as first result, but you have to go until page 10 (link here to avoid searching: https://extensions.joomla.org/instant-search/?q=Community%20Builder&hPP=10&idx=jed_live&p=9 ) to find it. **This is bugs 1 and 2** described above
4. Go back to page 1.
5. See that neither category "Clients and communities", nor sub-category "Communities" are visible left for filtering the search result **This is bug 3**
6. See that none of Community Builder tags appear in the tags filtering left **This is bug 4**
 
**Expected behavior**
Search other extensions, like "share button by" and it works as expected.
 
**Desktop (please complete the following information):**
 - Ubuntu 16.04 latest
 - Firefox 67.0.4 latest

**Comment by anibalsanchez** [comment]
Hi,

It looks like the issue is on the indexation of "Community Builder" specifically. It isn't in the index.

**Comment by beat** [comment]
Hi Anibal,
Thanks for your very quick reply. Indeed that could explain the result. But that doesn't look normall. :wink: 

Also, shockingly, the default sorting by overall rating and number of reviews seems not based on public displayed values, I have described this in detail in my ticket 25305 (and am since then also aware of https://github.com/joomla/jed-issues/issues/84 , but it still doesn't make sense to have a sorting on a different rating than the one displayed). Could you please also have a second look the ticket 25305 while checking for this ? :wink:

**Comment by anibalsanchez** [comment]
Let's keep the focus on this issue on the data issue that you found related to **Community Builder**. I've been recently improving the data crawler to solve data issues, so this could be a new problem of internal data inconsistency in the Community Builder extension structure.

If you want to improve the search definitions, please, publish your findings on #84. I've just updated it with a link to the search engine definitions. As you can find there, the current search algorithm combines the text matching and the ranking to produce better results. It is well defined and it can be changed at any time. We have received proposals from several JED Developers and we have been updating it accordingly when the feedback was validated by other reviewers as an improvement. If you have the time to participate in the process, you can always join the JED Dev Team.

**Comment by anibalsanchez** [comment]
I've been improving the search implementation. I'm still looking for the issue that indexer has that doesn't index some extensions.

**Comment by beat** [comment]
Hi Anibal,
Sorry to bump, but the JED search field still doesn't find Community Builder when typing it in the last 4 months.
Any hope to find the issue ?

**Comment by beat** [comment]
Hi @anibalsanchez, can I please volunteer to try to fix that issue and, if my help is accepted, can you please give me access to try to fix this ?

It has now been over 6 months that just our extension is not findable on JED.

**Comment by anibalsanchez** [comment]
Sure, we are always open to new JED Developers. I've been investigating the issue myself.... but I've been unable to pinpoint the source of the issue.

Please, contact me on Glip to start the onboarding process.

**Comment by anibalsanchez** [comment]
I've been working on an update to the latest Algolia API v4. 

My plan is looking into the issue of the extensions that are now indexed at the same time.

One more extension to check, "Phoca Gallery" #143

**Comment by anibalsanchez** [comment]
Hi, 

I've been running tests and performing queries to debug the issue. The search issue is found on extensions that have their own subcategories and/or there are also other extensions naming the parent extension).

I've re-adjusted the index parameters and the issue seems is solved. Community or Phoca Gallery appear first or near first in the search results. The rest of the search cases return similar results. So the change improves the previous configuration.

This is the new configuration: https://github.com/joomla/jed-issues/wiki/JED-Search-use-cases-and-definitions

Please, check the issue and report if you find new occurrences.

**Comment by PhocaCz** [comment]
Hi, sorry for late response, I didn't follow this issue but https://github.com/joomla/jed-issues/issues/143 ... 

Testing now and problems described in https://github.com/joomla/jed-issues/issues/143 seem to be fixed.

Thank you very much, Jan
