### ISSUE TITLE
Trying to register

### ISSUE THREAD

**Issue by prh47bridge** [joomla/jed-issues#115]
About 2 weeks ago I attempted to register. The activation email has never arrived. There does not appear to be any way to resend the activation email. If I now try to create an account it tells me that the username and email address are already in use. If I try a password reset it tells me that my email address is not valid. I am, therefore, stuck.
The username I am attempting to register is prh47bridge.
Please fix this.

**Comment by anibalsanchez** [comment]
I have executed the manual process to remove the inactive accounts.

Please, try now.
