### ISSUE TITLE
PHP error when submitting a review. Cannot use object of type stdclass as array

### ISSUE THREAD

**Issue by weeblr** [joomla/jed-issues#116]
**Describe the bug**
One of my user started to post a [review on sh404SEF](https://extensions.joomla.org/extension/sh404sef/). Upon clicking the "Submit" button, he was faced with a PHP error:

> 0 Cannot use object of type stdclass as array.

(see screenshot 1)

The review is not visible yet 3 days later. User tried again today to post a new review but got this message:

> Writing a new review will overwrite your previous review.

(See screenshot 2)

**To Reproduce**
No specific steps, just a user trying to post a review. All fields filled.

**Expected behavior**
Review posted.

**Screenshots**
![5Eok6zIw](https://user-images.githubusercontent.com/5846185/62446722-cc600180-b763-11e9-937e-6136d9050cf0.jpeg)

![image](https://user-images.githubusercontent.com/5846185/62446784-f0234780-b763-11e9-9794-86ff0017b0ac.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by weeblr** [comment]
Hi again,

Here is hoping someone can look at this problem.

Best regards

**Comment by weeblr** [comment]
Hi @anibalsanchez 

Any news on this? Anything I can do to help?

Best regards

**Comment by anibalsanchez** [comment]
Hi,

I have been unable to reproduce the issue. Additionally, we have integrated Sentry service (Error Tracking). So, we receive and track PHP errors. This error is not being reported and reviews are still being received normally.

So, the problem seems to be being fired under very specific conditions, it is being received at the review level and it is not reported.

For instance: I've just submitted a review to one extension without issues. So, more info is needed to reproduce the issue.

**Comment by weeblr** [comment]
Hi @anibalsanchez 

yet we have screenshot with the PHP error displayed so it did happen and was not reported.

>  So, more info is needed to reproduce the issue.

What information can be provided?

Best regards

**Comment by anibalsanchez** [comment]
We need to diagnose exactly when it does not work to reproduce the issue.

Is it an issue specific of sh404SEF?

**Comment by weeblr** [comment]
> Is it an issue specific of sh404SEF?

I cannot know that. I have a customer who reported to me trying to leave a review and being faced with this. I was lucky he took the time to do screenshot and just report the thing to me, otherwise I would not have ever known.

[EDIT] What I mean is this might have happened 1, 10 or 100 times without me knowing at all - and without you knowing either as the PHP error does not seem to be reported. I would suspect other extensions should be subject to the same.

As far as I can tell, and after asking him, there was nothing special: he just went and tried to post a review, then was faced with this error. As this is a PHP error, it can't really be related to his browser or OS.

The other thing is that if he tries to post another review, he can't with the message per the second screenshot. So at least looking up reviews directly in the database for sh404SEF (id=955) may provide insight about the details of his posting?

Best regards

**Comment by anibalsanchez** [comment]
JED has plenty of activity, so looking into the database is not an option to find an issue.

So, we need precise steps to reproduce the case. If there is a general issue, we receive many reports.

At this time, I haven't received more reports about this case. I'm going to add a review to sh404SEF. If I can't reproduce the issue, then I'll have to close the issue since there are no more related reports.

**Comment by weeblr** [comment]
Hi

>JED has plenty of activity, so looking into the database is not an option to find an issue.

You can't run a query against the database?

> So, we need precise steps to reproduce the case. If there is a general issue, we receive many reports.
Like I said, there is no step, just a regular user (not me) trying to post a review and getting a PHP fatal error.

> At this time, I haven't received more reports about this case. 
As reviews are posted by regular site maintainers and error reports are supposed to be posted to Github, I would indeed expect a very small number of reports to happen.

> I'm going to add a review to sh404SEF. If I can't reproduce the issue, then I'll have to close the issue since there are no more related reports.

Thanks for trying. Yet the JED has unreported PHP fatal errors when users try to post a review.
In case it might have an impact, here is a screenshot the user made the second time of their proposed review:

https://www.dropbox.com/s/hlldxmgy35evl2v/2019-08-01%2022_23_51-Add%20a%20review.jpg?dl=0

Best regards

**Comment by anibalsanchez** [comment]
I can't run a query against the db without knowing what to look for.

Please, send us a video with the steps to reproduce the issue. In the meantime, I'll post a review to sh404SEF.

**Comment by weeblr** [comment]
Hi Anibal,

> Please, send us a video with the steps to reproduce the issue.

Again, please try to understand **there is no step**. Just a regular user - not me - trying to post a review and getting a PHP fatal error from JED.

> I can't run a query against the db without knowing what to look for.

Maybe just look for any review for sh404SEF that was posted over the last 2 months (to be safe, don't remember the exact date) and that is there but is not published for some reason. Why it is not published would be the interesting thing to know as it could be an indication of which part of the JED code failed: the review seems to have been stored to the database (because the user gets the message "a new review will overwrite the previous one") but the review is not displayed? 

Best regards

**Comment by weeblr** [comment]
Hi @anibalsanchez 

Don't know if you tried yourself or did any work on this. Yesterday I asked that user if they could try again posting their review. I got a message this morning and the result is:

> Didnt give me the "Writing a new review will overwrite your previous review" message. but I got a 404

Not sure about an actual 404 response code but the screenshot is explicit:

![image](https://user-images.githubusercontent.com/5846185/64680011-2cda1100-d47d-11e9-9816-6985e16f34c0.png)

Once again a fatal error. Did Sentry caught that one? or was it caught by Joomla instead and just displayed by the Joomla error handler?

Best regards

**Comment by nickanti** [comment]
A user reported a similar issue when trying to post a review for Community Builder and I opened a JED ticket to report.
JED responded that this is a known issue and redirected me to this artifact.

**Comment by anibalsanchez** [comment]
I have just had an idea ;-)

I have been unable to reproduce the error.... however, the problem with Sentry's error handler is that the template error page catches the error and eats any further processing.

So, I've just added the error handler to the template error page. In theory, now, Sentry will also receive any error received in the template error page. So, I could diagnose the error (even without being able to reproduce it).

Please, try again to send a review. I'll be monitoring Sentry's reports.

**Comment by weeblr** [comment]
Hi

Just asked our user to post again his review. I'll let you know when/if he does that.

Best regards

**Comment by weeblr** [comment]
Hi

Sorry for late report. The user posted a review on or just before September 15. Was any error logged?

Cheers

**Comment by anibalsanchez** [comment]
Yes!, it is logged. I'm going to check in detail the next weekend. Txs.

**Comment by weeblr** [comment]
Ahh, good news. Can you also search the database for "stuck" reviews for sh404SEF? there might be others with reviews that are in the database but are not showing?

Best regards

**Comment by weeblr** [comment]
Hi @anibalsanchez 

I know you probably have been busy with the new ticket system and all but did you have a chance to review the error log and figure out what's going on here?

Also, can you run a query on the database to see if sh404SEF has other "stuck" reviews not showing?

Best regards

**Comment by anibalsanchez** [comment]
I've added a couple of checks to avoid this error. It shouldn't occur again. I'll monitor Sentry's log.

About "stuck" reviews, there are none. The error prevented the storage of the review.

**Comment by weeblr** [comment]
Hi

Thanks for that, I'll try have our user give it another go.

>About "stuck" reviews, there are none. The error prevented the storage of the review.

Is that consistent with the fact that when trying again, they were getting a message saying "Writing a review will overwrite your previous review?

![image](https://user-images.githubusercontent.com/5846185/66290916-c2cc5480-e8e0-11e9-8df5-a075a1ffc54d.png)

If the review was not stored, how can a "...previous review" exist?

Best regards

**Comment by tassosm** [comment]
Thank you @anibalsanchez. Does this fix #114 also?

**Comment by anibalsanchez** [comment]
@weeblr Good question, part of the information was saved. I'll check what was saved to clean the inconsistencies. Since the data was saved early in the processing of the review, they can't be recovered.

@tassosm No, it is a different issue. I answered there.

**Comment by weeblr** [comment]
>Good question, part of the information was saved. I'll check what was saved to clean the inconsistencies. Since the data was saved early in the processing of the review, they can't be recovered.

ok, too bad. I'm afraid this might have happened quite a few times.

Any idea what circumstances was causing the error? only few users seem to experience the issue, was it a particular browser for instance? or the content of the review?

Cheers

**Comment by anibalsanchez** [comment]
The issue is very odd indeed. It looks like that in some rare cases, the library retrieves an internal structure as an object instead of an array.

My guess is that the problem comes from a data issue and how the Fabrik library manages the serialization. This part of the system is complex, and the data is distributed in Joomla UCM and JED custom tables.

**Comment by weeblr** [comment]
Hi @anibalsanchez 

Bad news, problem not solved - the exact same error:

![image](https://user-images.githubusercontent.com/5846185/66374883-4bfc8d80-e9ac-11e9-9abe-bc3f2c4d9312.png)

He reported the error at about 21:15 UTC, likely he posted a few minutes before that.

Best regards

**Comment by anibalsanchez** [comment]
My bad. I forgot to apply the CI action. Now, it is applied.

**Comment by weeblr** [comment]
Hi

OK, thanks for replying quickly. Just informed the user but might be some time before he can test again due to time differences.

Best regards

**Comment by weeblr** [comment]
Hi @anibalsanchez 

So that user posted again his review and this time there was no message.  He's got a screenshot showing "296 reviews".

About 10 hours later, the review is still not showing for me or for an unlogged user, and the review count is still at 295.

Is that expected?

Cheers

**Comment by anibalsanchez** [comment]
Hi,

The review has been received and processed. So, the reported issue is solved. We have received more reviews and they have been published successfully, so the improvement is working fine.

About the specific review, it passed the first screening and was flagged as spam (Proxy). So, the IP has open ports or a characteristic associated with a Proxy. As far as I can verify, it was processed as expected.

Best Regards

**Comment by weeblr** [comment]
Spam? this is joke right?

**Comment by weeblr** [comment]
No wonder there are so few reviews if you think using a proxy is the sign of a spammer. 

Is there a manual way of reviewing those SPAM reviews? or are they lost for ever? Is there any information somewhere? 

Should we also tell our users to not post reviews from their work machines, behind a proxy but instead from home or another place?

Best regards

**Comment by anibalsanchez** [comment]
The current system works in this way. We can't change how spam is detected. We already know that the current detection system has an issue (that's complex and needs a new full implementation) #85 

From my side, I can't publish it manually. It wouldn't be fair if I force it. Please, send a ticket to Reported Reviews for a manual check-up (or I can send it for you but I'm not the owner of the extension of the reviewer...).

**Comment by weeblr** [comment]
Hi

I'm not asking you force it, indeed that would be unfair. I have started opening a ticket.
Not sure what you mean by 

> but I'm not the owner of the extension of the reviewer...).

Also, I read #85 but my user never mentioned anything like having a message such as :

"Security checks determined you may be using an IP masking service or VPN. To continue, you need a different Internet connection."

Considering how many times he tried to post that review, I'm 100% sure he would have mentioned it.

Best regards

**Comment by anibalsanchez** [comment]
The first screening of the reviewer has been introduced recently to reduce the number of reviews flagged as spam by Spam Checker. However, it does not detect 100% of the cases. Then, the second check-up performs the full lengthy validation where it detects more cases. So, the real problem is the original definition of reviews and the spam that we receive, and how to handle it.

For more information about the new Review System that's in the works: https://forum.joomla.org/viewtopic.php?f=262&t=973003

Fat finger error, I mean "I'm not the owner of the extension or the reviewer"

**Comment by weeblr** [comment]
Hi

OK I see. Ther review was posted only 12 hours ago so the check was in place but indeed if there's 1st a simpler one and then a more thorough one, this explains that.

I think I'll just close the ticket now as the PHP error is solved and we can follow up on the other ticket, #85.

I have sent a ticket to "Reported reviews", referencing this issue and I'll wait to hear from the team.

Best regards

**Comment by anibalsanchez** [comment]
Thank you for reporting @weeblr and your understanding.
