### ISSUE TITLE
[Feature Request] CI publish availability / API

### ISSUE THREAD

**Issue by alex7r** [joomla/jed-issues#118]
Would you consider adding API for updating the extension versions with CI pipelines for developers?

I would like to fully automate the process of "release", and if it is possible to automate the build process and the release process on the website it is still an issue to upload package to the JED.
You can not easily perform login with CURL since form have token.

**p.s.** 
I'm not really sure if it is possible to:
- curl for html
- preg match the token
- curl for auth + store cookies
- curl for edit form token
- upload new version with token

However I see it as overkill, so may be you will actually consider a small API endpoint.
Thanks.

**Comment by anibalsanchez** [comment]
Hi,

Sure. At this moment, there is a team focused on JED4 development. So, this task could be added to the roadmap.

If you want to volunteer to collaborate in the effort and develop the CI publish availability / API, we are always open to collaboration.

Best Regards

**Comment by alex7r** [comment]
Yes, sure. I would rather like to add up.

I heard about possibility to commit to JED repo and that you need to 
- pass through some checks (?)
- and sign NDA (?)

2 years ago.

However I did not found any clue where to do that since.
So I would be happy to contribute if you can guide me through "getting started" process.

**Comment by anibalsanchez** [comment]
Hi,

The JED 4 repo is available now here: https://github.com/joomla/com_jed4

Feel free to join the effort of the JED4 Team. You can submit an issue there to continue with the conversation there.
