### ISSUE TITLE
Images on JED not working

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/jed-issues#119]
It seems that images randomly fail to load due to a ERR_SPDY_PROTOCOL_ERROR 

Opening the direct link to a broken image, you can notice that the image is loaded only partially.
The problem could be due to the upload component.

![image](https://user-images.githubusercontent.com/17835460/62573776-1c8bb080-b897-11e9-9491-24beeded5b04.png)

**Comment by JazParkyn** [comment]
Hi, we are aware of the issue - our hosts are liaising with CDN provider to resolve the issue. Thanks!

**Comment by joeforjoomla** [comment]
Thanks @JazParkyn !

**Comment by JazParkyn** [comment]
The issue has now been resolved.

**Comment by joeforjoomla** [comment]
@JazParkyn i still experiment this issue. No changes so definitely not solved.

**Comment by joeforjoomla** [comment]
Issue still there just the same as before
![image](https://user-images.githubusercontent.com/17835460/62725365-47037800-ba15-11e9-975a-5d0d6df5b85e.png)

**Comment by anibalsanchez** [comment]
It looks like it working fine now. Since it was a CDN issue, it was a distributed issue and took some time to be solved everywhere.

If you still have the issue, please, update the issue to reopen it.

**Comment by joeforjoomla** [comment]
@anibalsanchez now it's working fine. Probably the CDN took some time to propagate as you pointed out. Thank you.

**Comment by anibalsanchez** [comment]
The issue is active again. Sample URL: https://extensions.joomla.org/extensions/extension/photos-a-images/images/simplehovereffect/

I've sent the ticket to the hosting provider.

**Comment by anibalsanchez** [comment]
At this time, the issue is solved.
