### ISSUE TITLE
Joomla little helper

### ISSUE THREAD

**Issue by fabio42170** [joomla/jed-issues#120]
Seems like we can't download the plugin at all whether it is on the [author's website](https://www.fasterjoomla.com/download/little-helper/littlehelper-2-6-2) or on [github](https://github.com/riczorn/littlehelper).
There's an error message showing. Am I the only one experiencing this ?
Thanks for your help !
<img width="451" alt="github-error" src="https://user-images.githubusercontent.com/41090804/63164806-e3d3a000-c029-11e9-860d-e4e5c5347357.PNG">

Fabio

**Comment by anibalsanchez** [comment]
Hi,

This ticket system is for JED system issues - we are unable to provide support for your issue. For support questions about how to download an extension, please contact the developer directly via their website.

If you find that the site is non-functional, you can report the extension on JED.

Regards
