### ISSUE TITLE
Get back "Last updated" top menu and filter for Joomla community JED

### ISSUE THREAD

**Issue by ssnobben** [joomla/jed-issues#121]
**The search filter for JED have also disappear for "Last updated".**

Normally when people want to check the latest updated extensions for Joomla community they go to this link one day ago, https://extensions.joomla.org/browse/new/ and then make t w o filters "Last updated" to find what extensions that was last updated.

Now from today this doesn't work bcs the filters doesn't show up. Pls make a quick menu top link to "Last updated" that been requested so many many times and get the filters back also.

**To Reproduce**
Go to https://extensions.joomla.org/ and see menus from top menu "Browse extensions" you can not find or filter anything as old JED had for see follow what extensions have been updated. 

Thats a good way to follow every developers activity and also see the progress of any developer how good and active they are in their dev process of their Joomla extension.  

**Now there is no way to know what extensions are "Last updated"**

**Expected behavior**
A menu and one filter that execute "Last updated" for top menu and also as a filter.

**Additional context**
Many people want to see how active developers are regarding their updates and progress of their Joomla extension and Joomla activity. 

**Its an essential part of Joomla community development monitoring tools and have been used by Joomla users for over a decade...**

**Comment by andiamine** [comment]
Yes please , filter by last updated is essential we do use this feature a lot.

**Comment by ssnobben** [comment]
Whats the status of this issue? 

The "Last Updated" feature was removed Saturday Aug 17 2019 and here is more discussions 

[https://forum.joomla.org/viewtopic.php?f=262&t=973799](https://forum.joomla.org/viewtopic.php?f=262&t=973799)  

[https://forum.joomla.org/viewtopic.php?f=262&t=973003](url)

**Comment by anibalsanchez** [comment]
Hi,

The next Friday, the JED team has the monthly meeting and we'll discuss the "Updated Extensions" report. My idea is restoring the unpublished report that was available on the menu.

BTW: Please, do not post twice, to avoid this copy-pasting.

Regards

**Comment by anibalsanchez** [comment]
**Recently Updated / New & Noteworthy** reports: We have discussed the suggestion to restore revamped reports and concluded that it's a good opportunity to revisit the topic with reviewed queries. After the new ticket system implementation, we'll continue with the implementation of this point. If you want to collaborate with the team, feel free to contact us here.

You can check the Full meeting report here: [JED Team Meeting - August 30th, 2019 ](https://volunteers.joomla.org/teams/extensions-directory-team/reports/1089-jed-team-meeting-august-30th-2019)

**Comment by anibalsanchez** [comment]
TOP 100 **Recently Updated** is back: https://extensions.joomla.org/browse/recently-updated/

it is the list of the last 100 updated extensions.

About **New & Noteworthy**, I'm still thinking how to find "New and Noteworthy"... because we already have the queries with the newest extensions and there is no easy way to feature extensions without manual intervention.

**Comment by andiamine** [comment]
Great news thanks :)

**Comment by ssnobben** [comment]
> 
> 
> TOP 100 **Recently Updated** is back: https://extensions.joomla.org/browse/recently-updated/
> 
> it is the list of the last 100 updated extensions.
> 
> About **New & Noteworthy**, I'm still thinking how to find "New and Noteworthy"... because we already have the queries with the newest extensions and there is no easy way to feature extensions without manual intervention.

Hi Anibal!  

The problem is that its not filter the "Last updated" with the latest released first.

Can you fix that filtering option asap it would be fine. (  https://forum.joomla.org/viewtopic.php?f=262&t=973799  )

**Comment by anibalsanchez** [comment]
Hi,

In the system, we only have the "modified date" of the listing. There is no other way to detect the releases after an extension is published; the author has to updated the entry with the latest release number.

**Comment by andiamine** [comment]
we did recently update one of our extensions (version changed also uploaded a new package of extension ) and didn't show , recently updated keeps displaying only old updated extensions 

maybe caching problem in this view ?

**Comment by webgobe** [comment]
something is really fishy. I also updated one of my extensions today (Similar Tags with Introtext and Images - new package has been uploaded, the description changed and the release number ALSO has been changed ) - and does not showing up, but, surprise! Another one I didn't touched for years - literally - is in top 100 (Phoca Downloads plugin for sh404SEF). And, jut to not be only about me, there is another weird entry on top 100, the Prayer Center by Mike Leeper, which is basically abandoned, that's why I build (and published) on JED my own prayer component. None of these could be included here because of some caching thing, is something wrong in the algo.

**Comment by anibalsanchez** [comment]
The query is sorted by #__ucm_content.core_modified_time.

My guess is that in some cases the date field in this table is not updated.

**Comment by ssnobben** [comment]
**** Yes as now this doesn't work as expected. 

The "Recently updated" doesn't work as "Latest updated" should work bcs its not show the latest updated Joomla extensions. Just revert the old "Latest updated" search filter that works well. 

Another wish would be to have the listings first view similar like the right columns extension badge of information so we all could see all this data from all extensions. See image no logo image etc that could be shown after user click on extension.

Have 3 extensions in a row with 3 columns of extensions overview of data like this instead.

![jed](https://user-images.githubusercontent.com/6490832/66023503-a94a9780-e4f1-11e9-8c5b-99422255a346.jpg)

So have 3 columns with extension listings showing this overview of them all info quickly and would be better info overview also adding star rating on top could be nice..

Example data that we have on second click instead of first overview:
------------------------------------------------------------------------------
**BlastChat**
Version:
    4.0
Developer:
    BlastChat 
Last updated:
    Mar 13 2016
Date added:
    Mar 05 2006
License:
    GPLv2 or later
Type:
    Free download 
Includes:
    c m
Compatibility:
    3
Download
This extension does NOT implement the Joomla! Update System
--------------------------------------------------------------------------

**Then we have all overview data that is important to see quickly and easy when coming to JED.**

Thks.

**Comment by anibalsanchez** [comment]
@ssnobben The old queries are not coming back, we must improve what we have today. I'll check it the next weekend.

If you have more "wishes", you can open new issues. If you have more wishes, you can also join the team to help us: https://volunteers.joomla.org/teams/extensions-directory-team

**Comment by ssnobben** [comment]
Thanks Anibal will think about that.

As now the recently updated shows the same extensions all the time. Nothing change the same "Recentely updated" comes up all the time and that’s a bug and unexpected behaviour.

Cheers!

**Comment by anibalsanchez** [comment]
I've reviewed the query and added a twist and an optimization. Please, check it now.

**Comment by ssnobben** [comment]
Anibal seems to work now!! Great to get it back !  :)

**Comment by andiamine** [comment]
Works fine thank you very much

**Comment by anibalsanchez** [comment]
Two testers and successful tests. Case closed!

Thank you for feedback :-D
