### ISSUE TITLE
No verification email after registering and then user is blocked message?

### ISSUE THREAD

**Issue by hennysmafter** [joomla/jed-issues#122]
We wanted to start uploading our extensions to the JED. And to do so we need to have an account. So for this purpose, we filled in the registration form and pressed submit.

This resulted in a Warning and an Error. We checked our inbox and no mail not even in the Junk section. Then looking at the error it looks like the registration failed completely.

![Register - Google Chrome](https://user-images.githubusercontent.com/4426337/64955894-aad95600-d889-11e9-9712-10e7dd0feddb.jpg)

So we tried to do a username reminder just to see if there was anything registered. Upon our amazement, we received then a user is blocked message.

![Username Reminder Request - Google Chrome](https://user-images.githubusercontent.com/4426337/64956061-0c012980-d88a-11e9-8b41-34479c99a760.jpg)

Can anyone help with getting this account approved?

**Comment by anibalsanchez** [comment]
Hi,

Your user enabled and active now. So, it looks like you've been able to solve it.

Regards

**Comment by hennysmafter** [comment]
@anibalsanchez 

I have not solved it I can still not log in. I just tried it again and it says that we still need to accept the verification email but there is no mail whatsoever. 

We checked spam and everything but there is no mail. So please activate our account or send us the activation mail please.

To be clear the username in question is **loginsecure.eu** not hennysmafter!

Thank you very much for your time answering and helping us!
