### ISSUE TITLE
No verification email after registering and then user is blocked message?

### ISSUE THREAD

**Issue by hennysmafter** [joomla/jed-issues#123]
Reopening incorrectly closed ticket.
https://github.com/joomla/jed-issues/issues/122

From the above link:

@anibalsanchez

I have not solved it I can still not log in. I just tried it again and it says that we still need to accept the verification email but there is no mail whatsoever.

We checked spam and everything but there is no mail. So please activate our account or send us the activation mail please.

To be clear the username in question is loginsecure.eu not hennysmafter!

Thank you very much for your time answering and helping us!

**Comment by anibalsanchez** [comment]
Hi,

I've confirmed that the user has been removed from the system (since the system didn't receive the email activation).

Please, try to register again.

**Comment by hennysmafter** [comment]
Hey @anibalsanchez 

Thank you for that and we just tried it and we are now registered and logged in. 
The submit extension button is greyed out however and it says that we need to complete the account profile. But when we go to the account profile we see that everything is already filled in. Also when we click on the greyed out button we still get to see the submit extension form so maybe there is a slight bug?

Thanks again and looking forward to your answer.

**Comment by anibalsanchez** [comment]
Great.

You have to complete the **Developer Name** to be allowed to send extensions.

Regards

**Comment by hennysmafter** [comment]
Hey @anibalsanchez 

Thank you for that suggestion we already had that filled out when we registered. But just did it again and saved and now the button is blue! Yippie. 

Thank you so much for helping us with these issues.

Have a great day.
