### ISSUE TITLE
Can't make reviews

### ISSUE THREAD

**Issue by korbeny** [joomla/jed-issues#124]
Every time I tried to make a review of an extension, I get the same error (image attached). I tried with a new account and from other computer and place and get the same error.

![chrome_2019-10-22_18-21-56](https://user-images.githubusercontent.com/7292662/67353958-7eb09500-f519-11e9-9e25-66c939bb7839.png)

**Comment by anibalsanchez** [comment]
Please, follow the previously reported issue #85

**Comment by anibalsanchez** [comment]
Thanks for reporting!
