### ISSUE TITLE
Search plugin is not working for particular features in website (Accordion tab model content is not searchable)

### ISSUE THREAD

**Issue by Rajandaniel** [joomla/jed-issues#125]
Hi Team,
In our website, we have smartsearch plugin, It was not seaching the data which are in accordion tab model content. We have also tried your free search plugin RokAjaxSearch, BT Smart Search and RSsearch. But still the files which are in accordion tab model was not searchable in our http://qcdemo.cellarstone.org/product-info/features page. Kindly can you suggest a search plugin solution, which search entire website.

Regards,
Rajan Daniel
E Marketing Executive

**Comment by anibalsanchez** [comment]
Hi,

This ticket system is for JED Directory issues. We are unable to provide support for your issue. For general questions about Joomla and extensions contact the developer directly via their website, or open a new topic on the Joomla Community Forum. http://forum.joomla.org/

Kind Regards
