### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by Sulpher** [joomla/jed-issues#127]
**ATTENTION: If you have a question or you need to contact the JED Team about an Extension, please, contact us via the JED Ticketing System: https://extensions.joomla.org/profile/** 

**Describe the bug**

1. If a JED item has video, there is an error in the console:

Failed to load resource: the server responded with a status of 404 ()
URL: 
https://extensionscdn.joomla.org/plugins/content/jw_allvideos/jw_allvideos/includes/js/quicktimeplayer/ac_quicktime.js?v=4.7.0
Have a look the URL is wrong.

2. The 2nd console error on the JED item page:
Failed to load resource: the server responded with a status of 404 ()

https://apis.google.com/u/0/se/0/_/+1/fastbutton?usegapi=1&size=standard&lang=en-US&parsetags=explicit&annotation=bubble&origin=https%3A%2F%2Fextensions.joomla.org&url=https%3A%2F%2Fextensions.joomla.org%2Fextensions%2Fextension%2Fclients-a-communities%2Fratings-a-reviews%2Fnorrcompetition%2F&gsrc=3p&jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en.7kWSr24wXFc.O%2Fam%3DwQE%2Fd%3D1%2Fct%3Dzgms%2Frs%3DAGLTcCN-4ZptW5UzimRFZRBm6izu5h2ZaQ%2Fm%3D__features__#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh&id=I0_1572633191621&_gfid=I0_1572633191621&parent=https%3A%2F%2Fextensions.joomla.org&pfname=&rpctoken=30076571
 
 
**Screenshots**
![Screen Shot 2019-11-01 at 21 39 04](https://user-images.githubusercontent.com/3432048/68047742-1cf9e300-fcf0-11e9-960d-50ef4dea74e6.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 78.0

**Comment by anibalsanchez** [comment]
Hi,

We are developing the new JED4 that it is going to replace the current system. So, we are not going to update the current implementation, focusing our efforts on the operation and developing JED4 until we can replace the current directory implementation.

Thanks for reporting.
