### ISSUE TITLE
JED stopped sending notification emails for new reviews

### ISSUE THREAD

**Issue by tassosm** [joomla/jed-issues#129]
My extensions have received quite a lot of reviews in the last couple of months but I never got a notification email letting me know about the reviews. 

Has JED stopped sending those emails?

**Comment by anibalsanchez** [comment]
Hi,

I've just sent a couple of tests and it is working Ok.

Just in case, I've updated the SPF, DMARC and DKIM records.

Hope this helps! Let us know if there is anything else we can do.
