### ISSUE TITLE
Logo not saving to listing

### ISSUE THREAD

**Issue by corywebb** [joomla/jed-issues#13]
I have added a new listing, and the logo isn't saving. I have tried editing the listing to re-add the logo, but nothing seems to be working.

Steps to reproduce:

1. Create a listing.
2. Fill out all of the required fields.
3. Add a logo image.
4. Save.

**Comment by corywebb** [comment]
It appears that there is something wrong with the system that is causing it to corrupt the image on upload. I tried using different images, and I get the same result.

**Comment by PhocaCz** [comment]
Hi, I can confirm, I have the same/similar problem:

https://github.com/joomla/jed-issues/issues/16

**Comment by nikosdion** [comment]
Same here. Right now Akeeba Backup has no logo because the uploaded doesn't work with any image.

**Comment by PhocaCz** [comment]
Hi Nicholas,
the same happens with the images of the listing.

**Comment by nikosdion** [comment]
@PhocaCz I think the problem has to do with the image upload / resize they are using.Or the CDN integration. I'd have no problem if they allowed us to submit a URL with the cover photo of the extension. At this point it's more damaging to us not having any cover photo / listing images than paying for a CDN to host these images out of our own pocket.

**Comment by anibalsanchez** [comment]
Hi,

JED has a tmpfs as image cache that reached 100%. It was cleared (as it was done several times in the past) but the drive is still reporting to be full. 

I'm looking into the issue and updating the ticket as soon as I have news.

Thanks for reporting.

**Comment by corywebb** [comment]
Thanks @anibalsanchez! Looking forward to seeing this get resolved.

**Comment by anibalsanchez** [comment]
From the technical support:

*I have taken a look and found that you hit the inode limit for the temporary filesystem on your 'cache' folder, so I've doubled it now.*

Resolved! Please, check your extension and reupload the images if it's necessary.

**Comment by corywebb** [comment]
@anibalsanchez I checked my extension, and the image is there. I didn't have to re-upload it. Thanks!

**Comment by nikosdion** [comment]
I can confirm it works again! Thank you :)

**Comment by PhocaCz** [comment]
I works OK now. Confirmed, thank you.

**Comment by anibalsanchez** [comment]
Hi,

Yes, the cache of 22GB has reached again 100%. I've just requested to cleared it again and increase the size.

Regards,

**Comment by CoalaWeb** [comment]
Great thanks for such a fast response.

**Comment by CoalaWeb** [comment]
I just updated several logos and they are displaying as expected, thanks.

**Comment by anibalsanchez** [comment]
Yes, we're now checking if we can schedule a timely cache purge.

Thanks,
