### ISSUE TITLE
No activation email

### ISSUE THREAD

**Issue by tassosm** [joomla/jed-issues#130]
One of my customers tried to create an account today to write a review but he never received the activation email. 

Please advise accordingly.

**Comment by anibalsanchez** [comment]
Hi,

The mailing system works Ok. So, the most probable cause is that the mail was sent to the Spam folder (or the user wrote a bad email).

Hope this helps! Let us know if there is anything else we can do.

**Comment by ManfredHuebner** [comment]
I am the one with the email problems and I can confirm there must be a problem:

- I was already registered with an email address (systems confirms that if I tried to register with this address again). So I tried to get my password reset. But mail did not receive, neither in inbox nor in spam. This is with a big email hoster in Germany.

- I decided to create a new account, but activation mail never comes (my own mail server; this server has grey listing activated).

Would be glad if I could create an account for the JED but i cannot. With no joomla site world wide I have problems in creating account, only on joomla.org - that cannot be normal ;-)
