### ISSUE TITLE
Problem with email activation / account creation

### ISSUE THREAD

**Issue by ManfredHuebner** [joomla/jed-issues#132]
**ATTENTION: If you have a question or you need to contact the JED Team about an Extension, please, contact us via the JED Ticketing System: https://extensions.joomla.org/profile/** 

**Describe the bug**
I am the one with the email problems and I can confirm there must be a problem:

    I was already registered with an email address (systems confirms that if I tried to register with this address again). So I tried to get my password reset. But mail did not receive, neither in inbox nor in spam. This is with a big email hoster in Germany.

    I decided to create a new account, but activation mail never comes (my own mail server; this server has grey listing activated).

Would be glad if I could create an account for the JED but i cannot. With no joomla site world wide I have problems in creating account, only on joomla.org - that cannot be normal ;-)

**Comment by anibalsanchez** [comment]
We have found an issue in the mail configuration that was generating delivery issues.

It has been fixed. Please, check it again and report if the issue remains.
