### ISSUE TITLE
JED review problem

### ISSUE THREAD

**Issue by jancsi88** [joomla/jed-issues#135]
Hello,
I found a very similar issue on the repo, but since it is closed I decided to open a new one.
[https://github.com/joomla/jed-issues/issues/114](https://github.com/joomla/jed-issues/issues/114)
Some of our users wrote us becuase they would like to leave a review on our extension, but they can not:
[https://extensions.joomla.org/extension/creative-slider/](https://extensions.joomla.org/extension/creative-slider/)

We received some screenshots about the issue. (He tried in normal and in incognito mode too)
Could you please check on this?
Thank you!
![image4](https://user-images.githubusercontent.com/60389735/73264314-c6a71e00-41d2-11ea-8a51-be7a52c318c6.jpg)
![image3](https://user-images.githubusercontent.com/60389735/73264315-c6a71e00-41d2-11ea-9958-73973c3e3056.jpg)
![image2](https://user-images.githubusercontent.com/60389735/73264316-c73fb480-41d2-11ea-85d2-f70cb3017349.jpg)
![image1](https://user-images.githubusercontent.com/60389735/73264317-c73fb480-41d2-11ea-92c5-37d9160fbbbb.jpg)

**Comment by anibalsanchez** [comment]
Please, follow #114
