### ISSUE TITLE
Ajax universal search bug

### ISSUE THREAD

**Issue by bryan-0101** [joomla/jed-issues#136]
Hello!

We have some issues with ajax universal search in Joomla!

When we manualy go to product at metalacbojler.com (products/storage water heaters/mb standard/inox dry heater), there is result which is ok of course.
https://www.metalacbojler.com/en/products/storage-water-heaters/2-metalacbojler/193-mb-standard-inox-dry-heater.html

But, when we type in search bar "mb standard inox dry" home page shows up, but the link in the adress bar is not home page. It's somehow related to product, but not complete. https://www.metalacbojler.com/en/75-mb-standard-inox-dry-heater/193-mb-standard-inox-dry-heater.html

In Joomla we've set to search only in "content" where the products are.
I'm sorry for disturbing, but I couldn't find answers anywhere.
If you are willing to help me, I'd be very grateful!
There is a video I've recorded so you can see what is happening.

https://drive.google.com/file/d/1umJe3yw-rHbpYoyFUIl2I5MsbyOITeaZ/view?usp=sharing

Thanks in advance!

Best regards

**Comment by anibalsanchez** [comment]
Hi,

This ticket system is for developers/users to report issues about JED. 

We are unable to provide support for your issue. For support questions about how to use an extension, please contact the developer directly via their website.

Kind Regards

**Comment by bryan-0101** [comment]
Ok, thanks a lot.
