### ISSUE TITLE
Templates on JED

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#138]
**Templates on JED**: At this time, the topic of publishing Templates on JED has come up again. 

The aim of the current JED Team is supporting all types of Joomla extensions on the directory. 

Since the previous effort to create a Template Directory for Joomla (JTD) is inactive ([OSM, Inc. - Full Board Meeting - October 18, 2018](https://volunteers.joomla.org/board-of-directors/reports/904-osm-inc-full-board-meeting-october-18-2018)), and the time of new ideas around Joomla 4 campaign has arrived, we are going to prepare a proposal for the board. 

Technically speaking, JED already has everything to add a new category for templates (in fact, we process and check template submissions today, and reject them due to not being allowed). 

We are also going to gather information from the previous JTD experience and checking the idea with other community members. At this time, the licensing of Templates on JED would follow a GPL / Creative Commons license model. 

At FFTF, people requested several times to add templates on JED, and we accept that it is a frequent request. 

At this time, our priority is focusing all efforts of J4 and JED4 launch.

**Comment by anibalsanchez** [comment]
**About Templates on JED - GPL / Creative Commons (CC) licenses**: 

CC Licenses are free of charge to the public. These licenses allow creators to communicate which rights they reserve and which rights they waive for the benefit of recipients or other creators. An easy-to-understand one-page explanation of rights, with associated visual symbols, explains the specifics of each Creative Commons license. Creative Commons licenses do not replace copyright but are based upon it. They replace individual negotiations for specific rights between copyright owner (licensor) and licensee, which are necessary under an "all rights reserved" copyright management, with a "some rights reserved" management employing standardized licenses for re-use cases where no commercial compensation is sought by the copyright owner. The result is an agile, low-overhead and low-cost copyright-management regime, benefiting both copyright owners and licensees. For more info: https://en.wikipedia.org/wiki/Creative_Commons, https://creativecommons.org/, and Comparison of free and open-source software licenses.

**Comment by anibalsanchez** [comment]
- Recently a new Joomla template directory has been published, maintained by members of the community, and with an open process to accept new submissions. https://themeglobe.com/joomla/
- To submit new templates: https://github.com/ciar4n/themeglobe
- Since the basic requirement of a general template directory for Joomla is covered, we close the JED issue.

**Comment by mbabker** [comment]
> Since the basic requirement of a general template directory for Joomla is covered, we close the JED issue.

So basically the project's stance is "well, a community member created an unofficial template directory, so the project doesn't need to follow through on a official solution"?  (Not that I disagree with this stance, these days I'm practically to the point that Google is a better solution for extension lookups than the JED, but that statement should be made a bit more clearly so people understand why JED has decided it doesn't need templates again)
