### ISSUE TITLE
Trying to upload the new image a "-200: HTTP Error"

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#142]
Reported by thePHPfactory, Advertisement Factory.

**Comment by anibalsanchez** [comment]
Unable to reproduce it and we didn't receive new reports.

**Comment by thephpfactory** [comment]
We encounter this issue only on this extension (we have over 30 listed). Also the same error comes when trying to upload a new version (extension kit). This happens only on Advertisement Factory, we are not able to change the image, nor to put a new kit. 

What can we do to update? Can I send to someone the new kit and the image to perform the update, if we are not able to?

**Comment by thephpfactory** [comment]
I posted here two screenshots with the error on JED:
https://imgur.com/a/XM4zabH

**Comment by anibalsanchez** [comment]
Since the issue is only found in your setup, please, send us more info about your local configuration. Additionally, please, try with a different browser/network.

**Comment by thephpfactory** [comment]
We tried this under FF, IE and Chrome; on all the same  -200: HTTP Error

First we delete the old kit (or image), then we upload a new kit or image. When the upload finished the -200: HTTP Error appears.
If we hit ok on the error and try to save, this https://ibb.co/StYj5fV comes up (although the new image seems to be there).

**Comment by thephpfactory** [comment]
It seems meanwhile this was fixed. Thank you!

**Comment by anibalsanchez** [comment]
Excellent,

Best Regards
