### ISSUE TITLE
Searching does not work

### ISSUE THREAD

**Issue by PhocaCz** [joomla/jed-issues#143]
**Describe the bug**
When I try to find "Phoca Gallery", I get some results but no "Phoca Gallery" (in search results, in the results offered) 

![No Phoca Gallery serch](https://pbs.twimg.com/media/EQl8XuuXkAMdyLh?format=png&name=small)

**To Reproduce**
1. Go to https://extensions.joomla.org/
2. Type "Phoca Gallery" into the search box

**Expected behavior**
Phoca Gallery will be found

**Screenshots**
![No Phoca Gallery serch](https://pbs.twimg.com/media/EQl8XuuXkAMdyLh?format=png&name=small)

**Desktop (please complete the following information):**
 - OS: Win, Linux
 - Browser Firefox, Chrome, Opera

**Comment by anibalsanchez** [comment]
Duplicate #143
