### ISSUE TITLE
No change in Joomla! administration after editing item on JED

### ISSUE THREAD

**Issue by PhocaCz** [joomla/jed-issues#144]
**Describe the bug**
When I edit and save download links on JED, "Install From" link in Joomla! CMS administration (Extensions - Install - Install from Web) will be not changed.

![No Change after edit](https://pbs.twimg.com/media/EQmAR__XkAAntuI?format=png&name=small)

**To Reproduce**
1. Go to https://extensions.joomla.org/
2. Add, edit or update download link form fields
3. After saving, no changes are displayed in Joomla! CMS administration (Extensions - Install - Install from Web) 
4. Setting 0 for cache the extensions in Joomla! administration (Install from Web) - no change

**Expected behavior**
New link will be displayed.

**Screenshots**
![No Change after edit](https://pbs.twimg.com/media/EQmAR__XkAAntuI?format=png&name=small)

![No Change after edit](https://i.imgur.com/p6K326r.png)

**Desktop (please complete the following information):**
 - OS: Win, Linux
 - Browser Firefox, Chrome, Opera

**Comment by anibalsanchez** [comment]
The JED download URLs are not related to the Install for Web (IFW) feature on the Joomla administration.

The  JED download URL field is shown on the front-end to download the extension.

IFW is based on the installer manifest of the extension, where the "Update Site" is declared. 

Hope this helps! Let us know if there is anything else we can do.

**Comment by PhocaCz** [comment]
Hi, can you please provide me more detailed information.

My manifest is:
https://raw.githubusercontent.com/PhocaCz/PhocaGallery/master/manifest.xml

```<updates>
	<update>
		<name><![CDATA[ Phoca Gallery ]]></name>
		<description><![CDATA[ Phoca Gallery is an efficient image gallery extension for Joomla! CMS. ]]></description>
		<element>com_phocagallery</element>
		<type>component</type>
		<version>4.3.18</version>
		<infourl title="Phoca Gallery 4.3.18">http://www.phoca.cz/version/index.php?phocagallery=4.3.18</infourl>
		<downloads>
			<downloadurl type="full" format="zip">https://github.com/PhocaCz/PhocaGallery/releases/download/4.3.18/com_phocagallery_v4.3.18.zip</downloadurl>
		</downloads>
		<tags>
			<tag>stable</tag>
		</tags>
		<maintainer><![CDATA[ Phoca.cz ]]></maintainer>
		<maintainerurl>https://www.phoca.cz/</maintainerurl>
		<section>Updates</section>
		<targetplatform name="joomla" version="3.9"/>
		<client>1</client>
	</update>
</updates>


```

My phocagallery.xml is:

```
<?xml version="1.0" encoding="utf-8"?>
<extension type="component" method="upgrade" version="3">
...
		<server type="extension" name="COM_PHOCAGALLERY" priority="1"><![CDATA[https://raw.githubusercontent.com/PhocaCz/PhocaGallery/master/manifest.xml]]></server>
	</updateservers>
</extension>
```

Isn't it the downloads/downloadurl attribute?

**Comment by anibalsanchez** [comment]
Please, check this link:

**Joomla! Update System requirement
 / What is the Joomla! Update System?**

https://extensions.joomla.org/support/knowledgebase/item/joomla-update-system-requirement/

**Comment by PhocaCz** [comment]
I don't have any problem with update system, it works like expected:

![Phoca Gallery Update Info](https://i.imgur.com/GvLKZCq.png)

![Phoca Gallery Update Success](https://i.imgur.com/qV18n10.png)


The problem is only inside Install from Web

![Problem Install from Web](https://i.imgur.com/prLQIqu.png)

```
<a class="install btn btn-success" href="#" onclick="return Joomla.installfromweb('https://www.phoca.cz/download/category/1-phoca-gallery-component', 'Phoca Gallery')"><span class="icon-checkmark" aria-hidden="true"></span> Install…</a>
```

The URL is wrong and such URL is not defined in XML files  :bulb:

**Comment by anibalsanchez** [comment]
IFW is operated by the core team. It was developed well before I joined the JED team. So, I don't know how it exactly works. I guess that it extracts the extension information from JED and it has its own cache.

To investigate the case, you can look into the code here: https://github.com/joomla/install-from-web-server

**Comment by PhocaCz** [comment]
I can debug the answer from Joomla! server:
https://appscdn.joomla.org/webapps/index.php?option=com_apps&format=json&view=extension&id=150&product=Sm9vbWxhIQ==&release=My45&dev_level=MTE=&list=grid&pv=Mi4wLjE=&callback=jedapps_jsonpcallback

but unfortunately I have no access to JED server to debug which information it returns :-(

**Comment by anibalsanchez** [comment]
com_apps is not an extension on JED. In some way, IFW interacts with JED, but I don't know how.
