### ISSUE TITLE
JED Search: the proximity of two search words is no ranking factor

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#145]
**Describe the bug**
Reported by @gitjk, the proximity of two search words is no ranking factor. Please, @gitjk describe in detail the case and how to reproduce it.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Gitjk** [comment]
Hello Anibal,
yesterday I thought Algolia does not rank two search words in close proximity better than cases where two search words are for example 100 words apart in the extension description. Checking a again, I now think it does. But maybe you can consider to allow some advanced search syntax, as described here:
[https://www.algolia.com/doc/api-reference/api-parameters/advancedSyntax/](url)

**Comment by anibalsanchez** [comment]
I've checked the information, however, I don't see (or I don't know) how we can apply it to our current search implementation.

I've updated the search documentation to the current configuration: https://github.com/joomla/jed-issues/wiki/JED-Search-use-cases-and-definitions

If you can send us specific recommendations, we'll be happy to test and implement them.

Since this issue is not actionable, I'm closing the issue. If you have more info to add, feel free to reply here.
