### ISSUE TITLE
JED Newsletter - Remove Google+

### ISSUE THREAD

**Issue by conconnl** [joomla/jed-issues#146]
@anibalsanchez 
As discussed an issue registration to remember it.
Please check the JED Newsletter configuration to make sure Google+ isn't there anymore

**Comment by anibalsanchez** [comment]
Hi,

I haven't found any occurrence of G+ https://extensions.joomla.org/newsletter/.

I think that the issue is already solved.

If not, please, include the specific page. Txs!
