### ISSUE TITLE
JED CDN is broken 

### ISSUE THREAD

**Issue by webcomil** [joomla/jed-issues#152]
the JED from Israel looks not as it should 
therefore cannot work with 
opening he google chrome console brings many 502 errors.

1. Go to 'JED homepage' at:  https://extensions.joomla.org/ from israel
2.  see the website is broekn
3. See error one console: of js files with error 502 bad gateway.

on all browsers.
see attached images
![broken_JED_error](https://user-images.githubusercontent.com/6807507/77868641-9e748380-7244-11ea-9e15-8320cf5a7c04.jpg)
![broken_JED_view](https://user-images.githubusercontent.com/6807507/77868643-9fa5b080-7244-11ea-8e2a-4d3436aa1525.jpg)

**Comment by anibalsanchez** [comment]
It works fine from here (Spain). Where are you located?
