### ISSUE TITLE
[JED] No 2FA Configuration in the frontend

### ISSUE THREAD

**Issue by zero-24** [joomla/jed-issues#156]
**Describe the bug**

It is not possible to configure 2FA from the frontend

**To Reproduce**

Login as extension developer
Notice that there is no way to configure 2FA for that account.

**Expected behavior**

As an developer I'm able to setup 2FA to my account.

**Screenshots**
![image](https://user-images.githubusercontent.com/2596554/79668829-daea2e00-81b7-11ea-9bd4-73f80a5a8475.png)

**Comment by anibalsanchez** [comment]
@conconnl Please, could you check the case.

**Comment by conconnl** [comment]
Nothing to check for me. 
The site doesn’t use the default joomla system, it’s something in com_jed. 
The developer needs to fix this as 2FA is required for at least all super users, so I must work in the front end.

**Comment by zero-24** [comment]
@anibalsanchez can you add an menu entry for the core user profile view that should include all code nesesarry for 2fa?

**Comment by anibalsanchez** [comment]
Give me a week to check why it was customized in this way. If it's possible I'll restore the original core functionality.

**Comment by zero-24** [comment]
Awesome ping me when you need help on that.

**Comment by anibalsanchez** [comment]
Thank you in advance @zero-24 !

**Comment by zero-24** [comment]
Ok got it working on the stage site:
![image](https://user-images.githubusercontent.com/2596554/80159667-e11f4680-85cb-11ea-9bd6-dfce0fbf5341.png)

Right now the way to enable it woud be just to create an com_users menu entry to edit the user:
![image](https://user-images.githubusercontent.com/2596554/80159752-0e6bf480-85cc-11ea-82eb-a729a2640505.png)

Please advice how we should proced from here @anibalsanchez ? I could write an override so that we remove / hide the fields you are supposed to be handle by the JED extension.

But I would say it is not that critical as it seems this fields are synced too.

So my proposal would be to publish an com_users profile view on the JED with the lablel 'User Settings'

It would look like this in the menu
![image](https://user-images.githubusercontent.com/2596554/80159951-9ce07600-85cc-11ea-9a82-4acf2cc2ce50.png)

And this from the backend:
![image](https://user-images.githubusercontent.com/2596554/80159976-ae298280-85cc-11ea-95a8-c0efbe94e01f.png)

What needs to be the next steps to make that change?

Or do you want me to take a look into the override that just shows that additional User settings from the core view?

**Comment by anibalsanchez** [comment]
Great news.

We can organize the JED User Management in this way:

- **Profile / User Settings**, as you shown based on com_users / profile view
- **JED Account**, to manage only *Developer Name* and the rest of the user fields as read-only or hidden fields.

Since this organization is going to be the new JED User Management. We can disable the modification of the core user fields from JED. I think that it is safe to change it directly on com_jed. To disable it, without extensive modifications, I think that you can hide them or change them to read-only. com_jed will not change these fields anymore:

- name
- username
- email
- password

Please, send a PR to change the *com_jed&view=profile&layout=details* to the repo (development branch) and I'll merge to apply it on stage and the live site.

Thanks in advance!

**Comment by zero-24** [comment]
Ok will take a look thanks.

**Comment by conconnl** [comment]
Is the Developer Name something in com_jed ?
I ask because I expect you could use a custom user field to have the same field.
Only depending on where it needs to be stored we need a separate plugin, which is not very difficult to do.

**Comment by zero-24** [comment]
Why do we need that developer name anyway?

**Comment by anibalsanchez** [comment]
The `developer_name` is a com_jed field, currently stored in the JED tables, and used in many features. Since JED3 is feature freeze, we look for ways to improve the site without changing com_jed extensively.

About the need of the `developer_name`, there is a nasty bug, that took me a couple of months to discover, that prevented the modification of extensions when there is no defined Developer Name. As a work-around, there is a query now that fills the Developer Name with the user name when it is empty. So, I think we can safely remove the custom login and the custom registration form, leaving the `developer_name` management to the Account tab.

**Comment by zero-24** [comment]
> So, I think we can safely remove the custom login and the custom registration form, leaving the developer_name management to the Account tab.

can you check how many username are not the same like developer_name from the database? When it is not used we might just drop that account tab to reduce the complexety right?

**Comment by anibalsanchez** [comment]
@zero-24 Most developers have defined the Developer Name. In fact, if you are a business, the Developer Name must be your real company name.

The user management is now in the com_users components. Please, check if everything works as expected.

**Comment by zero-24** [comment]
work good can you move the profile and logout menu entry here:
![image](https://user-images.githubusercontent.com/2596554/80283088-8c87e280-8715-11ea-93c9-c22e81de90f3.png)

**Comment by anibalsanchez** [comment]
@zero-24  Sure?  I think that's better if we keep the navbar clean. The modification of the user profile or the logout is not something that you want to find in front of the most frequent use case (the search).

**Comment by zero-24** [comment]
Hmm when you look for other web apps and even joomla logout and profile is on the top right position and even the login is there so tobl me it is confusing to look under Support to logout and find my Profile

**Comment by anibalsanchez** [comment]
okok, I'll check how it can be accommodated there on the right side.

**Comment by conconnl** [comment]
In the new template version the login will change to logout in the footer of all our website.

**Comment by zero-24** [comment]
> okok, I'll check how it can be accommodated there on the right side.

awesome.

> In the new template version the login will change to logout in the footer of all our website.

Sure when the new template is out we can check that again right?

**Comment by conconnl** [comment]
I can also add the change to the needed file.
I can't generate the release until the Compliance team adds the Cookie Script.
JED has edits on the default template, so update can't be done in the normal way.

Let me know what to do and I will add the change in GitHub

**Comment by conconnl** [comment]
@anibalsanchez if you implement this, then the logout button in the footer will really log someone out. https://github.com/joomla/jdotorgtemplate/commit/676bd00e970a2f00182b5ae686a05bb4a48e7062

**Comment by anibalsanchez** [comment]
As suggested by @zero-24 , I've moved the Log Out and User Profile links to the same position than the Log In and Register links.

2FA is fully enabled.

**Comment by anibalsanchez** [comment]
I've just completed the separation of com_jed and com_users. The user management is based on Joomla core now. 

In theory, all core user features (including 2fa and captcha) work as designed at the core-level and we shouldn't have other impacts on com_jed.

Please, keep an eye on user feedback. From my side, there is no more tasks for this issue.

**Comment by anibalsanchez** [comment]
The new user management organization is implemented and working well. Case closed.
