### ISSUE TITLE
After updating the image, the preview is not displayed on the search page

### ISSUE THREAD

**Issue by de1vin** [joomla/jed-issues#157]
After updating the image, the preview is not displayed on the search page.
https://extensions.joomla.org/instant-search/?jed_live%5Bquery%5D=getbutton
![Annotation 2020-04-20 173104](https://user-images.githubusercontent.com/11943785/79763442-c4b1ae80-832c-11ea-82b6-12b25db575f2.png)

**Comment by anibalsanchez** [comment]
This is related to the way that the search crawler works and when it updates the index.

We have increased the frequency to solve the issue. #165 

Thanks for reporting.
