### ISSUE TITLE
Invisible reCAPTCHA?

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#158]
A user reported in the forum that it was not possible to register on JED: https://forum.joomla.org/viewtopic.php?f=262&t=979622

I confirmed the issue and it seems that the problem is caused by the Invisible reCAPTCHA configuration. I think that it is part of the recent changes.

I have changed the captcha to "CAPTCHA - reCAPTCHA" to re-enable the user registration.

Please, confirm if we continue using this captcha or the Invisible reCAPTCHA. Maybe there is a mismatch in the keys.

**Comment by conconnl** [comment]
For me it's rather simple.
JED must follow the Joomla user functionalities.
Invisible reCAPTCHA is the latest and safest method in Joomla, a feature which exist for years.
If JED doesn't follow the defaults and have the old one hardcoded it's needs to be fixed.

That you temporary use the older version, to keep it working, doesn't off course mean it's the right way.

**Comment by anibalsanchez** [comment]
@zero-24 The current registration seems to be incompatible with **Invisible reCAPTCHA**. 

I think we could also drop the custom com_jed registration from. The value of the current form is that it includes the **Developer Name**. So, I think that we could remove it and to move the site to the standard login form and registration form.

What do you think  @zero-24 ? We could try to migrate at the same time that we improve Account management. #156

**Comment by zero-24** [comment]
I can take a look other the weekend maybe any pointers where to look?

Where is that developer name in com_jed? And why does it need to be a dedicated field anyway?

**Comment by anibalsanchez** [comment]
The idea is removing the current /register/profile/edit, changing **Log in** and **Register** to target the core User component features.

I think that there is no need of code modifications. Chekc the details here: https://github.com/joomla/jed-issues/issues/156#issuecomment-618949284

**Comment by zero-24** [comment]
ok lets wait for that to be up an running. So we can use the core captcha stuff.

**Comment by anibalsanchez** [comment]
The user management is now in the com_users components.

However, com_jed has captchas that must be reviewed to check if they work with the Invisible reCaptcha.

**Comment by zero-24** [comment]
Where do com_jed use captchas so we can review and test the code?

**Comment by anibalsanchez** [comment]
Check the Account edition tab.

Only the "Developer Name" field must remain.

But, also the core user fields are still being included and probably the captcha with them.

**Comment by zero-24** [comment]
It seems i still see al fields: 
![image](https://user-images.githubusercontent.com/2596554/80292282-d09ad780-8755-11ea-9e4e-992af71fc21d.png)

And it seems that the captcha at the bottom:
![image](https://user-images.githubusercontent.com/2596554/80292295-fd4eef00-8755-11ea-98a1-d92fd06799dc.png)

is ignored now as i have not to pass it to get the changes saved.

@anibalsanchez @conconnl would you mind enableling the 2fa yubikey plugin too?

**Comment by conconnl** [comment]
Anibal temporary enabled the old recaptcha method. The invisible version should be used and then captcha bar won’t be visible. 

I don’t see any reason why we wouldn’t enable Yubi as well, especially if everything is handled by com_users

**Comment by conconnl** [comment]
@anibalsanchez can we enable invisible CAPTCHA again, now com_users is used?
There are a lot of spam registrations.
I'm deleting at least 10 users a day with non-existing mail address or even domain names.

**Comment by anibalsanchez** [comment]
- I've re-enabled invisible CAPTCHA.
- I've enabled **Two Factor Authentication - YubiKey**.  @zero-24 Please, check it (I don't have a Yubikey to test :-( )

**Comment by anibalsanchez** [comment]
I've just completed the separation of com_jed and com_users. The user management is based on Joomla core now. 

In theory, all core user features (including 2fa and captcha) work as designed at the core-level and we shouldn't have other impacts on com_jed.

Please, keep an eye on user feedback. From my side, there are no more tasks for this issue.

**Comment by anibalsanchez** [comment]
The invisible captcha has been working fine. Case closed.
