### ISSUE TITLE
JED Newsletter on CJO

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#159]
The JED Newsletter will be migrated and find a new home to CJO. https://community.joomla.org/

**Comment by conconnl** [comment]
I have two options to create the new list within CJO.
1. Export the current developers list 2356 users.
2. Receive from you the list with the real extension developers on the site, for this I need name,email.

In CJO their are new templates to use for newsletters.
My suggestion here is to copy one, change it a little bit to your needs, so this is updated  as well.

**Comment by conconnl** [comment]
@anibalsanchez Can I please have an answer.
The longer we wait the bigger the chance the Confirmed user list is very short.

**Comment by anibalsanchez** [comment]
Agreed. **1**

**Comment by JazParkyn** [comment]
Has the current list in Acy (option 1) been kept up to date from com_jed though? If not a new export would be better (option 2).

**Comment by anibalsanchez** [comment]
As far as I know, it has been working in this way for ages and we (the current team) haven't changed until now.

So, it is safe to move it as it is now.

Option 2 goes one step further and would contact all extension developers (regardless if they subscribed the newsletter).

**Comment by conconnl** [comment]
For me it doesn't matter at all.
The fact is simple.....
* If you want to reach all your developers in the future, we need to full list and ask consent.
* If it doesn't matter to JED team, I will use the old list and ask consent.

**Comment by anibalsanchez** [comment]
In my opinion, if we are defining the newsletters, **1**. People subscribe to the newsletter and we contact them about the newsletter. So, we have to manage the current list of subscribers.

Contacting different segments of users (all or owners of extensions), due to different circumstances, it is another matter.

**Comment by conconnl** [comment]
The newsletter list is created on CJO, all users are imported and they have received an confirm request based on the template created by Marketing.

The subscribe page is created: https://community.joomla.org/joomla-extensions-directory-newsletter.html
The archive page is created: https://community.joomla.org/extensions-directory-newsletter-archive.html
The thank you page after subscribing is created: https://extensions.joomla.org/extensions-directory-newsletter-thank-you/

All found links on extension website are changed, redirected or updated.

To do:
Check if we can migrate old newsletters to display in archive.

Suggestion:
Create an promotional text, banner or something else on the home page for 1 or 2 weeks to tell the visitors the newsletter will be used again by JED Team and that they can subscribe.

**Comment by anibalsanchez** [comment]
Great work @conconnl !

Now, an opinion, **be warned**: _I'm picky and I'm not a designer_. Please, _feel free to ignore the following opinion_, I'm only writing it here to check if it can be incorporated in the process in some way.

1. The mailing template is showing the tables.
2. The mailing template changes the text size proportions on mobile

![Confirmation - Desktop](https://blog.anibalhsanchez.com/images/JED/jed-confirmation-desktop.jpg)

![Confirmation - Mobile 1](https://blog.anibalhsanchez.com/images/JED/jed-confirmation-mobile1.jpg)

![Confirmation - Mobile 2](https://blog.anibalhsanchez.com/images/JED/jed-confirmation-mobile2.jpg)

A practical solution that has worked for me is [Cerberus Responsive Email Patterns](https://tedgoas.github.io/Cerberus/). You only have to paste the styling sheet and the email HTML layout.

**Comment by conconnl** [comment]
Sorry, this is not something I can do anything with.
Templates are build and maintained by Marketing, this is just the default automatic confirm message. Which is used by AcyMailing by default. I just pressed send.

I know someone is implementing the new AcyMailing 6, with new designs, templates etc.
I'm also not an designer, so I'm not going to mingle with it. (I will certainly break things)

Additionally on my phone I don't see the table lines.
The same that Michael doesn't see a readable mail in his Dark Mode mail client and I can see it in my dark mode client.

**Comment by conconnl** [comment]
....
Another problem we have to fix, is that the templates hacks breaks the default layout designs of our articles etc.
For now I'm going to add inline styles to the thank you page, to revert all unnecessary template changes.

The new JED must follow our default template any any CSS change should be done correct for a specific page and not overwrite the whole template.

**Comment by conconnl** [comment]
.....
The newsletter break is because of JCE use, it changes some structure

**Comment by conconnl** [comment]
All required issues are done, including removal of the extension
