### ISSUE TITLE
No image displayed after editing the listing

### ISSUE THREAD

**Issue by PhocaCz** [joomla/jed-issues#16]
Hi,

when I upload an image to JED listing, such is displayed in edit mode, stored but not displayed in frontend, see image:

![http://i.imgur.com/QLmZQFA.png](http://i.imgur.com/QLmZQFA.png)

When I save the listing, no image is displayed
When I resave it, the image changes the name to some internal string but also not displayed
Sometimes it displays the raw string (missing image) in main page

See:
https://extensions.joomla.org/extensions/extension/extension-specific/extensions-specific-non-sorted/phoca-documentation-category/ - there is no image

But in administration of the listings, there is logo image and also no other images.

Is there some limit for this or some problem?

Thank you, Jan

**Comment by vietvh** [comment]
We have exactly the same issue while changing logo for one of our extensions

**Comment by anibalsanchez** [comment]
Hi,

The issue has already been reported before. It's related to an issue in the image cache.

Please, follow the previous issue here: https://github.com/joomla/jed-issues/issues/13

Closing this issue as duplicate.

Thanks for reporting!

**Comment by PhocaCz** [comment]
Hi, thank you, it works OK now.

**Comment by luX0r-reload** [comment]
Hi,
I changed the image in one of the extensions, but now no images appear for it in the search results.
It's ok in the extension page and in the "Other extension" tab.

**Comment by mfleeson** [comment]
The images for search are supplied by Algolia which is only updated once a day. I've manually run the update so your correct image will now be shown.

**Comment by luX0r-reload** [comment]
Thank you!
