### ISSUE TITLE
JED CI - cPanel ssh-agent issue

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#160]
As we discussed on glip, there is an issue on cPanel and implementation of the ssh-agent management.

Today, we have a script that runs, pull changes from the repository and apply the changes automatically with a git hook. The `jed-git-hook-ci.sh` and the post-merge hook. 

cPanel supports ssh authentication.... but when the cronjob runs, the `ssh-agent` can be inactive. So, the CI fails. As a workaround, our script starts initializing the `ssh-agent` and at the end kills the agent (otherwise it creates a new `ssh-agent` for each cronjob execution).

This is the essential `jed-git-hook-ci.sh` that we need to review:

    #!/bin/sh

    # Workaround for the cPanel lack of ssh-agent
    eval "$(ssh-agent -s)" >/dev/null

    # Key to access GH
    ssh-add $HOME/.ssh/id_rsa >/dev/null 2>&1

    # Repo
    cd $HOME/repo/jed

    # Run the hook hooks/post-merge
    git checkout develop >/dev/null 2>&1
    git pull >/dev/null

    # Workaround for the cPanel lack of ssh-agent
    killall ssh-agent

**Comment by conconnl** [comment]
@zero-24 and @conconnl will come with the right way of running this kind of hooks, which will be usable for all Joomla Properties we have, so it is standardized as well.

**Comment by conconnl** [comment]
In the mean time @zero-24 has developed a plugin for this. The documentation for usage, configuration and deployment will be written. 
Which will make it possible for all sites to easily use the GitHub repositories for versioning.

**Comment by anibalsanchez** [comment]
Hi @conconnl , Please, check this comment about the idea of deploying a package with the webserver: https://github.com/zero-24/plg_system_gitdeploy/issues/1

**Comment by conconnl** [comment]
Checked, to much of magical words for me 🤪 Doesn't really matter, specialists are working on these things. I don't have to understand coding. 

The common need is: 
It has to work on every website, without playing around in difficult parts of a system.
It should be triggered / started from an external versioning system (secure off course).
How it runs is up-to specialists, who build it. 

It certainly should not have the problems you are working around. As workarounds are never solutions.

**Comment by anibalsanchez** [comment]
If you are looking for a solution at the organizational level, then a Continous Integration solution is recommended.

Joomla has many sites and the burden of administration is important. So, it makes sense to define a single way of deploying the systems to all servers.

There are many pipelines. So, probably, **Github Actions** would be the first choice for us and it has no maintenance/management costs.

**Comment by conconnl** [comment]
I personally don’t care how it’s done, for that we have specialists working on it. 
As long someone doesn’t have to be a developer, system engineer etc. Most are webmasters, Joomla Administrators, then the solution is fine. As always the best solutions will be created by working together and sharing knowledge.

**Comment by anibalsanchez** [comment]
I concur. Each organization chooses the tool that better solves the case. 

In the Joomla, people frequently want to solve everything with a plugin. For instance, a plugin to simulate a cronjob. However, there are problems that are better solved with the right tool. In this case, CI/CD is better solved with a service already designed for that purpose.

I would check with the rest of the Ops team if they have other preferences. For instance, I think that the Production team use other CI/CD services.

**Comment by conconnl** [comment]
Only we are not allowed to have access to the one from Production (which I totally agree with). We can’t spend money off course. We need to make sure that just webmasters can use it. (I can’t even use what you do). 
Using a plugin to receive the Webhooks calls and configure the settings is not a problem at all. What you do when receiving the call is the discussion which you have with @zero-24 there is never one perfect way. 

It doesn’t matter what I think, Tobias is working on this project and discuss it with others where needed.

**Comment by anibalsanchez** [comment]
Sure. These observations are only my two cents.

**Comment by anibalsanchez** [comment]
The original ssh-agent is gone. Txs @conconnl 

Case closed.
