### ISSUE TITLE
The JED Router Patch and the Trailing /

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#161]
According to the **SEO-JED-ANALYSIS** report, there are **Content duplication issues**.

In particular, to solve the duplication of URLs, it has been implemented a modification of JED and Joomla files to generate URLs with a trailing slash. For instance:

- https://extensions.joomla.org/category/photos-a-images/
- https://extensions.joomla.org/category/photos-a-images/slideshow/

For more information, please, check the documents created in the **JED January Super Sprint Report, Jan 2017**.

To apply this non-standard modification of com_jed and Joomla router.

1. com_jed router is able to process URLs with a trailing /.
1. com_jed defines the canonical link with a trailing /, via an HTTP header.
1. The Joomla router produces URLs with a trailing /.

Since this is a non-standard modification of Joomla, we strive to remove it as soon as possible; we are actively looking for another way to implement it.

**Comment by zero-24** [comment]
Just to make sure i get this correctly.

Right now JED is able to process URLs with a trailing / & defines a canonical link with a trailing /, via an HTTP header. as well as there is a modification of joomla?

Can you point me to that modification?

**Comment by JazParkyn** [comment]
Canonical link is defined for extentions view: \public_html\components\com_jed\views\extension\html.php L74

It isn't defined the same file for categories view: public_html\components\com_jed\views\category\html.php

The post-merge hook runs this: cp $SOURCE_PUBLIC_HTML_DIR/components/com_jed/site-route-patch.php $TARGET_PUBLIC_HTML_DIR/libraries/src/Router/SiteRouter.php

**Comment by zero-24** [comment]
Thanks will take a look into it,

**Comment by zero-24** [comment]
@anibalsanchez can you check this PR whether it fixes the issue?

https://github.com/joomla/joomla-cms/pull/28814

**Comment by anibalsanchez** [comment]
We could create a new system plugin to do the opposite, using the technique, add a trailing slash.

    $router->attachBuildRule(array($this, 'addTrailingSlash'), JRouter::PROCESS_DURING);

**Comment by zero-24** [comment]
A plugin would be far better than a core hack. So :+1: from me maybe JED4 fixes that than better ;-)

**Comment by anibalsanchez** [comment]
Yes, of course. Could you test the idea of a plugin to implement the `addTrailingSlash`?

**Comment by zero-24** [comment]
sure do you have a plugin somewhere already? Installing it on the stage envoirment should do the trick right i can than take a look for sure.?

**Comment by anibalsanchez** [comment]
This would be a new system plugin. If we need to deactivate it, better if it is isolated. The plugin could be of general interest, so it could be published on JED.

Yes, you can test it on stage.

**Comment by zero-24** [comment]
Ah missunderstand you. I thourgt ther would be one already and i should test it ;-)

Will check when i can get to it writing one. Do you have a pointer for the event? Should be something on before route or something right?

**Comment by anibalsanchez** [comment]
On this area of the router, I don't know more than the current workaround that applies the /. So, if the plugin achieves the same effect, then it is OK for me.

If the plugin provides the full support of trailing / for the CMS, then much better. If it could be asking too much for a simple system plugin.

**Comment by zero-24** [comment]
hmm from what i learned in the last days that there is no duplicated content thing happening here. And based on https://github.com/joomla/joomla-cms/pull/28814 it seems to be not that easy to fix it in the CMS itself.

**Comment by anibalsanchez** [comment]
@wilsonge also confirmed that the URL with a trailing slash can be generated with the `attachBuildRule`

https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Router/Router.php#L285

https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Router/Router.php#L407

I'm giving it a try.

**Comment by anibalsanchez** [comment]
I've developed the code to add the trailing slash to the URLs as:

```
			$router->attachBuildRule(array($this, 'addTrailingSlashDetect'), JRouter::PROCESS_BEFORE);
			$router->attachBuildRule(array($this, 'addTrailingSlash'), JRouter::PROCESS_AFTER);
```

Case closed.

**Comment by wilsonge** [comment]
Nice one! Is there any other places we’re hacking core I can look at?

**Comment by anibalsanchez** [comment]
No, this one was the only one where we had to patch.
