### ISSUE TITLE
Log Structure not equal on all places!

### ISSUE THREAD

**Issue by conconnl** [joomla/jed-issues#162]
There are different parts within the system which generate logging for later references.
Only they are scattered around, which doesn't make it easier to analyze the information.

Suggestion: Use the default Joomla location for all logs "/administrator/logs"

* Update all cronjobs
* Update any custom script which has a log definition and doesn't use the default
* Move logs in the other folders related to the crons and custom scripts

**Comment by anibalsanchez** [comment]
@conconnl All cronjobs are failing after the removal of the logs directory.

Please, restore the logs directory and give me the opportunity to review the point (the next weekend). We also need to check what processes are running and generating logs in the current /logs directory.

**Comment by conconnl** [comment]
I didn’t remove anything. 
I just saw this differences and is why I created the issue. Updating the CPANEL cronjob is 2 minutes work.

**Comment by anibalsanchez** [comment]
If you can do it before the next weekend, go ahead. No worries.

**Comment by conconnl** [comment]
I updated the cronjobs in CPANEL.
I see a difference between the Cronjobs, shouldn't those be the same.

Some use:  >> /home/USER/public_html/administrator/logs/NAME.log 2>&1
Some use:  > /home/USER/public_html/administrator/logs/NAME.log 2>&1
Some use:  >/dev/null
Some use:  >/dev/null 2>&1
Some even have # before the complete command.

What should I do with it?

**Comment by anibalsanchez** [comment]
Follow the same convention. 

There are processes that accumulate the log output, processes that only matter the last execution and processes that don't generate useful output. 

Please, move the currently logged files to the new /administrator/logs to maintain the logged information consistency.

**Comment by conconnl** [comment]
My proposal:

Let's use:
/usr/local/bin/php /home/User/Folder/ScriptName.php >> /home/User/public_html/administrator/logs/scriptname-$(date +\%Y\%m).log 2>&1

This will generate a new log file per month and appends the required log information.
It will make sure we don't have super sized files, which can generate other issues.
It also makes it possible to implement cleaning.

**Comment by anibalsanchez** [comment]
Sure, excellent.

**Comment by conconnl** [comment]
All updated...
The ones with # in front, are probably not active.
Can those be deleted?

**Comment by conconnl** [comment]
As agreed, I removed the ones with a # in front.
