### ISSUE TITLE
No modification on pending extensions possible

### ISSUE THREAD

**Issue by RolandSM** [joomla/jed-issues#163]
I have an extension pending in JED and should make some modifications.
But this is not possible, if I click on EDIT I get an empty form.
Also I was sure that I filled the required fields already?

1. Login to JED
2. On Overview you see your pending extension, also with Text and screenshot
3. If you click on the normal opening button, a text is shown that its pending.
4. If you click on EDIT the form opens but is empty.

Expected behavior:
Filled form field where I can edit already done entries.

Video:
https://drive.google.com/open?id=1k9NwGrKqAgjVeACmACnDUWCEei385rEl

Desktop:
 - OS: Kubuntu 19.10
 - Browsers: Chrome & Firefox with latest updates

Smartphone:
 - Device: Samsung S10+
 - OS: Android 10
 - Browser Chrome
 - Version latest

**Comment by anibalsanchez** [comment]
It seems that there was an issue in the extension and it was unpublished. I've reactivated it, however, there's a validation issue.

Please, check the message. When you’ve finished your changes, please open a ticket under “New Listing Support” and ask for it to be rechecked.

**Comment by RolandSM** [comment]
Hello,
same error as before, I cannot edit the pending extension and add the requirements from ticket...
Greets

**Comment by anibalsanchez** [comment]
Hi,

We have checked the extension and it looks like it doesn't have a logo and you have not selected the checkbox about the "Joomla! Update System". These settings are mandatory and you fill them to be able to save it.

**Comment by RolandSM** [comment]
Hello,
seems so but I have no possibility to fix this. The entry is shown in my overview (see initial video)
Also Iam sure that I activated Joomla Update system like all my other extensions.
Think I have to make the complete entry new? But can I take a title which is already existing???
You see my video? You also see my extensions? username Medialekt on JED? You see also last ticket answer on 19.04.2020 10:53:00 containing "But your project page link is broken: http://www.joomlapro.com.br"??? Dont know about this link??? Not from me?

**Comment by RolandSM** [comment]
I refilled all the form fields like all my other extensions. Saved.
Wrote a reply for my ticket to check again.
But if I open again the EDIT Button, the Form is again empty like before and in my video...

**Comment by anibalsanchez** [comment]
Please, try to create a new extension with a new name to confirm if it is a problem related to the extension naming.

**Comment by RolandSM** [comment]
My Extension is named "User Redirect".
There was an entry so I had to make "User-Redirect". This is the one with the issue.

I can make a new entry, but both are away now???

BUT:
There exists no "User Redirect" only a "User Redirect After Login"...
Perhaps in trash??? Or could you see what is the state of "User Redirect"...

The only thing I can do with a new entry without whitespace "UserRedirect"???

**Comment by anibalsanchez** [comment]
We can delete your extensions from your profile, so the names become available again.

If there are existing extensions with the same name (or alias), then the previous extensions have the name, the names (and alias) is reserved and it can't be released.

My guess is that your extension (in some way) is in conflict with a previous extension name (or alias).

Please, try to send a new extension named for instance "RM User Redirect"

**Comment by RolandSM** [comment]
Okay, let me think about...

My extension name is "User Redirect". This was not possible because the JED said that´s already existing.
Then I switched to "User-Redirect" which works... One save... But no further edit...

The Joomla Core replace whitespaces inside Title into a minus (-) as Alias.
So in this example the check was only the Title which was Okay. But after change there should be now two same entries with "user-redirect"...

If so, perhaps I found a bug.

I try to make a new name and push the extension again like you wrote...

**Comment by RolandSM** [comment]
Can you see in database if there are really two existing entries like I wrote?
Can you see also the other one with same name if this exists and also is published? Or the other entry can be deleted when its not published??? I cannot find on extension search, so it seems perhaps that after removing I can use this name 1:1?

**Comment by anibalsanchez** [comment]
We need to confirm that your user can create a new extension, with a new name not used before.

Please, try to create a new extension named for instance "RM User Redirect".

**Comment by RolandSM** [comment]
As you wrote, I added another one with "RM User Redirect".
Here if I click on "Edit" all Form fields are filled like excepted.

So it should be really an issue with the same Alias of 2 extensions here, not my user limitation.

It would be great if you could find the both extensions with same alias "user-redirect". My one could be deleted.
If the other one can also be deleted, perhaps its unpublished since years? Then it would be great ift you can rename my one without RM in front.

Thanks.

And of course I recommend to put thes into buglist of JED.

**Comment by anibalsanchez** [comment]
Great,

There are other extensions named "User Redirect". The name is already reserved by other accounts.

The new name **RM User Redirect**is right. We are going to process it accordingly. Please, send us a new ticket if you want to remove the first submissions from your profile.

The issue is solved. Thanks!
