### ISSUE TITLE
[JED] - search not working correctly / icon and enter

### ISSUE THREAD

**Issue by JazParkyn** [joomla/jed-issues#164]
Type in a search string on the homepage:
- clicking the search button **does** do the search with the string
- pressing enter  **does not** do the search with the string,

Type in a search string in the instant search bar:
- clicking the search icon does nothing
- pressing enter does nothing

**Comment by anibalsanchez** [comment]
Okok, I have the JS code written in an extension. I'll adapt it to the JED widgets.

**Comment by anibalsanchez** [comment]
I've just added search on Enter and linked the Go icon to the /instant-search.

Case closed. One more to go.
