### ISSUE TITLE
Broken links /blog/item/*

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#166]
After the removal of the Zoo Blog, all links associated with the old Blog are broken and users are reporting them.

Please, add a redirection from /blog/item/* to the new Blog link https://volunteers.joomla.org/teams/extensions-directory-team#reports

**Comment by conconnl** [comment]
I don’t see any reports. 
If people click then, they should become visible in the not visible Components menu, because that is broken in the site. 

@JazParkyn as you have changed this part, you probably also know what is changed. 
Can you look at it and tell me if you need any help?

**Comment by anibalsanchez** [comment]
There are blog links that are linked in the documentation, presentations, emails, etc.

For instance: https://extensions.joomla.org/blog/item/fun-in-jed-bug-smashing-and-feature-development/

In particular, this link has been reported in the listing support.

**Comment by conconnl** [comment]
You are saying that we need the same redirect rule as you provided for Magazine site, to redirect */blog/item/* to one and the same location?

**Comment by anibalsanchez** [comment]
No. @JazParkyn didn't migrate each article. So, we only have to redirect all the old blog links to the new content area: https://volunteers.joomla.org/teams/extensions-directory-team#reports

**Comment by JazParkyn** [comment]
Nothing is present in com_redirect because com_jed is interferring. A .htaccess rule is needed to fix this.

**Comment by anibalsanchez** [comment]
I've just added the rule to redirect /blog/* and synched the htaccess from the live site to AdminTools and regenerated everything (htaccess* also commited).

Case closed.
