### ISSUE TITLE
Long indexing by Algolia?

### ISSUE THREAD

**Issue by artur-stepien** [joomla/jed-issues#167]
**Describe the bug**
Search feature on JED site doesn't work correctly. There are extensions missing in the search.

**To Reproduce**
1. Go to [https://extensions.joomla.org/instant-search/?jed_live%5Bquery%5D=BP%20Popup](https://extensions.joomla.org/instant-search/?jed_live%5Bquery%5D=BP%20Popup)
2. Look for "BP Popup" in the results

**Expected behavior**
Well, the extension you're looking for should be listed in here?

**Desktop (please complete the following information):**
 - ALL

**Smartphone (please complete the following information):**
 - ALL

**Additional context**
Last extensions that where missing are BP Slider, BP Prettify. The are now available in the search results. But it took few days for them to show up. Now another extensions published almost 3 hours a go is missing. There is something seriously wrong with Algolia implementation or the service it self doesn't work the way it should. The extensions missing are showing in the "Install from Web" plug-in correctly.

**Comment by anibalsanchez** [comment]
The index is not updated immediately. After your extension has been processed, you have to wait until it processed.

This is a known issue. Please, follow #165 for more information.
