### ISSUE TITLE
Extensions Report form submission error

### ISSUE THREAD

**Issue by joomlaphp** [joomla/jed-issues#17]
Extension reporting error on extensions.joomla.org page

Error page alert after clicking submit button
`0 Could not load form com_jed_extension`

![extensions-page-report-problem](https://user-images.githubusercontent.com/423588/28209108-c06496cc-6899-11e7-8240-4c6a40eece59.png)

Thank you, Ugur

**Comment by anibalsanchez** [comment]
Hi,

I've checked and solved the issue.

*After the update to Joomla 3.7.2, links with no Itemid and no matching menu item are reaching the wrong component and generating the 404 error.*

In this particular case, **the reports have been successfully received**, but com_jed failed to show the final message (redirecting to an article that was not defined in a menu item).

For the record, the solution has been to create a menu item for each one of these system articles.

Thanks for reporting!

**Comment by joomlaphp** [comment]
Thank you!
