### ISSUE TITLE
New Login system - unclear

### ISSUE THREAD

**Issue by bembelimen** [joomla/jed-issues#170]
When I click on "write a review" as a non-logged-in user, I get the following screen:

![grafik](https://user-images.githubusercontent.com/1229869/81055556-36f7c680-8ec9-11ea-97a6-0c002660d7df.png)

Perhaps it makes sense, that the user get at least a link, where he/she can click to log in?

**Comment by anibalsanchez** [comment]
Sure, we can improve the message and add buttons for Login/Register. In fact, I thought that the message wasn't shown anywhere.

**Comment by anibalsanchez** [comment]
Fixed. Case Closed ;-)
![fixed](https://user-images.githubusercontent.com/385780/84565849-894fc100-ad6c-11ea-9309-b3bd21873180.png)
