### ISSUE TITLE
J! Configuration on Reply-To value - CHECK_LINKS_FAIL

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#171]
> It’s seems that the broken link check mails do not follow the J! Configuration at least on the level of Reply-To value. 
> People responding send the mail to the sender and not Reply-To and this only happens with these mails. 

Hi @conconnl , these transactional emails are sent via Sendgrid's Transactional email.

I'll check where it is configured to match the J! Configuration.

**Comment by anibalsanchez** [comment]
I've just tested a couple of different cases and all them have noreply[@]joomla.org.

Which is the specific case?

**Comment by conconnl** [comment]
You have to check reply_to not sender. 
If you receive a mail and press reply. 
If it works then it’s the user their mail client not following the mail RFC

**Comment by anibalsanchez** [comment]
The Sendgrid's Transactional emails have reply_to noreply[@]joomla.org.

The RS Tickers emails have reply_to support[@]extensions.joomla.org.

It looks fine to me.

**Comment by anibalsanchez** [comment]
Since it is working as expected, case closed.
