### ISSUE TITLE
JED Bad Link Notice - False positives

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#172]
Hi,

A month ago, we revamped and re-activated the link checker and we have been processing the bad links on the site.

I've checked your extension links and they seem to be Ok. MansetHaber JT1 https://extensions.joomla.org/extension/mansethaber-jt1/

I'm going to inspect the logs to find the error that the crawler is getting accessing your site.

**Comment by JoomlaTema** [comment]
Thanks Anibal. It is not just for mansethaber extension I have 2 other notices for 2 other extensions.

The Joomla Extensions Directory automated link check noticed that the URL https://extensions.joomla.org/extension/masonry-sliding-gallery/ is unavailable for your extension Masonry Sliding Gallery.
 
Please ensure that the server is available and that the link is correct. We will re-check this link in a few days; if it is still unavailable, your extension will be unpublished.
 
 Update the extension links ASAP.
 
If the extension is already unpublished, please, log in and open a support ticket with this link: Listing / UPDATE - Unpublished extension, broken links fixed.
 
Best Regards,
The JED Team`

Broken Link Notice
 
The Joomla Extensions Directory automated link check noticed that the URL https://extensions.joomla.org/extension/caps-for-ez-realty/ is unavailable for your extension Caps for EZ Realty.
 
Please ensure that the server is available and that the link is correct. We will re-check this link in a few days; if it is still unavailable, your extension will be unpublished.
 
Update the extension links ASAP.
 
If the extension is already unpublished, please, log in and open a support ticket with this link: Listing / UPDATE - Unpublished extension, broken links fixed.
 
Best Regards,
The JED Team

**Comment by anibalsanchez** [comment]
@JoomlaTema To check the basics, do you have a security rule to block crawlers?

**Comment by JoomlaTema** [comment]
No I do not have. By the way did you notice that warning message say  nothing about my demo or download link. It says I couldnt find that URL 

>https://extensions.joomla.org/extension/caps-for-ez-realty

That is not my demo or download URL it is my extension's JED URL.

**Comment by anibalsanchez** [comment]
okok, I'll check the logs.

About the mail content, yes, you are right, the text can be improved to make it clearer. Now, it is confusing because it is not saying what must be checked in the extension.

**Comment by JoomlaTema** [comment]
Okay thanks

**Comment by anibalsanchez** [comment]
I've tested the links with the same command that link checker uses on the server terminal. They are working fine now. So, it looks like it was a temporary issue.

Since the link checker reviews the links several times before unpublishing, it is going to recheck the links.

Please, let me know if you receive new notifications. According to my tests, you shouldn't receive more messages.

**Comment by JoomlaTema** [comment]
Okay Anibal thank you very much for your efforts.

**Comment by anibalsanchez** [comment]
We haven't received new cases. I'm closing the issue by now, if we receive new reports, I'll reopen it.
