### ISSUE TITLE
Error - Security checks determined you may be using an IP masking service

### ISSUE THREAD

**Issue by advanz-lu** [joomla/jed-issues#174]
Hello,
I am tring to write a review for https://extensions.joomla.org/extension/clients-a-communities/user-management/shack-user-switching/

I get:

Error

Security checks determined you may be using an IP masking service, a VPN or a server is actively running on your desktop IP. To continue, you need a different Internet connection.

My IP is 88.207.177.248 (dynamically attributed by my ISP - P&T Luxembourg (PT.lu))

I am not using a VPN or a masking service.

Can you white list me?

Thanks,
-Graham-
PS: If my router reboots I'll be given another IP of course.

**Comment by anibalsanchez** [comment]
Hi,

No, we can't allow the submission from restricted connections.

For more information, please, follow the previous report #85
