### ISSUE TITLE
Marks on the JED Recently Updated page

### ISSUE THREAD

**Issue by ghost** [joomla/jed-issues#176]
Hi,
Available on pages 1 and 2

![extesions](https://user-images.githubusercontent.com/423588/83310414-9c16b180-a214-11ea-9507-46dd5296c879.jpg)
![extesions2](https://user-images.githubusercontent.com/423588/83310426-a6d14680-a214-11ea-98e3-91aac5230d22.jpg)

Thank you,

**Comment by anibalsanchez** [comment]
I tested the issue on Chrome and Firefox, but I've been unable to reproduce it.
