### ISSUE TITLE
Not receiving emails after new reviews

### ISSUE THREAD

**Issue by royroosterz** [joomla/jed-issues#178]
Hi,

It seems no emails are sent from the JED to extension authors when a new review has been written and approved. Can you please validate and fix that it is working again?

Thank you!

Best regards,
Roy

**Comment by anibalsanchez** [comment]
To test a review on one of your extensions, which are your extensions?

**Comment by royroosterz** [comment]
Hi Anibal, 

Thank you for the reply.

My extensions:

- TAGZ: https://extensions.joomla.org/extension/tagz-open-graph/
- AMPZ: https://extensions.joomla.org/extension/ampz-social-sharing/

Best regards,
Roy

**Comment by anibalsanchez** [comment]
I've confirmed an issue in the job that sends the new review emails. I'll be fixing it in the next days.

**Comment by royroosterz** [comment]
Thanks!

**Comment by royroosterz** [comment]
Any luck Anibal?

**Comment by anibalsanchez** [comment]
I've just merged the fix and executed the process. It runs OK and mails are being sent.

Case closed.

**Comment by royroosterz** [comment]
Hi Anibal,

I received a new review for TAGZ, but no email...can you please validate that the issue is really fixed?

Best regards,
Roy

**Comment by anibalsanchez** [comment]
Hi,

The New Review emails are going out. Take into account that the emails are sent once per day. So, if you received the review today, you'll receive the emails tomorrow.

**Comment by royroosterz** [comment]
Ok, I wasn't aware of that. I will be a little more patient 😉

Thanks!

**Comment by royroosterz** [comment]
Just received the email. Thank you Anibal!
