### ISSUE TITLE
Error: Not found - You have already rated this extension

### ISSUE THREAD

**Issue by morphico** [joomla/jed-issues#18]
Hi there,
I gave review for extension (I do not often visit these sites, and when I'm on them I'm mostly looking for something). This review is not moderated yet. And now, when I click "Write a review" I am redirect to mainpage with info "Error: Not found". I think the better will be message "You have already rated this extension"

**Comment by anibalsanchez** [comment]
Hi,

We have consolidated all duplicated issues related to "Error: not found" on reviews here #48 

Closing this ticket as duplicated
