### ISSUE TITLE
'My Extensions' link does not appear despite logging in Extensions Directory

### ISSUE THREAD

**Issue by cecilgupta** [joomla/jed-issues#180]
The issue is with Joomla Extensions Directory website.
I am on this page - https://extensions.joomla.org/
and I have logged in a extension developer.
After logging, there was a menu item 'My Extensions' under 'Browse Extensions' to list the extensions that were developed by me.

The link is missing and does not appear in the menu.

**Comment by conconnl** [comment]
I just logged in with a normal registered test user.
Which has the same Joomla rights as your user and the link is visible to me: https://extensions.joomla.org/browse/my-extensions/
