### ISSUE TITLE
Reset password failed: This user is blocked. If this is an error, please contact an administrator.

### ISSUE THREAD

**Issue by Amin-Idris** [joomla/jed-issues#181]
Notice
Reset password failed: This user is blocked. If this is an error, please contact an administrator.

**Comment by Amin-Idris** [comment]
My login is my email: aafidris@gmail.com 
I don't know why I have been blocked. Please tell me so I do not do again what I did wrong.

**Comment by anibalsanchez** [comment]
Maybe it was caused by the login attempts. I just sent you a pass reset.
