### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by islam-92** [joomla/jed-issues#182]
My website doesn't work after I mak update for my Joomla version and showing this message:
aticgroup.com is currently unable to handle this request. I think this error comes because I doing the update with the wrong version, I have the last log error 
![error log](https://user-images.githubusercontent.com/68500176/87873555-de61a100-c9c2-11ea-9b1c-4399f44b4e4e.PNG)
but I don't know how to correct the errors..
HTTP ERROR 500
![Untitled1](https://user-images.githubusercontent.com/68500176/87873459-04d30c80-c9c2-11ea-9d9b-5b04cdcb2226.jpg)

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
