### ISSUE TITLE
Rename JED hostname and RDNS

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#183]
A question from a user about the JED hostname and RDNS.

We are currently running the Link Checker from the JED server. A user is suggesting an improvement to better identify the server and how it visits the links. 

Now, the JED server is identified with 72-29-124-148.static.directrouter.com and the user agent is "Joomla-JED-LinkChecker". 

It would be better if the JED visits are logged as "jed-link-checker.joomla.org".

What do you think about the DNS? Is it possible? Do we ask for it to Rochen?

CC @JazParkyn @conconnl

**Comment by jeckodevelopment** [comment]
Changing the hostname is something technically possible as well as it's possible to apply a reverse DNS.
Our customers, generally request us to modify the RDNS for their dedicated servers.

**Comment by conconnl** [comment]
@anibalsanchez You should technically be able to send certain headers with your calls, which should also mean you can define a hostheader without changing the server name itself.

Changing the server name to "jed-link-checker.joomla.org" wouldn't be possible, as this would mean that the JED site running on this server would also get this name. If we would choose a general name, we can always ask if they would like to change it. First I would like to see you (possibly with the help of others) to solve it in the tool itself. The moment we replace the server, you have the same problem / discussion.

**Comment by anibalsanchez** [comment]
@conconnl The idea is simply to ask Rochen to change the RDNS to "jed-link-checker.joomla.org".

In this way, people will detect the visit of the process as related to JED and the link checker.

If you are OK, I can ask for the change to Rochen support.

**Comment by conconnl** [comment]
The idea is not simple.
As a server has one RDNS, then you are saying that the whole server running is called like that including for the Extensions website, the stage, development, JED4 etc.
You should at least think of a general name, not a tool specific while the server is running more parts.

@JazParkyn please share your opinion!

**Comment by anibalsanchez** [comment]
You are right. It could be "jed.joomla.org".

**Comment by anibalsanchez** [comment]
Or, it could be "extensions-directory.joomla.org".

**Comment by conconnl** [comment]
Officially the server is already called "joomla-extensions.directrouter.com" and the others for example "joomla-misc.directrouter.com" if we do it, we should standardize and also discuss it within the webmasters (operations).
As all servers should be then made correct.
It can be as simple as "joomla-extensions.directrouter.com" to "joomla-extensions.joomla.org", "joomla-misc.directrouter.com" to "joomla-misc.joomla.org"
As well for any other server we have.

If we do this, I would say:
* Get all current server names DNS and RDNS.
* Define a default naming convention for all server.
* Ask Rochen if they can and want to change it.
* Standardize it on all servers.

Found already:
joomla-extensions.directrouter.com
joomla-misc.directrouter.com
jdev002.directrouter.com
joomla-ads.directrouter.com
joomla-org.directrouter.com
joomla-forum.directrouter.com
joomla-sandbox.directrouter.com

**Comment by anibalsanchez** [comment]
There is always an opportunity to standardize something LOL

**Comment by conconnl** [comment]
So, what do you propose as General Request / question to Rochen?

**Comment by anibalsanchez** [comment]
I would ask Rochen support to rename "72-29-124-148.static.directrouter.com" to "jed.joomla.org"

**Comment by conconnl** [comment]
As mentioned, these things should be followed as a generic action, not JED specific.
I asked what you would do in generic sense, but your suggestion is JED specific.
Created an Operational issue, to follow it as standardization action.
