### ISSUE TITLE
My extensions do not appear in the search results - Algolia issue?

### ISSUE THREAD

**Issue by tassosm** [joomla/jed-issues#184]
I noticed today that my extensions do not show up in the search results. 

If you search for "EngageBox" or "Convert Forms" the respective extension doesn't appear in the 1st place as it should.

Yesterday it was working pretty fine, so I guess something didn't go well with the last update of the Algolia index.

Perhaps, this issue is affecting other listings too.

**Comment by anibalsanchez** [comment]
Confirmed. Yesterday there was an outage that affected several servers of the organization and it happened at the right time to broke the indexing of extensions.

I've just manually executed the process and it is solved now. 

Thanks for reporting.

CC: @conconnl @JazParkyn

**Comment by tassosm** [comment]
Thank you!
