### ISSUE TITLE
JED Review : Not found

### ISSUE THREAD

**Issue by webtoots** [joomla/jed-issues#185]
**ATTENTION: If you have a question or you need to contact the JED Team about an Extension, please, contact us via the JED Ticketing System: https://extensions.joomla.org/profile/** 

**Describe the bug**
I want create review about joomgrabber extension but when i click on the button "Be the first to write a review", i have a eroor message "Not found!"

**To Reproduce**
click on the button "Be the first to write a review"

**Expected behavior**
I thought I had the form to write a review

**Screenshots**
![2020-07-28_13h41_13](https://user-images.githubusercontent.com/7084865/88661154-583b0e00-d0d8-11ea-9774-3d17c000f30f.png)
![2020-07-28_13h41_33](https://user-images.githubusercontent.com/7084865/88661157-58d3a480-d0d8-11ea-88af-c38c953edbe8.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser : Chrome
 - Version: Last

**Comment by anibalsanchez** [comment]
Duplicated #114
