### ISSUE TITLE
Redirect vel.joomla.org to https://extensions.joomla.org/vulnerable-extensions/vulnerable/

### ISSUE THREAD

**Issue by carcam** [joomla/jed-issues#186]
Can we fix the redirect from vel to:

https://extensions.joomla.org/vulnerable-extensions/vulnerable/

I think it makes much more sense.

**Comment by mandville** [comment]
Which redirect from vel ?
There are 3 parts to vel .
Live
Resolved
Abandoned.

**Comment by carcam** [comment]
Sorry I set it only in the title.

I think the most obvious would be:

vel.joomla.org to https://extensions.joomla.org/vulnerable-extensions/vulnerable/

I think that is what most people would use directly.

Right now the redirect sets you at the extensions homepage.

**Comment by mandville** [comment]
A link in the category text to the resolved list would be great now that
you forced users to only see the live vel by default.

**Comment by conconnl** [comment]
> A link in the category text to the resolved list would be great now that you forced users to only see the live vel by default. 

You have access yourself to update the category descriptions, or you can make a proposal in a related issue and ask the team to help.

**Comment by conconnl** [comment]
> I think the most obvious would be: 
> vel.joomla.org to https://extensions.joomla.org/vulnerable-extensions/vulnerable/

@carcam I have updated the htaccess for you.

**Comment by mandville** [comment]
a more logical place would have been https://extensions.joomla.org/vulnerable-extensions/about/

**Comment by mandville** [comment]
> 
> 
> > A link in the category text to the resolved list would be great now that you forced users to only see the live vel by default.
> 
> You have access yourself to update the category descriptions, or you can make a proposal in a related issue and ask the team to help.

i am not in the habit of just altering text in this context without consultation.  As i haven't delved into the areas or examined acl without advisement i wasnt aware .

**Comment by conconnl** [comment]
> https://extensions.joomla.org/vulnerable-extensions/about/

You could also have said that as response on @carcam not after the requested change is done.
You just created extra work, for this one time I changed it again.

As said in the other reply
> You have access yourself to update the category descriptions, or you can make a proposal in a related issue and ask the team to help.

This means, this issue doesn't relate, it's a different subject. (Mixing things is just confusing)
You can involve your own team, by discussing it in the channel, create an issue in GH or whatever you see fit.
