### ISSUE TITLE
Broken Markdown description on extensions

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#187]
The extension markdown description looks OK, but it is rendered as a broken HTML:

Accordeon Menu CK
https://extensions.joomla.org/extension/accordeon-menu-ck/

**Comment by conconnl** [comment]
Other extensions:
<img width="317" alt="image" src="https://user-images.githubusercontent.com/11913918/89470214-8a550b80-d77b-11ea-875f-8ed1ec84b57c.png">


This extension:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/11913918/89470248-a3f65300-d77b-11ea-9e52-c6b579f4b6a0.png">

How the heck can the same view have 2 different HTML outputs.

**Comment by conconnl** [comment]
The reviews get nested from this one.
![image](https://user-images.githubusercontent.com/11913918/89471190-cc7f4c80-d77d-11ea-8879-b2d12e1e78dc.png)

**Comment by conconnl** [comment]
Page 2 is correct again.
https://extensions.joomla.org/extension/structure-a-navigation/menu-systems/accordeon-menu-ck/?com_jed_review_3408_limitstart=10

**Comment by anibalsanchez** [comment]
The issue in the reviews is different from the originally reported issue in the extension markdown description.

**Comment by conconnl** [comment]
The layout looks good now.
The reason is unclear to me, but unpublishing this review helped.
<img width="816" alt="image" src="https://user-images.githubusercontent.com/11913918/89569745-74038a00-d825-11ea-8600-fad7915b6b0e.png">

**Comment by anibalsanchez** [comment]
Great, kudos! @conconnl 

The issue was probably being caused by badly formatted data. It could have been caused by an obscure bug. Let's keep an eye on the topic if other broken extensions are reported. At this point, case closed.
