### ISSUE TITLE
[QUESTION] Will JED be ready to get information from manifest.xml to provide latest version for "Install from Web"

### ISSUE THREAD

**Issue by PhocaCz** [joomla/jed-issues#188]
Hi, I apologize for the question, which may have a touch of ignorance as I don't have any information about JED features.

Will JED be ready to get information from manifest.xml to provide latest version for "Install from Web"? It is planned?

**Comment by anibalsanchez** [comment]
I think that it is a planned feature for JED4. https://github.com/joomla/com_jed4/ You can follow the development, test and report issues on the repository.

Since you are asking about a future feature, better if you open the question in that repository.

CC: @JazParkyn

**Comment by PhocaCz** [comment]
Ok, thank you for the info.
