### ISSUE TITLE
Video does not working in slider

### ISSUE THREAD

**Issue by Sulpher** [joomla/jed-issues#189]
**Describe the bug**

Video does not working.
Please have a look at ths page:
https://extensions.joomla.org/extension/e-commerce/shopping-cart/stripe-for-phoca-cart/
Click on the next slide in slider - there should be video player, but there is a short code instead of it.

{youtube}qyJRXtycYg4|1200|525{/youtube}																	

Pic1: https://i.paste.pics/74d1ef2c5838f0545b75f32e67079a79.png
Pic2: https://i.paste.pics/99811791a9204ce1c0312aab610147a8.png

**Comment by conconnl** [comment]
Thanks for sharing this with use.
The issue is fixed
