### ISSUE TITLE
Unable to write reviews

### ISSUE THREAD

**Issue by Nanjoocom** [joomla/jed-issues#19]
I am able to login and write the whole review but as soon as I click the submit button a message appear asking me to either login or create an account.
Why is this?

**Comment by Nanjoocom** [comment]
I might add that I'm already logged on when receiving this message.

**Comment by anibalsanchez** [comment]
Hi,

We have been unable to reproduce the case. 

We are checking a related issue on #48 . Feel free to join to the task force there.
