### ISSUE TITLE
Can't leave reviews (Security checks determined you may be using an IP masking service, a VPN or a server is actively running on your desktop IP. To continue, you need a different Internet connection.)

### ISSUE THREAD

**Issue by loppanloppis** [joomla/jed-issues#192]
Hi!

When I try to leave a review I get the following error message :+1: 

Security checks determined you may be using an IP masking service, a VPN or a server is actively running on your desktop IP. To continue, you need a different Internet connection.

But I'm not using an IP masking service or VPN.

Any ideas? My username on JED is loppis.

Thanks!

Best regards

Peter

**Comment by Llewellynvdm** [comment]
Have you done a self check? Validating your IP against some of the following:
- https://www.ipqualityscore.com/vpn-ip-address-check
- https://www.ipvanish.com/checkip/
> There are many more tools like these you can just google.

This will help to make sure that your router or other entities on/in your networks are not (without your knowledge) in fact using a VPN, or other IP masking tools.

**Comment by anibalsanchez** [comment]
Hi, 

It is a known issue of the current review system, please, follow this report #85 

Thanks for reporting.
