### ISSUE TITLE
No confirmation email received for registration

### ISSUE THREAD

**Issue by mott31145** [joomla/jed-issues#193]
Trying to register a new account. Entered full name, email address, password. Waited a long time for confirmation email. It never came after 12 hours.
Tried a different name, different email, different password. After 15 minutes, still no email to confirm. Looks like the registration process is broken.

**Comment by anibalsanchez** [comment]
Hi, 

The emails are sent immediately. 

The most probable issue is that your mail server sends the email to the spam box or quarantines the email. Please, check the spam box or ask your email provider how the emails are filtered.

**Comment by anibalsanchez** [comment]
I have created an account and confirmed that it is working fine. Please, check with your email provider where the emails are going.

Case close. Please, re-open if you confirm that emails are not delivered to your email provider.

**Comment by mott31145** [comment]
Hello Anibal,

Thanks for checking this. I have not had any other issues with gmail.com.
But in any case I see that I am now actually logged in (without doing
anything except connecting to the site) under the first user name that I
chose. (The site says that I joined yesterday.) I won't bother any further
with investigating this. Thanks again.

James Mott

**Comment by mott31145** [comment]
Disregard that message. I'm sorry, but I was confused with a different
site. I will look further into the Joomla extension directory site issue
but I've decided that for my needs a log-in is not urgent. If it becomes
important, I will revisit this.
James Mott
