### ISSUE TITLE
Bad link - Redirection via login to Tickets is not working

### ISSUE THREAD

**Issue by Webdongle** [joomla/jed-issues#194]
**ATTENTION: If you have a question or you need to contact the JED Team about an Extension, please, contact us via the JED Ticketing System: https://extensions.joomla.org/profile/** 

**Describe the bug**
Link in acknowledgement email not authorised

**To Reproduce**
In extensions.joomla.org find an extension click to report it and make the report.
When the acknowledgement email arrives in your in box ... click the link to view the report

 
**Expected behavior**
Browser opens on the report

**Actual behaviour**
https://extensions.joomla.org/index.php?option=com_rsticketspro&view=ticket&id=1519:extension-report&Itemid=951 goes to
https://extensions.joomla.org/

**Screenshots**
Clicking the link
![jed 01](https://user-images.githubusercontent.com/1115202/90519676-44774a80-e160-11ea-99f8-d556e5a72a1f.JPG)

Navigate to vulnerable extensions >>> submit a report
![jed 02](https://user-images.githubusercontent.com/1115202/90519897-8ef8c700-e160-11ea-9984-e691b02f71eb.JPG)

Now click the link in the email
![jed 03](https://user-images.githubusercontent.com/1115202/90519980-a89a0e80-e160-11ea-8bac-1cb916c64407.jpg)

Note the 'Support' menu item has more options and that the jed report is listed as Support >>> submit a ticket instead of Support >>> my tickets
![jed 04](https://user-images.githubusercontent.com/1115202/90520985-e9deee00-e161-11ea-8ab5-cbce62387cbc.jpg)

Windows 10, Firefox browser, Thunderbird email client.

**Smartphone (please complete the following information):**

**Additional context**

**Comment by anibalsanchez** [comment]
I think that this issue is similar to #169 Let's see if I can find the time to check it in the weekend.

**Comment by Webdongle** [comment]
Yes very much so.  Also N.B. When you go to https://extensions.joomla.org/ that the 'Support' menu item is showing items for non logged in users.
![jed 05](https://user-images.githubusercontent.com/1115202/90558473-0f84eb00-e194-11ea-9f9b-cbea84864fc4.jpg)

It does look like the base url is not recognising logged in status but when anywhere else on the site it is.

Closing in favour of #169
