### ISSUE TITLE
Unable to remove reviews

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#195]
I'm opening this issue to track an ongoing internal issue that is preventing the removal of reviews in the system.

When spam reviews are detected, we try to remove them and the system doesn't effectively remove them.

**Comment by Llewellynvdm** [comment]
From what I have been able to gather it is controlled in two places, and removing it from the one place does not work, it must be removed from two places. Please let me know in glip if I need to give you more details...

Closing this issue for now, let me know if you think its premature.
