### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by brianteeman** [joomla/jed-issues#199]
21:02 GMT the extensions site is just a blank page

**Comment by brianteeman** [comment]
Correction its just the home page that is blank

**Comment by anibalsanchez** [comment]
Looks fine from here.

**Comment by brianteeman** [comment]
it is now - it was not 14 hours ago

**Comment by anibalsanchez** [comment]
I didn't receive any alert. So, I guess that it was not a global issue.

Case close, then. I'll keep an eye on the alerts.

**Comment by brianteeman** [comment]
I am not sure if you would have got an alert if you are only monitoring for pings. Unless you are monitoring for the present of a marker on the page there would have been no alert

**Comment by anibalsanchez** [comment]
The monitor checks the 200 HTTP Status. So, it would detect a blank page 500 error.

**Comment by brianteeman** [comment]
Sorry if I was not clear.
it was NOT a 500 blank page - it was a 200
