### ISSUE TITLE
[JED] Optimization of PageSpeed-Insights-rules

### ISSUE THREAD

**Issue by chriswagner0815** [joomla/jed-issues#20]
Dear colleagues,
attached information about improving page speed for the JED would help us in improve rankings and user time on site. If you have time and access to work with the JED, please fix these issues.

1. Root template
https://developers.google.com/speed/pagespeed/insights/?hl=de&url=https%3A%2F%2Fextensions.joomla.org%2F 
***************************************************************
To be fixed: 
- put js and css in one file
- add render critical path to the document head with a style - tool for that: https://jonassebastianohlsson.com/criticalpathcssgenerator/ 
--> be advised to include all other templates, like tags, like https://extensions.joomla.org/category/social-web/)
- allow browser caching of files with timestamp for 7 days (css and js)
- allow caching for fonts and images as well in larger time frame
Infos: https://github.com/phanan/htaccess#set-expires-headers 
- external files like:
https://ads.joomla.org/images/fa450c89b90628deb458429e08265dcc.jpg 
https://cdn.joomla.org/rochen/rochen_footer_logo_white.png (5 Minuten)
should also get larger cache time (dont think that the rochen_footer_logo will change every 5 min) and the 
- compression of .js should be enabled (https://github.com/phanan/htaccess#performance; be advised there is not compression for js added)
***************************************************************

2. Extension template (like: https://extensions.joomla.org/extension/extplorer/)
***************************************************************

- Compression and minification from above would help
- Fix issues here: https://developers.google.com/speed/pagespeed/insights/?hl=de&url=https%3A%2F%2Fextensions.joomla.org%2F which are coming from out servers (like optimization of images)
***************************************************************

3. tags (https://developers.google.com/speed/pagespeed/insights/?hl=de&url=https%3A%2F%2Fextensions.joomla.org%2Ftags%2F)
***************************************************************

- fix images and compress them more (can be done with guetzli from Google: https://github.com/google/guetzli)
- add expires for images (should be fixed globally with the fixes from above)

Thank you for any time you can contribute!
Chris Wagner
SEO Team

**Comment by anibalsanchez** [comment]
Great tips! I'll be looking into these recommendations.

**Comment by anibalsanchez** [comment]
We are merging the effort to improve the SEO on the upcoming 2020 Desing update. Please, follow #2020
