### ISSUE TITLE
Can't leave a review

### ISSUE THREAD

**Issue by P1xs0ul** [joomla/jed-issues#200]
Hi. I was trying to leave a review for Event Booking extension, and when I clicked the Write A Review buttons, I got an error message: Error - Not found!

URL: https://extensions.joomla.org/extension/event-booking/

Just letting you know.

**Comment by anibalsanchez** [comment]
Hi,

The issue has been already reported. Please, check it here: https://github.com/joomla/jed-issues/issues/114
