### ISSUE TITLE
virus in extension

### ISSUE THREAD

**Issue by Folamour** [joomla/jed-issues#201]
hi folks, i use jed since age, and its the first time i saw that, hopefully i was on my xampp lab, but i've installed this extension

https://extensions.joomla.org/extension/automatic-intro-image/

and malware byte warned me that she connect to external risky domain,

do what you want, but uninstall the plugin dont remove the request so i'll have to reinstall all my lab,

but that not a problem, thank god its not my live site,

all the best,

f.

**Comment by anibalsanchez** [comment]
Hi,

This support is oriented to support the JED system. 

To report confidential security issues on extensions, please contact the VEL team: https://extensions.joomla.org/vulnerable-extensions/submit-a-report/

Best Regards
