### ISSUE TITLE
Different menu in homepage

### ISSUE THREAD

**Issue by Razzo1987** [joomla/jed-issues#202]
**Describe the bug**
In home page there is a different menu.

**To Reproduce**
1. Login in the portal
2. Go to to homepage and open menu item "Browse Extensions" and "Support"
3. Go to to another page and open menu item "Browse Extensions" and "Support"

**Expected behavior**
Same item in the menu

**Screenshots**
HOMEPAGE:
![immagine](https://user-images.githubusercontent.com/906604/95652726-7cad6080-0af3-11eb-9a3a-b057671ebe10.png)
![immagine](https://user-images.githubusercontent.com/906604/95652584-7965a500-0af2-11eb-8e0c-5499c245a92e.png)

DIFFERENT PAGE
![immagine](https://user-images.githubusercontent.com/906604/95652632-ce092000-0af2-11eb-8f02-83ab91a9bbdc.png)
![immagine](https://user-images.githubusercontent.com/906604/95652614-b467d880-0af2-11eb-8f55-1a612ece455d.png)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 20.04 64bit
 - Browser: Firefox
 - Version: 81.0 (64 bit)

**Comment by anibalsanchez** [comment]
Hi,

The support menu changes when you are logged in.

It looks like your browser kept the menu cached in the Home page.

I'm unable to reproduce the issue. Please, re-open the issue if you can reproduce the issue on different browsers.
