### ISSUE TITLE
Message field in "Submit a Ticket" not working

### ISSUE THREAD

**Issue by RolandSM** [joomla/jed-issues#204]
Hello,

I try to send a ticket, but I cannot write into the Message textarea. Not in Firefox and not in Chrome, also with cleared Cache.
Also the editor is not loading perhaps a wrong editor setting in my account?

**Comment by anibalsanchez** [comment]
It works fine from this side. We didn't receive other reports and people are sending new tickets just fine.

Do you have any browser console error?

**Comment by RolandSM** [comment]
Only a Content Security Policy for Ressource https://assets.hcaptcha.com...

My account is "medialekt".

**Comment by anibalsanchez** [comment]
@conconnl What do you think? Do we need to add https://*.hcaptcha.com to the CSP? There is already a reference to  https://hcaptcha.com but it seems that there is a browser out there blocking hcaptcha.

**Comment by RolandSM** [comment]
I dont think that its a captcha problem...

**Comment by conconnl** [comment]
Check the wiki:
https://github.com/joomla/joomla-websites/wiki

**Comment by RolandSM** [comment]
@zero-24 have already reviewed in a google meet and his idea was a false editor setting?

**Comment by anibalsanchez** [comment]
Just in case, I've reset the frontend settings to the default values.

**Comment by RolandSM** [comment]
Yes, no the message field works, also the editor is loaded... Thanks

**Comment by RolandSM** [comment]
From my side is this ticket solved, but perhaps the real reason have to be found?

**Comment by RolandSM** [comment]
PS. Reporting is not so easy when I cannot open a ticket.
The user have to know about this github repo where he can also gets help...

**Comment by anibalsanchez** [comment]
About your issue, it seems that you configured the user front settings in a previous iteration of the user profile. Those settings can't be changed now.

This repo is linked on the menu:

![jed-issues](https://user-images.githubusercontent.com/385780/97788215-9e13e080-1bb7-11eb-8939-571ffaf01206.png)

**Comment by RolandSM** [comment]
Yes I know about this repo, but perhaps most of the other clients not and I mean, that it could be possible that I am not the only one with this issue...
But thanks so far for me...
