### ISSUE TITLE
Unable to write a review

### ISSUE THREAD

**Issue by toonetcreation** [joomla/jed-issues#206]
Hi,

When I try to write a review on this extension https://extensions.joomla.org/extension/jcart-for-opencart/ I am redirected to JED home page with error message attached.

![2020-12-09_20-25-58](https://user-images.githubusercontent.com/20813754/101677559-011d5080-3a5d-11eb-982e-19746dc773ef.jpg)

Thanks

**Comment by Llewellynvdm** [comment]
Please have another go at it... it should be resolved now. Not that we where able to duplicate your error, but we have updated the JED with a few bug fixes over the last few months. So we would like to know if your still having this issue.

Apology for not reaching out to you sooner...

**Comment by toonetcreation** [comment]
sorry but does not work.
I have reseted my password and after login process I get this : http://prntscr.com/10zrrix

**Comment by Llewellynvdm** [comment]
What area are you trying to view, from what URL does it take you here, or what action.

**Comment by Llewellynvdm** [comment]
Okay this does no make sense that once you login you get this... will get back to you. But for what its worth please clear your browser cache and try again.

**Comment by toonetcreation** [comment]
ok works fine, was cache issue.
thanks again
