### ISSUE TITLE
JED Ticket System Message field blocked

### ISSUE THREAD

**Issue by marcorensch** [joomla/jed-issues#208]
When you have to open a ticket you need to create a ticket here: 
https://extensions.joomla.org/support/support-tickets/

The form cannot be sent because of the required Message field that is not working.
<img width="901" alt="Bildschirmfoto 2021-01-09 um 10 33 39" src="https://user-images.githubusercontent.com/11912135/104088306-27096100-5266-11eb-8325-1a81a9a96b89.png">

I don't know if an editor should be loaded or not - the fact is that you can't enter anything in the message field.

Tested on Mac with Chrome & Safari (latest versions)

**Comment by conconnl** [comment]
Just tested on Mac with Chrome & Safari, with a normal registered user.
I see the editor and I can use it.

Please check the browser console, it should show errors if it's related to the site.
If there are any please share, because all browsers I have tested, don't show any errors and the editor works.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/11913918/104089296-25dc3200-526e-11eb-85e8-317c5df1e470.png">

**Comment by marcorensch** [comment]
ahm.. what...
i've tested it on chrome & safari (mac) aswell as on EDGE and Firefox on another computer, and yes there is a JS error:

Refused to connect to 'https://assets.hcaptcha.com/captcha/v1/d1dd7d8/static/i18n/de.json' because it violates the following Content Security Policy directive: "connect-src 'self' https://*.joomla.org https://*.pingdom.net https://*.google-analytics.com https://*.googlesyndication.com https://*.doubleclick.net https://*.algolia.net https://*.algolianet.com".

now a test on a third machine:
EDGE (Version 87.0.664.66 & 87.0.664.75): 
<img width="1680" alt="Bildschirmfoto 2021-01-09 um 11 52 38" src="https://user-images.githubusercontent.com/11912135/104089707-3215be80-5271-11eb-8eb2-728fd57a3c05.png">
FF 81.0.1 & 84.0.2:
<img width="1286" alt="Bildschirmfoto 2021-01-09 um 11 55 06" src="https://user-images.githubusercontent.com/11912135/104089735-8c168400-5271-11eb-85f5-3c6d61202c7b.png">

**Comment by conconnl** [comment]
It seems hcaptcha extended the required CSP rules.
I added this one, so this error should be gone now.

**Comment by marcorensch** [comment]
Nice but unfortunately this was not the issue... the error in console is gone but the site still does not load the editor as on your screenshot... Could it be that my account / profile has a problem?

**Comment by conconnl** [comment]
@anibalsanchez could you look at this as someone who knows the coding of the site?

**Comment by marcorensch** [comment]
@conconnl 
**UPDATE**: its indeed a problem with my Account (Proximate) - i've created a testaccount now (proxi) and there the editor is shown - so what happened to my account **(settings)**? unfortunately i did not find any option to "chose an editor" in profile page which would probably solve the problem.

**Comment by conconnl** [comment]
I see what you mean.
You mentioned account is on JCE, but that one isn't configured to be used for Registered people.
The default is TinyMCE, somewhere in the long history of actions on the website the editor has been changed, but people their profile has been reset.

I switched your account to default editor.
@anibalsanchez & @JazParkyn can you please put all registered accounts to TinyMCE so it's fixed for any other user existing on the website?

**Comment by marcorensch** [comment]
Solved now

**Comment by andrewmichaelwinkler** [comment]
I have the same problem on Firefox for Windows 10. The message text field is not editable.

**Comment by JazParkyn** [comment]
Fix applied
