### ISSUE TITLE
403 Access Denied at extensions.joomla.org 

### ISSUE THREAD

**Issue by toivo** [joomla/jed-issues#209]
Reported 10 minutes ago in https://forum.joomla.org/viewtopic.php?f=262&t=983991 and confirmed.

**Comment by conconnl** [comment]
It’s known, we have a monitoring system. 
publicly available, with notifications to different members and channels. 
https://status.joomla.org/

**Comment by toivo** [comment]
Thanks - the existence of such a monitoring system is of course good but that has not been widely publicised.

**Comment by conconnl** [comment]
It's known at the Team Leaders of the different teams maintaining the properties, who could share it with their team members. It has been shared with SMT, to put it on Social Media if they think it's usable for the public.

**Comment by toivo** [comment]
Ok, understood.

**Comment by conconnl** [comment]
It's now fixed.
It was an error on server access rights, created by a mistake at the hosting supplier
