### ISSUE TITLE
Issue in the text encoding/ decoding for the extension Return to Top on JED

### ISSUE THREAD

**Issue by adtj93** [joomla/jed-issues#210]
Issue in the text encoding/ decoding for the extension [Return to Top on JED](https://extensions.joomla.org/extension/return-to-top/). Ampersand symbols are still displayed while editing or adding the full description for this listing on JED.

**Comment by Llewellynvdm** [comment]
Please have another go at it... it should be resolved now. Not that we where able to duplicate your error, but we have updated the JED with a few bug fixes over the last few months. So we would like to know if your still having this issue.

Apology for not reaching out to you sooner...
