### ISSUE TITLE
[JED] Share link on Facebook and advertisement is the preview image

### ISSUE THREAD

**Issue by hvdmeer** [joomla/jed-issues#211]
Somehow an advertisement on the JED is shown in the preview image when the link (extensions.joomla.org) is shared on Facebook.
This probably won't happen all the time but is it possible to exclude ad-images for being shown in Social Media preview images?

Example:
![link-JED-FB-shows-ad](https://user-images.githubusercontent.com/7062995/104605470-d7200500-567e-11eb-9f96-ae8382a5b373.png)

**Comment by JazParkyn** [comment]
I suggest that we ask the marketing team for some images that can be used in OG data tags to resolve this? @anibalsanchez what are your thoughts?

**Comment by conconnl** [comment]
@hvdmeer 
Did you had the problem before the Scala advertisement was added?

**Comment by JazParkyn** [comment]
It would have chosen the first available image on the page, so that would depend based on the URL.

**Comment by conconnl** [comment]
It seems the JED is just broken on this level 😢 
Default template setting on JED, which on other sites are visible in the source
<img width="463" alt="image" src="https://user-images.githubusercontent.com/11913918/104611521-8233bd00-5685-11eb-879b-007dd38da333.png">

**Comment by anibalsanchez** [comment]
1. The jorg template has a default og:image tag.

2. JED3 (com_jed) defines an og:image tag for each extension. For instance, **Weblinks**:

```html
<meta name="og:image" content="https://extensions.joomla.org/cache/fab_image/logo/54dd19afdb25f.png" />
```

This is what works fine. 

However ... if Facebook scrapper doesn't find an og:image tag, it starts parsing the page looking for an image. So, that's when it could find any image on the page and the post can render an ad.

We should check the original URL that didn't have an og:image and in this way find out why Facebook scrapper became creative.

**Comment by JazParkyn** [comment]
@anibalsanchez Wilco has found the issue in the template and I will submit a commit to fix it later today

**Comment by hvdmeer** [comment]
Late to the party. I don't see an og:image set on the landing page. 
@conconnl Don't know if it happens more often. I'm hardly ever sharing the extensions.joomla.org landing page.
But good to see the problem is found and a fix will be deployed.

**Comment by conconnl** [comment]
@JazParkyn & @anibalsanchez 
Is this fixed?

**Comment by anibalsanchez** [comment]
No. You can check the issue on Facebook Sharing Debugger: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fextensions.joomla.org%2F

![fbd](https://user-images.githubusercontent.com/385780/105578433-84ca9c80-5d80-11eb-97c9-55a0eb05d3d3.png)

**Comment by JazParkyn** [comment]
@anibalsanchez These changes will be pushed when you've identified the issue in the git script. 

For now, I have manually applied this change, but the other changes in my commit can't be applied in this way. FB cache cleared.

![image](https://user-images.githubusercontent.com/6943227/105579135-79757200-5d7c-11eb-8481-82bbd60b22db.png)
