### ISSUE TITLE
Backend of Website Clicking to Frontend

### ISSUE THREAD

**Issue by GarrettLloyd** [joomla/jed-issues#212]
When I am in the backend of my website using joomla, working to add an item anything I click forces me to leave the backend and directs me to the front end

This video below is an example

https://user-images.githubusercontent.com/77693479/105079100-f216be80-5a5c-11eb-8ef4-a1ba161a0a7a.MOV

**Comment by anibalsanchez** [comment]
Hi,

This is the JED issues tracking. So, we follow the issues of https://extensions.joomla.org/.

If you have an issue on your Joomla site, you can look for help on Joomla Forum: https://forum.joomla.org/

Best Regards
