### ISSUE TITLE
I can't post any tickets because I can't enter any text into the message text field

### ISSUE THREAD

**Issue by andrewmichaelwinkler** [joomla/jed-issues#213]
I'm trying to contact support about getting my extension InfinitySubmit re-listed after a broken link issue. However, I can't submit a ticket because I cannot enter any text into the required message text field.

**Comment by conconnl** [comment]
Please try again, I updated your editor settings.

**Comment by conconnl** [comment]
@anibalsanchez @Llewellynvdm @JazParkyn 
This is the same issue as https://github.com/joomla/jed-issues/issues/208 
Can you please take the action and reset the editor of the users to Default in their profile?

**Comment by andrewmichaelwinkler** [comment]
Now I can no longer log into Joomla and get the following error message:

You are not authorised to view this resource.

**Comment by andrewmichaelwinkler** [comment]
When I tried, I found that I was logged out of the Joomla site and when I tried to log back in I got an error saying:

You are not authorised to view this resource.

**Comment by conconnl** [comment]
According to systems you have logged in, 8 hours ago.
It isn't clear for me at the moment, where you clicked or what you did to get the message.
The login page is: https://extensions.joomla.org/users-login-form/

The only change done is from the not allowed JCE editor to the Joomla default TinyMCE editor, in your profile.

**Comment by JazParkyn** [comment]
Database updated to tinymce as default for users who did have jce as default.
