### ISSUE TITLE
extensions.joomla.org - you need a different Internet connection

### ISSUE THREAD

**Issue by Goalfair** [joomla/jed-issues#214]
"extensions.joomla.org" says when visiting "User Profile": Error. Security checks determined you may be using an IP masking service, a VPN or a server is actively running on your desktop IP. To continue, you need a different Internet connection.

These "security checks" seem to be misguided since I am not using any of these.

**Comment by conconnl** [comment]
You are correct, therefore see:
See: https://github.com/joomla/jed-issues/issues/85#issuecomment-704521240
