### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by bazza14** [joomla/jed-issues#216]
I have my login credentials saved in Firefox but your site says they are wrong. So I first tried recovering my user id. I clicked the link, entered my email address, got a "we've sent you an email" message but no such email arrived so I repeated the exercise with the same outcome.

**Comment by Llewellynvdm** [comment]
Please let us know if this issue still persist as it seems to be resolved on our side.

**Comment by bazza14** [comment]
No it's worse now. It now tells me the email address is invalid. This isn't important enough to warrant spending any more time on. I'll just register again.

**Comment by Llewellynvdm** [comment]
It could be that the user was removed. So yes creating a new account and let us know if you still unable to finish the registration. Will help if we knew the email and username to more effectively give you support.

These details you can email to jed-support@community.joomla.org and just let me know here that you have done so.
