### ISSUE TITLE
Joomla Extensions Website Loading Issue

### ISSUE THREAD

**Issue by aboarken** [joomla/jed-issues#217]
Joomla extensions website is not loading correctly and it giving error 500 Internal Server Error.

![loading issue](https://user-images.githubusercontent.com/18500882/108500992-ab1d2280-72c1-11eb-9e55-aaa01b002025.png)

![Error 500](https://user-images.githubusercontent.com/18500882/108501116-dacc2a80-72c1-11eb-8d38-34397d33daea.png)

**Comment by anibalsanchez** [comment]
It works fine from here. Maybe it was a temporary glitch somewhere.

**Comment by aboarken** [comment]
@anibalsanchez do you think its a CDN caching issue? Its still not loading correctly from my side.

**Comment by aboarken** [comment]
@anibalsanchez , now its working. Thank you.

**Comment by Llewellynvdm** [comment]
Happy to hear its resolved.
