### ISSUE TITLE
Wrong charset for Cyrillic symbols

### ISSUE THREAD

**Issue by Sulpher** [joomla/jed-issues#218]
There is a wrong charset for the field "I used it for" - no Cyrillic symbols are available there. I suppose there is Latin-Swedish charset or something like that instead of UTF-8.

have a look:
<img width="826" alt="Снимок экрана 2021-02-23 в 21 55 52" src="https://user-images.githubusercontent.com/3432048/108893625-5ca1b800-7622-11eb-8a58-8d0b7ff974a3.png">

https://extensions.joomla.org/extension/google-structured-data/

I met this issue a lot of times. Please fix it.

**Comment by Llewellynvdm** [comment]
@Sulpher far as I can tell we are only using [utf8mb4_unicode_ci](https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L27) in all our database tables as the Joomla standard. Further more the JED is a English website, and we do not currently target a multilingual implementation.

**Comment by Llewellynvdm** [comment]
@conconnl  just mentioned to me that it could be fabric that messes things up. We are working on a JED 4 and hope we will have a better outcome there since it will be a native Joomla extension.

**Comment by Sulpher** [comment]
> @Sulpher far as I can tell we are only using [utf8mb4_unicode_ci](https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L27) in all our database tables as the Joomla standard. Further more the JED is a English website, and we do not currently target a multilingual implementation.

JED is not just English since there is a dropdown list to select a language of the reviews, thus this issue should be fixed or the dropdown list should be removed to avoid misunderstanding.
