### ISSUE TITLE
[improvement] Move My Extensions menu item to My profile

### ISSUE THREAD

**Issue by Sulpher** [joomla/jed-issues#219]
It is logically to move My Extensions menu item to My Profile since it is related 1st level menu:

<img width="1243" alt="Снимок экрана 2021-02-24 в 12 46 51" src="https://user-images.githubusercontent.com/3432048/108982451-decfc200-769e-11eb-94c9-eadcccf50923.png">

**Comment by anibalsanchez** [comment]
Hi,

I'm not calling the shots anymore ;-) Let's ask to @Llewellynvdm , the current JED team leader.

**Comment by Sulpher** [comment]
> I'm not calling the shots anymore ;-) Let's ask to @Llewellynvdm , the current JED team leader.

this issue was automatically assigned to you after I posted it :-)

**Comment by anibalsanchez** [comment]
Ahh, one more thing to update. ;-)

**Comment by Llewellynvdm** [comment]
Thanks for this input, and I think it is a great idea, I will share it with the JED team. Can't make any promises... the current layout/design was done before my time. But I am sure there was a good reason for it, and yet in JED4 we will re-valuate all these with the help of a UX experts like yourself. Would you be interested to contribute at that time?

This means that for now I/we are focusing all out energy towards getting ready for JED4, besides the normal JED tasks.

**Comment by Sulpher** [comment]
> Thanks for this input, and I think it is a great idea, I will share it with the JED team. Can't make any promises... the current layout/design was done before my time. But I am sure there was a good reason for it, and yet in JED4 we will re-valuate all these with the help of a UX experts like yourself. Would you be interested to contribute at that time?
> 
> This means that for now I/we are focusing all out energy towards getting ready for JED4, besides the normal JED tasks.

Thanks for offering, but I am not into volunteering.
Btw, there is a great UI/UX conception for the JED which was suggested a few years ago:
https://ekerlabs.com/blog/the-new-joomla-extensions-directory-concept

I hope to see something similar :-)
