### ISSUE TITLE
Install from web missing extensions

### ISSUE THREAD

**Issue by brianteeman** [joomla/jed-issues#221]
I don't know if this is a JED team issue, a Install from Web plugin issue or what but The install from web plugin is only displaying extensions that are marked as compatible with joomla 4 alpha. It is not including extensions that are marked as compatible with Joomla 4 Beta

To make it even harder to find extensions you will also see that extension on JED are shown with a 4Alpha tag on search views and then (where appropriate) a 4beta tag on the individual item view.

So I suspect that there are multiple bugs here

https://github.com/joomla/joomla-cms/issues/32705

**Comment by anibalsanchez** [comment]
IFW is maintained by the Production Team.

There is a server somewhere that reads the JED database and updates the CMS plugin with information. I guess that this proxy service is not updated with the latest version tags.

**Comment by brianteeman** [comment]
> To make it even harder to find extensions you will also see that extension on JED are shown with a 4Alpha tag on search views and then (where appropriate) a 4beta tag on the individual item view.

This part is on jed not ifw

**Comment by anibalhsanchez** [comment]
All the J4 tags are going to be removed/migrated when J4 is finally released.

**Comment by brianteeman** [comment]
Maybe so but right now it is broken and not working as designed

**Comment by Llewellynvdm** [comment]
The JED as part of its objectives are planning to rebuild this area, to make use of the new API functions in Joomla4 so there are plans in the works for Joomla 4 (JED4). As for Joomla 3 and the current Web-Install it will be replaced once JED 4 is out. This will still take a while as the volunteers involved are putting all their focus into getting Joomla 4 out the door.

But thank you for the heads-up it is duly noted and will be looked at.

**Comment by Llewellynvdm** [comment]
Let's continue the conversation here https://github.com/joomla/install-from-web-server/issues/58 as the JED4 application will resolve the JED side of the problem, but at the moment the [install from web server](https://github.com/joomla/install-from-web-server) is the place to try and address the current TAG issue mentioned.

**Comment by brianteeman** [comment]
Please do not close this while there is an outstanding issue regarding the JED
