### ISSUE TITLE
User account blocked

### ISSUE THREAD

**Issue by forrestkirby** [joomla/jed-issues#222]
**Describe the bug**

The extensions.joomla.org account for the user name `forrestkirby` seems to be disabled or deactivated. I tried to issue a password reset, but I get the notification “Reset password failed: This user is blocked. If this is an error, please contact an administrator.”

**To Reproduce**

1. I navigated to https://extensions.joomla.org/password-reset/
2. Then I entered my e-mail address
3. I filled out the Captcha and hit the *Submit* button
4. The notification “Reset password failed: This user is blocked. If this is an error, please contact an administrator.” appears.

**Expected behavior**

I would expect to get an e-mail with a link to reset the password for the account and a success notification.

**Screenshots**

![](http://snap.ashampoo.com/uploads/2021-04-03/YJNhBnyj2NjyW00g7TS2VbuN1bgvuqIN1wv5EOga5PYupY1nnojDP7RK0yAuJJCf.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 89.0.4389.114 (Official Build) (64-Bit)

**Additional Information**
I checked the spam folder and verified that the e-mail address is correct as was suggested in the thread [Enable/activate account at extensions.joomla.org](https://forum.joomla.org/viewtopic.php?f=262&t=985741&p=3628194#p3628189) in the Joomla! forum [extensions.joomla.org - Feedback/Information](https://forum.joomla.org/viewforum.php?f=262).

**Comment by anibalsanchez** [comment]
@JazParkyn Here we have another case of an inactive account. Do I remove it manually from the system?

**Comment by forrestkirby** [comment]
Hi anibalsanchez, so are you an administrator on the JED and could you please enable or activate or delete my account? Or is this not the right place to ask this question? If so, could you please tell me how I could reach out to a JED admin?

Thank you

**Comment by anibalsanchez** [comment]
Sorry for the delay, I've just deleted the user. Please, register again.

**Comment by forrestkirby** [comment]
Thank you very much!
