### ISSUE TITLE
Hard to recognize Free vs paid extensions

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/jed-issues#228]
I think free extensions were once green but they are orange now like the others:
That makes it hard to recognize them
![grafik](https://user-images.githubusercontent.com/828371/128002488-b65a67df-abd9-4017-8b33-88fb708b6c9e.png)

**Comment by Llewellynvdm** [comment]
I am not sure why that was changed.

Will ask the team if they changed that for a reason or by accident.

**Comment by anibalsanchez** [comment]
On the general site, the free extension tag is a `label label-success` and the paid extension tag is a `label label-warning`. Please, check it here: https://extensions.joomla.org/browse/top-rated/

However, in the search results they are not using the same style: https://extensions.joomla.org/instant-search/?jed_live%5Bquery%5D=youtube

It looks like a bug in the search results rendering.

**Comment by Llewellynvdm** [comment]
Only security updates excepted at this point on JED 3, or major bugs...

Since we are working on [JED4](https://github.com/joomla/com_jed4) where you will be able to also contribute directly. We need your help there... so please start looking over the new JED4 and make our contributions there.
