### ISSUE TITLE
Wrong logo size and video

### ISSUE THREAD

**Issue by Sulpher** [joomla/jed-issues#23]
I have uploaded the logo with required size 960x420 pixels and the bottom part is hidden on the product page, but the thumbnail is okay. Please see enclosed screenshot.

By the way, I have a video on this page too. If to remove the video, the logo displays with another size.

Please check it out locally: it seems there is an issue. Add a logo without video and then ads the video and see what will happen.

![screen shot 2017-10-20 at 08 20 51](https://user-images.githubusercontent.com/3432048/31806346-bb198092-b56f-11e7-9a32-cc0037a3febc.png)
![screen shot 2017-10-20 at 08 21 12](https://user-images.githubusercontent.com/3432048/31806347-bbd2d54c-b56f-11e7-9aaf-70a792c5fa3e.png)

**Comment by anibalsanchez** [comment]
We have more detailed information about the case here #50

**Comment by anibalsanchez** [comment]
Solved!
