### ISSUE TITLE
JED Ticket System broken

### ISSUE THREAD

**Issue by sanus70** [joomla/jed-issues#230]
Unable to create a new ticket, caus the page only shows an error.

![jticket](https://user-images.githubusercontent.com/43116794/130259505-fe0cb2a6-05bb-4de4-8ae6-e9957a9e54cb.png)

**Comment by Llewellynvdm** [comment]
@sanus70 thank you for reporting this.

We are looking into it, and will let you know soon as we have this resolved.

**Comment by Llewellynvdm** [comment]
Okay @sanus70 the ticket system is up again, thanks again for your help in reporting the issue. Let us know if you have any further issues.
