### ISSUE TITLE
Make Joomla 3 and Joomla 4 comptability clearer

### ISSUE THREAD

**Issue by stevejburge** [joomla/jed-issues#232]
My first reaction to this was "oh no, another one of those reviewers"

But honestly, this could be an area we need to improve the JED's usability? That "J3" box is tiny and unclearr
![Screen Shot 2021-10-09 at 9 10 08 AM](https://user-images.githubusercontent.com/3868028/136659292-d4ddca0a-ee89-4759-9454-d19e2204047f.png)

**Comment by anibalsanchez** [comment]
Hi Steve, the team is managed by @Llewellynvdm .

The new JED4 is on horizon. So, this issue is probably a won't fix.

**Comment by Llewellynvdm** [comment]
We have volunteers behind a [ticket system](https://extensions.joomla.org/support/support-tickets?subject=Extension%20Report&department_id=2&extension-id=11974&extension-name=Google%20Structured%20Data) where these issue must be reported. The don't follow this repositories issues, and will not respond here.

I agree this review is incorrect, and must be reported either by the extension developer or any other person to the JED team in the JED with the ticket system that is in place there.

As to improvement to the JED there is a team, and repository where that kind of contribution can be made, simple open this [repo](https://github.com/joomla/com_jed4), and [open an issue](https://github.com/joomla/com_jed4/issues) and start your contribution :+1: 

> Then lastly and most importantly, not reading and not paying attention are never solved with more stuff to read.
