### ISSUE TITLE
Cannot log in my account

### ISSUE THREAD

**Issue by junbernardo** [joomla/jed-issues#233]
Dear Sir/Maam:

I am trying to log in my account to leave a review for an extension. But it is asking for a secret key that I cannot recall.

I know my username and password are correct. I used the forgot username and password link to verify that. But none gave me the key.

What should I do?

Thank you so much.

Regards.

**Comment by Llewellynvdm** [comment]
Hi, you please give me your username? so I can take a look? you can email it to me at llewellyn[dot]van-der-merwe[at]community[dot]joomla[dot]org
