### ISSUE TITLE
Cannot Login to Joomla Extension Directory Site

### ISSUE THREAD

**Issue by Estacey19** [joomla/jed-issues#234]
I'm brought here by trying to 'report a problem' with the JED.   I have an account there.. verified, etc.. etc..   However, when I try to log in it keeps telling me My password and/or username is wrong.   the Login is 'asking' me for a 'SECRET KEY' or some such thing.. which I have never had to enter before..   and have no idea how to get past that.

**Comment by Llewellynvdm** [comment]
This sounds weird, we can't just go and remove those security measures. For the safety and sanity of all we will need an email request from the same email address as the account, to whom we will forward the needed steps to resolve the issue.

**Comment by Llewellynvdm** [comment]
Hi @Estacey19 I have replied to your email, and I am sure we can now get this resolved... in the email conversation.

**Comment by Estacey19** [comment]
All is well now.. thank you for your help!
Edward
