### ISSUE TITLE
[3.x][4.x] Install from Web/JED issue

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/jed-issues#237]
### Steps to reproduce the issue
Open the install from web both on Joomla 3 and Joomla 4

### Expected result
All extensions are loaded and displayed correctly

### Actual result
Images are randomly not loaded with a 404 code (see screenshots)

### Additional comments
Is someone going to fix this issue that happens since several days? Nobody seems to take care of this issue. What a shame.
![jed_errors2](https://user-images.githubusercontent.com/17835460/145075062-f1e43b40-c390-477c-9b49-a668c511e957.JPG)
![jed_errors](https://user-images.githubusercontent.com/17835460/145075068-48ca2d89-47a5-403e-a6a8-0aa24861d0b2.JPG)

**Comment by Llewellynvdm** [comment]
Hi @joeforjoomla we do care :+1: and we are always grateful if someone catch something we missed.

I will take a look and get back to you!

**Comment by zero-24** [comment]
As requested by @Llewellynvdm this has beeen moved to the jed-issues repo.

**Comment by joeforjoomla** [comment]
Many thanks @Llewellynvdm ! i hope this will be fixed soon.

**Comment by joeforjoomla** [comment]
@Llewellynvdm is there any update on this issue? We still have images of our extensions not visible. Thanks

**Comment by Llewellynvdm** [comment]
I have been fighting [other fires](https://github.com/joomla/jed-issues/issues/236#issuecomment-990338514) on the JED today (took my whole afternoon, while I had other pressing matters around deadlines for my own clients).

Never the less I have been asking around in the various teams for advice around this issue. There is not yet any clear path to resoling the issue, but we are working on it.

Wondering if you would like to join the JED team? we can always do with more volunteers ;)

**Comment by joeforjoomla** [comment]
@Llewellynvdm joining the JED team to contribute would be nice :)
I hope the issue will be sorted out soon.

**Comment by Llewellynvdm** [comment]
@conconnl fixed the DNS issues, and it seems like this issue is now resolved. Thanks @conconnl !

@joeforjoomla about joining the JED, what area would you like to contribute? There are several areas:

- Reviews 
- Extension Listing
- Tickets
- Forum
- Maintenance
- - JED Extensions
- - JED3 Website
- Building JED-4

If you would seriously like to continue this conversation, please email me at llewellyn.van-der-merwe [a t ] community.joomla.org
