### ISSUE TITLE
Can't log in to Joomla! extensions directory

### ISSUE THREAD

**Issue by Ben9062** [joomla/jed-issues#241]
Created an account ? to https://extensions.joomla.org. 
It appears my email is locked, the site had asked for a secret key which I never received and now I want to post a review of RentaloPlus - an excellent component.
Help !!

**Comment by Llewellynvdm** [comment]
This sounds weird, we can't just go and remove those security measures. For the safety and sanity of all we will need an email request from the same email address as the account on the JED, to whom we will forward the needed steps to resolve the issue.

**Comment by Ben9062** [comment]
Thanks for the reply, I managed eventually to register and then create a review which was the underlying issue with another account.  

All good now

Regards

Ben

**Comment by Llewellynvdm** [comment]
Ben you should refrain opening multiple accounts as this is against the JED terms of service.

Good that you got this resolved, until next time take care!
