### ISSUE TITLE
contact mechanism LACKING

### ISSUE THREAD

**Issue by ergotone** [joomla/jed-issues#259]
You know, I go to  the JED to purchase new extensions... I search, eventually find some. 

...and EVERY TIME, I get nowhere trying to contact the developers!
The Company name links to a USELESS listing on your site. Then I have to frigging GOOGLE to try and find the actual developer's web site, so I can get USEFUL information, like the **price**, and various options .
How about fixing that???

**Comment by dryabov** [comment]
Each extension developer has the option of providing links to the extension's demo page, documentation page and support page. These links are displayed in the right-hand column below the extension's download button.

Which extension are you talking about now?
