### ISSUE TITLE
jVArcade exists in database

### ISSUE THREAD

**Issue by jVArcade** [joomla/jed-issues#26]
I have taken over the development of this component from JVitals as they seem to have just disappeared. The links to jVArcade are closed due to broken links. I am unable to submit it again with my information and would like to keep the name as that's what everybody already knows it as.

Can jVArcade be removed from the database so I can start it up again ?

**Comment by anibalsanchez** [comment]
Hi,

This ticket system is for developers of extensions listed on JED - we are unable to provide support for your issue here. For JED support questions, you can go to https://extensions.joomla.org/support/support-tickets/.

Kind Regards
