### ISSUE TITLE
Search in JED returns no resuts

### ISSUE THREAD

**Issue by tassosm** [joomla/jed-issues#260]
The instant search in JED seems broken. It does not return any results in any keyword.

![image](https://user-images.githubusercontent.com/6807469/231664529-7c4d36c2-ec4e-426f-8641-40f6e40f0609.png)

**Comment by woluweb** [comment]
Yup. I also shared the information yesterday evening on Mattermost but without any reaction so far: 
https://joomlacommunity.cloud.mattermost.com/main/pl/buqurgnapi8mjerr9ywwkbszeh

**Comment by PhocaCz** [comment]
Hi, I get same or similar problems. The search finds nothing or completely different items:

Searching "Phoca Cart" - it finds all different extensions which have string "cart" in description but it should just find "Phoca Cart" - component or Phoca Cart modules and plugins:

![img](https://i.imgur.com/Bb5G1YN.png)

Paradoxically, it will display all possible results, just not the ones that really relate to the search string "Phoca Cart"

**Comment by tassosm** [comment]
I confirm the problem mentioned by @PhocaCz. The same issue affects my extensions too. I am disappointed seeing the JED constantly broken.

**Comment by mfleeson** [comment]
We have spent most of today debugging the algolia update script and found an extension that had UTF8 text in its definition was causing the update to crash. This has now been fixed and tested.
