### ISSUE TITLE
extension search not working properly

### ISSUE THREAD

**Issue by ryanminnig** [joomla/jed-issues#261]
When performing a search, for instance, for the term "recipe", the results returned do not show my component (Simple Recipe), nor do they show "JoomRecipe", a paid component, nor many of the other items in the "Food and Beverage" sub-category.
The results do show "Gary's Cookbook", a component that hasn't been updated in 8 years.

Is there something that I can do with my component listing to ensure that it is included in specific search terms like "recipe", "cookbook" etc?
What is the ranking system for returned results?  number of downloads?  number of reviews?

Regards,
Ryan

**Comment by aarati-parajuli** [comment]
Just noticed this issue. We have an extension named "3D Flipbook - Dearflip".
It doesn't appear in the search result when I search for 'Dearflip', 'Flipbook', or even '3D'. 
But it appears while visiting in the category 'print & pdf'. This is strange! 
This doesn't only affect us developers but also confuses users to choose the right extension for their purpose. 
I wish the JED team will focus on this issue as soon as possible. 

Best regards,
Aarati
![image](https://github.com/joomla/jed-issues/assets/52268708/4fa642a6-db25-4488-ac5d-a65f56f38072)
![image](https://github.com/joomla/jed-issues/assets/52268708/0b06300b-263b-4029-83e2-daeaaaaecc9a)

**Comment by mfleeson** [comment]
We have spent most of today debugging the algolia update script and found an extension that had UTF8 text in its definition was causing the update to crash. This has now been fixed and tested.
