### ISSUE TITLE
my web don't work maasjet.com

### ISSUE THREAD

**Issue by Maasjet** [joomla/jed-issues#263]
Please describe the problem or your issue 
my web don't work maasjet.com
i don't know the problem

**Comment by jeckodevelopment** [comment]
Hi,
This repository is ONLY for reporting issues with the *.joomla.org websites, not the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-https://issues.joomla.org/

Regards,
Thanks
