### ISSUE TITLE
Joomla Extension Directory Error

### ISSUE THREAD

**Issue by Traveller913** [joomla/jed-issues#267]
I recently purchased via the Joomla Extensions Directory (JED) a download of SJ Cool Showcase for Content - Joomla! 4 & 3 Module (Extension License: Business (+ $10.00) sj-cool-showcase-for-content 	$22.90 	$22.90

It is not compatible with Joomla 4 as advertised on the JED and is therefore of no use for my upgraded J4 website.

Your comments would be appreciated.
Regards,
 Rod Macmillan
UK

**Comment by mfleeson** [comment]
Please raise this as a ticket on JED. jed-issues on github is for issues with the functionality of JED. It displays what the developer has inputed.
