### ISSUE TITLE
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 10047664 bytes)

### ISSUE THREAD

**Issue by Tiffannie3x3** [joomla/jed-issues#268]
Trying to update a category and it is not allowing me to do so. The last action I did was delete a document and now it says there's not enough space. 

<img width="617" alt="Screenshot 2023-08-16 071554" src="https://github.com/joomla/jed-issues/assets/142413961/f05dd924-e90f-4b9e-938a-a49cb9702956">

It reads: Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 10047664 bytes) in /home/threebythree/public_html/condodocs/libraries/joomla/database/driver/mysqli.php on line 891
at the top of the page. nothing else is displayed.

**Comment by mfleeson** [comment]
Hi
Your error has nothing to do with the Joomla Extensions Directory. Suggest you seek support in the joomla forums.
