### ISSUE TITLE
can't upload install package

### ISSUE THREAD

**Issue by hikashop-nicolas** [joomla/jed-issues#269]
**Describe the bug**
I just published a new release for HikaShop and I'm not able to upload the new version's install package when editing the extension page on the JED. I'm getting an error with the message "Failed to move uploaded file."

**To Reproduce**
1. Go to the JED
2.  Edit the HikaShop extension https://extensions.joomla.org/extension/e-commerce/shopping-cart/hikashop/
3. Delete the current install package and upload the new Starter edition from https://www.hikashop.com/extensions/hikashop-starter.html
4. See the error message in an alert box.

**Expected behavior**
The install package should upload successfully

**Screenshots**
https://i.imgur.com/yov2Y77.png

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 116.0.5845.188 (Build officiel) (64 bits)

**Additional information**
I tried both the ZIP and the TAR.GZ and got the same error.
I tried the same operation with small plugin install package and it worked fine. I suppose it might be linked to either the fact that HikaShop's install package has many files, or that the ZIP is above 5MB.
However, previous versions of HikaShop were also above 5MB and I didn't had the issue before. Also, the tar.gz is below 5MB and I found this issue about the install package size limit raised to 20MB a few years back, so 5MB shouldn't be a problem:
https://github.com/joomla/jed-issues/issues/59

**Comment by billtomczak** [comment]
We're seeing the same problem here. We have an extension package that is 2.5M that we are unable to upload. No issue uploading a package that was under 2M.

**Comment by mfleeson** [comment]
We have requested that our host increase the file upload setting in php. Please try again and post back here if it works or does not work. Thanks. Mark. JED TL.

**Comment by hikashop-nicolas** [comment]
Thanks. I just tried but I still have the same issue.

**Comment by billtomczak** [comment]
Just tried here as well and it's still a problem

**Comment by xillibit** [comment]
I have tried now the problem is still here

The error message says it can't move the uploaded file, so maybe a problem on rigths: 
![image](https://github.com/joomla/jed-issues/assets/876395/596f0070-5467-4c2a-b661-8a03c596ebd4)

**Comment by billtomczak** [comment]
@xillibit  It's definitely a file size issue. I have no trouble uploading a 1.7M zip file, a 2.5M zip file shows the error on your screenshot. And yes, still a problem

**Comment by xillibit** [comment]
Tried with a 1,8 Mo zip it seems uploaded but when submit the form, there is still an issue :

![image](https://github.com/joomla/jed-issues/assets/876395/fe11a52d-bf11-417a-bf79-6c84b62b9fef)

**Comment by billtomczak** [comment]
@xillibit - I just happened to catch the jed site right after a reboot. I can now successfully upload *and* save when under 2M. Now I'm seeing the stalled upload you describe for over 2M

**Comment by mfleeson** [comment]
Thanks for the updates, according to the field it's set to allow uploads of 20MB but it's failing within the ajaxfile field when it looks for the temporary upload. Come find me on Mattermost if you want to help debug.

**Comment by mfleeson** [comment]
Checked phpinfo on the server and it's still saying max_upload_size=2M so I've asked the host once again to make sure it's correct. Thanks for all your patience.

**Comment by billtomczak** [comment]
no worries @mfleeson I appreciate your efforts very much

**Comment by mfleeson** [comment]
All working again. I've the php.ini file was corrupted so it reset to defaults. Now max_upload_size is 20Mb and after a quick test I think its complete. Please test and let me know how you get on.

**Comment by hikashop-nicolas** [comment]
I confirm it is now working. Thanks for fixing it !

**Comment by billtomczak** [comment]
thank you @mfleeson!
