### ISSUE TITLE
Unable to submit extensions...

### ISSUE THREAD

**Issue by PhilHika** [joomla/jed-issues#273]
**ATTENTION: If you have a question or you need to contact the JED Team about an Extension, please, contact us via the JED Ticketing System: https://extensions.joomla.org/profile/** 
=> I have already contact several time the JED team via Ticket system, and following several failures, I was invited to come here on Github

**Describe the bug**
I'm working for HikaShop, and we are unable to "Submit extension", any attemp result in a error message
"You are not allowed to add an extension
You have unpublished extensions"

**To Reproduce**
1. Go to 'https://extensions.joomla.org/browse/my-extensions/' (in HikaShop account)
2. Click on '+ Submit extension'
3. See error :
'You are not allowed to add an extension
You have unpublished extensions'

**Expected behavior**
Be able to submit more extension/plugins

**Screenshots**
See this link : https://i.ibb.co/R3Mh8sF/screenshot1.png

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 120.0.6099.130 (Build officiel) (64 bits)

**Smartphone (please complete the following information):**

**Additional context**
According to the error message, my problems come from the fact that I have unpublished extensions and this is true, these extensions are duplicates of HikaShop which are here (screenshot : https://i.ibb.co/bBkkcxK/screenshot.png) and here (screenshot : https://i.ibb.co/FmBW0G7/screenshot2.png)

AND please note that the "published" HikaShop Extensions is still without his reviews.

Please help us to solve this issue.
Regards

Philippe
Team HikaShop

**Comment by mfleeson** [comment]
Hi
Just checking whilst away from my usual desk - according to JED the main
Hikashop module is unpublished!
[image: image.png]
but also it has zero reviews! We are experiencing all sorts of issues with
the ancient JED 3 code. Have you had an issue raised with the JED team that
has caused Hikashop to be unpublished?
I can republish it and try and get back the reviews.
Best Wishes
Mark (JED TL)

**Comment by PhilHika** [comment]
Hello, 

You have surely put the focus on something important, because in fact in our extensions I see **3** HikaShop, 2 unpublished and 1 published...
And all **without any reviews**.

Now which one is the main one? We do not know...
Nor do we understand why we have 3 HikaShop in our extensions directory...

What do you suggest to us to be able to progress on this subject please?
Regards

Philippe
Team HikaShop

**Comment by hikashop-nicolas** [comment]
I think this is linked to the fact that HikaShop got unpublished following a VEL issue which was not reported to us more than a month ago.
We made a patch for the security issue on the same day and asked to be published back.
One week later HikaShop was published back on the JED but without reviews.
We were told that people we're working on restoring the reviews but no news of this so far.
Then, we wanted to published a new extension we developed for HikaShop and got the issue we're reporting now.

**Comment by mfleeson** [comment]
Thanks Nicolas. We are seeing this happen each time VEL suspends an
extension. I have requested access to the database backup for before
11/28/23 so I can try and restore the reviews/get everything back up and
running.

**Comment by hikashop-nicolas** [comment]
Thank you for looking into it.

Also, I would like to point out that all this stems from us never being notified about the VEL listing, and thus we could only react after the extension being unpublished from the JED, for which we did get notified. Someone from the JED support told us that we should have received an email when this happened. But I checked on our end and we didn't.  I told that person that it would be great to look into this because not being notified of VEL listings when it concerns your extension is a big problem, but I didn't hear back from anyone yet on this.

**Comment by mfleeson** [comment]
Hi Nicolas. Not sure what happened with the notification but I finally managed to get restore of the database before your entry was messed up. What it appeared to do is remove all entries from the reviews table but left the ucm entries. It then created a second ucm entry tied to your extension id which caused JED to return to entries and mess up. Please can you check your base Hikashop entry now and let me know if anything else looks wrong.

**Comment by hikashop-nicolas** [comment]
Hi,

Thanks for your work. It's getting better, but there is still something missing it seems.
I now only see one HikaShop entry in "My extensions" and it's the main one which is published. So I can now add new extensions.
However, HikaShop still has zero reviews:
https://i.imgur.com/dEKjtRu.png

**Comment by mfleeson** [comment]
How odd. In the backend it's showing all of the reviews. I'll check further.

**Comment by mfleeson** [comment]
It turns out it stores the number on reviews on the extension record, it
had been set to zero. Updated and resynced algolia and all 290 are now
displaying.

**Comment by hikashop-nicolas** [comment]
I can confirm that everything is back ! Thanks so much !
