### ISSUE TITLE
Error when selecting a number of extensions to display

### ISSUE THREAD

**Issue by Sandra97** [joomla/jed-issues#3]
When clicking on any number of extensions to display, you're redirected to a page mentioning "No extensions found":

![a](https://cloud.githubusercontent.com/assets/4682328/23583136/0ea4f51a-0112-11e7-9d30-d0a1144047b5.png)

![index](https://cloud.githubusercontent.com/assets/4682328/23583137/0ea50618-0112-11e7-890f-9e3dde65bb06.png)

**Comment by JazParkyn** [comment]
I have just tested this and when changing the number of extensions to display, the page reloads correctly. 

Can you supply the full URL of the page that you experienced this issue on please?

**Comment by Sandra97** [comment]
An example: https://extensions.joomla.org/extensions/extension/contacts-and-feedback/forms/breezing-forms/
If I choose 10, I have the "no extensions found" issue

**Comment by anibalsanchez** [comment]
We have merged a fix related to pagination. Thanks, @jreviews 

Still, the pagination remembers the page position from previous navigation, so I think this issue is still happening.

**Comment by anibalsanchez** [comment]
I can no longer duplicate the issue. After the latest updates, when the page limit changes, the page index goes back to page 1.
