### ISSUE TITLE
Content - Simple Pop-Up

### ISSUE THREAD

**Issue by 77Andre** [joomla/jed-issues#33]
Здравствуйте! Не работает Simple Pop-Up вставляю {simplepopup} закрываю {/simplepopup} ничего не происходит, помогите.
![12](https://user-images.githubusercontent.com/34774325/34303699-b0a11f6c-e747-11e7-920b-f7562928c4d5.jpg)

**Comment by Kubik-Rubik** [comment]
This repository is only for issues with the official Joomla! Extensions Directory.

If you need support with a specific extension, then you have to contact the corresponding extension developer.

@anibalsanchez Please close here.
