### ISSUE TITLE
page count doesn't function

### ISSUE THREAD

**Issue by N6REJ** [joomla/jed-issues#35]
When looking at a developers extension listing and you click on "all" on item count it returns error
https://extensions.joomla.org/profile/profile/details/35423/
![image](https://user-images.githubusercontent.com/1850089/36941040-a49a5280-1f17-11e8-98a6-4e68db77fc96.png)

**Comment by anibalsanchez** [comment]
After the latest changes, the option "All" is not available anymore and all extensions of the developer are shown on the developer page.
