### ISSUE TITLE
Spam through ALFContact

### ISSUE THREAD

**Issue by edrobal** [joomla/jed-issues#36]
A spammer found a way to send spam by our web site. We have ALFContact last release with captcha. How is it possible ?
Spam report is :
Return-Path: <webmaster@tpassociation.ch>
Received: from mta-gw5.infomaniak.ch (mta-gw5.infomaniak.ch
[83.166.132.53]) 	by mda285.infomaniak.ch (8.14.5/8.14.5) with ESMTP id
w3CLE5GS008734 	for <x>; Thu, 12 Apr 2018 23:14:05 +0200
Received: from smtp-imu3.infomaniak.ch (smtp-imu3.infomaniak.ch
[84.16.68.111]) 	by mta-gw5.infomaniak.ch (8.14.5/8.14.5) with ESMTP id
w3CLE5DB169668 	(version=TLSv1/SSLv3 cipher=DHE-RSA-AES256-GCM-SHA384
bits=256 verify=OK) 	for <x>; Thu, 12 Apr 2018 23:14:05 +0200
Received: from h2web38.infomaniak.ch (h2web38.infomaniak.ch
[128.65.195.55]) 	by smtp-imu3.infomaniak.ch (8.14.5/8.14.5) with ESMTP id
w3CLE5d4000641 	for <x>; Thu, 12 Apr 2018 23:14:05 +0200
Received: from h2web38.infomaniak.ch (localhost [127.0.0.1])
	by h2web38.infomaniak.ch (8.14.5/8.14.5) with ESMTP id w3CLE5mD007967
	for <x>; Thu, 12 Apr 2018 23:14:05 +0200
Received: (from uid39543@localhost)
	by h2web38.infomaniak.ch (8.14.5/8.14.2/Submit) id w3CLE5v8007964;
	Thu, 12 Apr 2018 23:14:05 +0200
X-Authentication-Warning: h2web38.infomaniak.ch: uid39543 set sender to
webmaster@tpassociation.ch using -f To: x
Subject: guest test title
Date: Thu, 12 Apr 2018 23:14:05 +0200
From: GuestViors <samburton202@aol.co.uk>
Reply-To: GuestViors <samburton202@aol.co.uk>
Message-ID: <d28d________________________fe29@www.tpassociation.ch>
MIME-Version: 1.0
Content-Type: text/html; charset=utf-8
X-Greylist: Sender succeeded STARTTLS authentication, not delayed by
milter-greylist-4.2.7 (mta-gw5.infomaniak.ch [83.166.132.48]); Thu, 12 Apr
2018 23:14:05 +0200 (CEST) X-Antivirus: Dr.Web (R) for Unix mail servers
drweb plugin ver.6.0.2.8 X-Antivirus-Code: 0x100000 X-Infomaniak-Spam: ham
X-Spam-Score: 0
X-Spam-Detail:
gggruggvucftvghtrhhoucdtuddrgedtfedrvdeggdegiecutefuodetggdotefrodftvfcurf
hrohhfihhlvgemucfkpffhqffotefpkfetmfenuceurghilhhouhhtmecufedttdenucenucfj
ughrpefvufffhfhrkfggtgeshhdtjhdttddtjeenucfhrhhomhepifhuvghsthggihhorhhsuc
eoshgrmhgsuhhrthhonhdvtddvsegrohhlrdgtohdruhhkqeenucffohhmrghinhepthgvmhhr
vghsuhhlthhsvddtudekrdgtohhmnecukfhppeduvdekrdeihedrudelhedrheehnecuvehluh
hsthgvrhfuihiivgeptd

Absenderdetails:<BR><HR>Name: GuestViors<BR>E-Mail:
samburton202@aol.co.uk<BR>IP-Adresse: 46.161.9.14<BR>Browser: Mozilla/5.0
(Windows NT 10.1; Win64; rv:38.0) Gecko/20100101
Firefox/38.0<BR><HR><BR>guest test post bbcode html
http://temresults2018.com/ simple

**Comment by anibalsanchez** [comment]
Hi,

This ticket system is for the JED site and extension publishing system.

For support questions about how to an extension, please contact the developer directly via their website.

Best Regards
