### ISSUE TITLE
New Instant Search

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#37]
We are implementing a new **Instant Search**, based on [Algolia](https://www.algolia.com/) (our search partner).

For more information about how we are configuring the new search, please, visit this link: [JED Search use cases and definitions](https://github.com/joomla/jed-issues/wiki/JED-Search-use-cases-and-definitions).

At this time, it's implemented for testing on the Live Site. It is available for everyone.

Feel free to send suggestions, ask or recommend new features. Now, we are planning the next step to improve the general search with the *Faceted Search Widget*.

**Comment by rayrutjes** [comment]
Hello @anibalsanchez , the implementation looks great already!
Please let me know if there is anything we can help you with regarding the relevance.

I took a look at your [before & after Algolia comparison here](https://github.com/joomla/jed-issues/wiki/JED-Search-use-cases-and-definitions).

I was wondering if you did understand the differences or if there was something we could help you with.
What does this mean? ` Legacy Query: 42% - 3/7`, and how could we improve that?

**Comment by anibalsanchez** [comment]
Hi @rayrutjes, thank you!

In general, Algolia search returns better results than the current search engine, based on MySQL queries. However, the objective of the implementation has been to strike a balance between what Algolia does better (full-text search) and the current search engine definitions (order by parent/child extension and scoring). So, the 50% ratio is a good measure that Algolia is returning similar results but also adding value.

Now, we are planning to replace the general search with the search widget, powered by Algolia. If you want to participate in the implementation, feel free to join the team here: https://extensions.joomla.org/support/knowledgebase/item/contributing-code-to-the-jed/

P.S. Also, contact me to add you in the Glip channel for JED Devs.

**Comment by rayrutjes** [comment]
Thanks for your answer.

The challenge will be to translate the "weight" approach to the Tie-Breaking algorithm Algolia uses.
The main advantage of going with that new approach is that you will be easily able to understand every rank of every result, and adjust if necessary.

You might consider bucketing the metrics you currently have (scoring + num_reviews). Also I'm wondering what the scoring is in your case. Is it related somehow to the number of downloads or page views?

My email being already all over the place, here it comes: raymond.rutjes@gmail.com.

Please don't put expectations to high on my implication. I'd be happy to provide help and answer questions, but chances are I won't really be able to get my hands dirty :)

**Comment by anibalsanchez** [comment]
All collaborations are welcomed.

In JED context, the scoring "Overall" is the primary metric that summarises Functionality, Ease of use, Documentation and Support. You can find the number on the right sidebar of an extension.

I've just sent you an invitation to Glip Joomla account.

**Comment by anibalsanchez** [comment]
NOTE to myself, the entries with a name like a category are linking the category. Example: **Weblinks**.

**Comment by nextend** [comment]
Hi,
if you are searching for slider, the instant search gives pretty bad result I think. Non of the related tags' top 3 extensions come up. 

Related tags:
https://extensions.joomla.org/tags/slideshow/
https://extensions.joomla.org/tags/image-jquery-slideshow/

Ps.: I'm the developer of Smart Slider 3 and the new search has negative impact for us.

**Comment by anibalsanchez** [comment]
Hi, 

The results are strictly based on the text matches of the defined text fields and the following order: https://github.com/joomla/jed-issues/wiki/JED-Search-use-cases-and-definitions

Please, try to improve the description or the hashtags to increase the presence of the main keywords that you look for.

**Comment by molotow11** [comment]
Hello, All.

"Articles filter" keyword search - [link](https://extensions.joomla.org/extensions/extension/?searchall=articles+filter&filter%5Btags%5D%5B%5D=&filter%5Bcore_catid%5D=&filter%5Bincludes%5D=&filter%5Bversions%5D=&filter%5Btype%5D=&filter%5Bhasdemo%5D=&order=&filter%5Bnewupdated%5D=&filter%5Bscore%5D=&filter%5Bfavourites%5D=&dir=DESC&limitstart=0&controller=filter&view=extension&layout=list&Itemid=145&clearorders=0&clearfilters=1)

First place given to an extesion which not related with search or filtering. 
Second and 3rd places given to 3rd-party extensions, it seems not good and should be given only by keyword search for specific component.

Is it known issues? Will you planned to fix it?

**Comment by molotow11** [comment]
Hello, Anibal.

Thanks for your answer.

Sorry, for my mistake. Yes, it is better results with instant search. When you planned to replace general search with new system? Which instruction we can use for optimize general search currently?

**Comment by anibalsanchez** [comment]
Hi,

It is going to be better to optimize for the new engine. It is mainly driven by keyword positions. So, if you want to optimize your text, the usual techniques for SEO can help you to write the extension description. For instance: include the primary keywords in the title; include the primary and the secondary keywords in the first paragraphs, etc.

I plan to implement the new engine as soon as I can have a weekend available just to work on JED. ;-)

**Comment by anibalsanchez** [comment]
The new search is published: https://extensions.joomla.org/instant-search/

The classic search is still published too, and it will be slowly deprecated in the future.

Please, check how it works. Feel free to submit new issues in case you find any opportunity for improvements.
