### ISSUE TITLE
No email sent when review posted for extension

### ISSUE THREAD

**Issue by joomdonation** [joomla/jed-issues#38]
Since few months ago, JED no longer sends notification email when our extensions received reviews from users. Could someone please check it?

**Comment by anibalsanchez** [comment]
Hi,

We are retesting the review system and we have confirmed that emails being received (other ext devs are also receiving emails).

So, it could have been a temporary issue.

I'm closing the issue. If you find a new case, please, reopen the ticket to check your particular review (there's a partial log of the recent activity that we could check up).

**Comment by joomdonation** [comment]
Thanks @anibalsanchez . We still haven't received any email from the system. Maybe it's just a problem with our own email somehow. I will update our account with new email and monitor the next review

Regards,

Tuan
