### ISSUE TITLE
Unable to see review feedback of my new list

### ISSUE THREAD

**Issue by asika32764** [joomla/jed-issues#4]
In the past, when I submit new list and get some error, the warning message will show on top of extension edit page, but currently JED cannot show any message (like the image I attached), so I wait for one month and do not know what to do.

![](http://i.imgur.com/XE4e5fl.jpg)

**Comment by asika32764** [comment]
Hello? It's about 3 weeks without response in JED tickets, and my extension still pending without any information so I don't know what should I do .

Can anyone tell me how to resolve this problem?

**Comment by JazParkyn** [comment]
What is the name of your extension? I'll take a look. There are currently 14 extensions awaiting processing.

**Comment by asika32764** [comment]
My extension is **Ezset** in https://extensions.joomla.org/extensions/extension/administration/ezset/

Thank you very much. I just hope to know why I didn't receive the review feedback.

**Comment by JazParkyn** [comment]
It got held as pending because the third party libraries that you've used don't pass the JED Checker. I have now checked it manually and have published it for you.

**Comment by asika32764** [comment]
Thank you.

I'm wonder that is it useful to check the `My extension includes external libraries.` checkbox?

![p-2017-04-09-002](https://cloud.githubusercontent.com/assets/1639206/24834368/8e9774a4-1d15-11e7-857c-0d2071190456.jpg)

I checked it before submit extension but it seems not work, no one try to manually check the 3rd party library.

**Comment by JazParkyn** [comment]
Yes, the checkbox indicates to the JED team that your extension includes third party libraries, and because of this may need to be looked at manually if it doesn't pass the JED Checker.

**Comment by asika32764** [comment]
OK, another question, if my list has not passed the review, JED will show any information on list page? or it will send me a notice mail? I's weird that I always didn't receive any notice about my list so I just waiting forever...
