### ISSUE TITLE
date added?

### ISSUE THREAD

**Issue by brianteeman** [joomla/jed-issues#42]
did something go wrong with a data import.
i noticed today that many extensions have a date added of 18/9 Nov 2014 but they all had reviews from much further back in time

For example all of @mbabker extensions are "affected"
https://extensions.joomla.org/profile/profile/details/150276/

**Comment by mbabker** [comment]
IIRC this was a "symptom" of the move to the current system.  I don't think it's anything recent.

**Comment by brianteeman** [comment]
maybe not recent but i just noticed it

if I, as a user, cant trust the data then its better for it to be removed
