### ISSUE TITLE
Long-running queries / 2018-07

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#45]
After the incident that turn off all servers, JED came back with low performance on some complex queries.

I have already executed several commands to optimize the database, but it has not solved the issue.

Users are reporting that the **New** menu item is no longer usable. I'm disabling it temporarily. https://forum.joomla.org/viewtopic.php?f=262&t=963892

The source of the problem seems to be the complex queries that are now not running optimally. 

I'm assigning the issue to me to review the problem in detail. The solution could imply the re-implementation of these queries.

**Comment by Gitjk** [comment]
When loading a JED page there are a few errors in the Firefox site inspector.  Does this ring a bell?
(screenshot attached)
![jed-errors](https://user-images.githubusercontent.com/10586468/43153323-456261de-8f71-11e8-8405-a4e033b35633.png)

**Comment by anibalsanchez** [comment]
It's not related with the performance issue. We have recently implemented CSP headers and they are blocking some scripts from loading. Feel free to report it as a different issue.

**Comment by anibalsanchez** [comment]
I have implemented the first part of the implementation of materialized views to optimize the ucm_content queries. The MySQL load has been reduced substantially. Counting the additionally capacity allocated by Rochen, the site is running Ok. More work is required to complete the optimization of ucm_content subqueries.

The issue is solved. Thank you for your feedback.
