### ISSUE TITLE
can not add a review to jdownloads: file not found

### ISSUE THREAD

**Issue by web54** [joomla/jed-issues#48]
When I want to write a review to jdownload extension ( they helped me so that I do want to do that !! ;) )
I got an error file not found.
could you help me ?
thanks

**Comment by anibalsanchez** [comment]
The reports include references about the "Not Found" error on specific extensions, but these extensions are receiving reviews. So, it is not clear why the user receives the "Not Found" error.

CC: @JazParkyn

**Comment by web54** [comment]
ok: 
i went in as logged (user ; tataye) 
https://extensions.joomla.org/extension/jdownloads/
i want ton add review
link to review is : https://extensions.joomla.org/write-review/review/add?extension_id=140
when clicking it brings me to : https://extensions.joomla.org/index.php with error not found
I trid with several browsers and adblock disabled, but always the same

**Comment by anibalsanchez** [comment]
When you access the extension page (https://extensions.joomla.org/extension/jdownloads/), do you find a console error in the browser?

**Comment by web54** [comment]
there are no error but messages :
JQMIGRATE: Migrate is installed, version 1.4.1
localhost/browser.js:61 Opera has modified script or content on staticxx.facebook.com (PATCH-1195, Facebook - block first character in the comment field from triggering a single key keyboard shortcut). See browser.js for details
localhost/browser.js:61 Opera has modified script or content on www.facebook.com (PATCH-1195, Facebook - block first character in the comment field from triggering a single key keyboard shortcut). See browser.js for details

**Comment by anibalsanchez** [comment]
This issue is similar to #114 

I've just implemented a tweak to system to solve it. I'm closing the issue as solved. If the issue persists, please, reopen it.
