### ISSUE TITLE
Images resized incorrectly, causing pixelation

### ISSUE THREAD

**Issue by ciar4n** [joomla/jed-issues#50]
It appears all images uploaded to JED via extension submit are resized to 960px wide? Images on extension pages are displayed at 1170px resulting in all images been slightly pixelated. Any chance of getting the image resize set to the width they are displayed (1170px).

This is also true for extension 'logo' images although slightly different. Images are resized to 302px wide, however, the space available for this image is better suited for 368px wide. The current image width causes whitespace each side of the image on JED browse pages.

**Comment by anibalsanchez** [comment]
Thank you @ciar4n for taking care of the issue!

Solved!

**Comment by ciar4n** [comment]
Issue still exists. Images uploaded are still resized to 960px.

**Comment by anibalsanchez** [comment]
The images are resized to 960x, but then they are scaled keeping the aspect ratio.

**Comment by ciar4n** [comment]
True but the issue is that they are been scaled up to 1170px which causes pixelation (loss of quality).

**Comment by anibalsanchez** [comment]
To fix it, the system should show the 960x .... or change the recommendation to upload a bigger image... let's say a 1280px image and create a set of images.

**Comment by ciar4n** [comment]
> change the recommendation to upload a bigger image

The problem is not so much the recommendation. The problem is when you upload an image, for example, 1280px wide, that image gets resized down 960px wide. It should only get resized down to 1170px because 1170px is the width it is been displayed at.

**Comment by anibalsanchez** [comment]
We could propose/implement the change and communicate the new definition.

**Comment by ciar4n** [comment]
Maybe this is it here?.. https://github.com/joomla/jed-dev/blob/master/public_html/components/com_jed/views/extension/tmpl/default.php#L41

Or here?.. https://github.com/joomla/jed-dev/blob/master/public_html/components/com_jed/views/extension/html.php#L97

**Comment by anibalsanchez** [comment]
Thanks, @jreviews for fixing the issue! PR #273 https://github.com/joomla/jed-dev/pull/273

It is already merged on stage. Tomorrow, I plan to publish it to the live site.

**Comment by anibalsanchez** [comment]
PR merged and live on the site.

Issue solved?

**Comment by ciar4n** [comment]
Yep. Tested and now resizing correctly. Nice job @jreviews
