### ISSUE TITLE
Problem refund JoomlaKave

### ISSUE THREAD

**Issue by aspergerway** [joomla/jed-issues#52]
I'm still not getting my $15 refunded. I didn't get along well with "Responsive Instagram Photo Gallery".
They asked me for the paypal email after several and far attempts to contact me, but they did not refund me.

**Comment by jeckodevelopment** [comment]
Hello @aspergerway this repository is to report issues with the Joomla Extensions Directory (as software) not with extensions themselves or the extensions providers. 
Please try to get in touch directly with the extensions developers. 
Feel free to leave a review for their extensions directly on JED, but administrative issues should be dealt with the provider.

Thank you for understanding.
