### ISSUE TITLE
A questionable link from JED

### ISSUE THREAD

**Issue by adatso** [joomla/jed-issues#57]
Hi,

Today, after resetting the password on JED, I received a message from "info+2018@extensions.joomla.org" with a fishy link:

https://u3886767.ct.sendgrid.net/wf/click?upn=UvZltPxmreGpYMfgSnK89g7wTlBteGCNPpRrMB-2FgLcgZkQ1Sgw55P1T8zV1WNnuH3CiPm9Wkbe2OEsp6BiX9pxEOAp9h5ys3P7ikEZe9cxCOu-2FlPhNc99gLhrEVg9byrHYPa2HBwcy7bLrlQ0EfqLJ1UpqZspgxsV2y9mbZ8pKcAnWSR6sLzA7keCj-2Bee81x_uoQOw53Jnd2odJf4vBwXdY8zVpydf2F3W-2BkB14NFXKAZ14t0C6rD5j-2FBZRKdmr7cSgZ1CkWr0edTN8pOQW8viSgX0J-2B-2B7CnkYzh5a9k9YBgGlJfcER9sckqDATscFoHbxx0t2PhDPQTfCil2WTviASt-2Fjb0lyDCYYzSEhBeQTR-2F-2Bq1-2BxIoBACJRfJyDwWErINTcOz8Y5jifveElDAdhKKg-3D-3D

and link anchor: 

https://extensions.joomla.org/index.php?option=com_resetpassword&task=confirmtoken&token=9123b604614a80d3d926462fa7a32a79

Even if this is done to collect some info, I consider this unacceptable!

![2018-09-30_18-38-54](https://user-images.githubusercontent.com/11773382/46259937-2b1f7380-c4e0-11e8-8835-319c47191b69.png)

**Comment by anibalsanchez** [comment]
Hi,

It looks like someone entered your email and sent you an email to reset the password.

There's nothing we can do about it. Anyone can (in any passoword reset form) enter any mail.

To avoid confusions, I'm changing the replyTo address to no-reply@extensions...

Regards,

**Comment by anibalsanchez** [comment]
Hi,

I've already corrected the email replyTo. 

SendGrid encodes the links to keep track of the openings and clicks.

 If you have requested the password reset, why does the link look fishy? Are you worried about the SenGrid domain?

**Comment by anibalsanchez** [comment]
I have disabled SendGrid's click tracking (we're not really using it). Case solved!

**Comment by adatso** [comment]
thank you
