### ISSUE TITLE
Activation Email

### ISSUE THREAD

**Issue by Deathwielder** [joomla/jed-issues#58]
I recently registered.  I waited for an activation email for over 1 week.  None arrived.

I tried to login and I got an error stating that I had not activated my account.  I reviewed SPAM/JUNK emails, deleted emails, etc.  to no avail.

On the ORIGINAL registration the email used to register was webmaster@militarywives.com  and the user name was chadduck.

Since I had NOT received the activation I have created a second account - same email address username bchadduck.  No activation has been received.

Suggestions?

![image](https://user-images.githubusercontent.com/43042701/46622579-03cc3600-cae0-11e8-80a5-718322fe6105.png)

**Comment by openmed-io** [comment]
same issue here 
my username is openmed.io
cant find "resend activation email" option

**Comment by openmed-io** [comment]
could you activate my account now, 
and proceed with email sending issue later
?

**Comment by anibalsanchez** [comment]
We have implemented a new process to periodically remove inactive accounts.

Case closed. Txs for reporting

**Comment by machadoug** [comment]
> We have implemented a new process to periodically remove inactive accounts.

How often does this process run? In other words, how long should I wait?

**Comment by anibalsanchez** [comment]
For the record, it runs weekly.
