### ISSUE TITLE
Maximum upload size for extension is 7MB

### ISSUE THREAD

**Issue by jreviews** [joomla/jed-issues#59]
Please increase the limit or provide an alternative for extensions that exceed this size.

**Comment by Llewellynvdm** [comment]
I agree, this limitation is preventing bigger applications from being submitted to the index. Lets increase this limit to a size that will support more freedom.

**Comment by anibalsanchez** [comment]
The system now accepts up to 20mb. Thanks @jreviews !

**Comment by Llewellynvdm** [comment]
Thank you too!
