### ISSUE TITLE
Repeated list items

### ISSUE THREAD

**Issue by asika32764** [joomla/jed-issues#6]
Extension list in JED category will repeat multiple times.

https://extensions.joomla.org/tags/administration/

![p-2017-04-09-003](https://cloud.githubusercontent.com/assets/1639206/24834436/7eea6b54-1d17-11e7-9a13-9ddf31ccebe1.jpg)

**Comment by JazParkyn** [comment]
I have not been able to replicate this by visiting the URL that you supplied. Does the page still display duplicates for you?

**Comment by asika32764** [comment]
OK, it fixed. Maybe someone adjusting site as that time.
