### ISSUE TITLE
Wrong email sent to owner after leaving reply to review

### ISSUE THREAD

**Issue by jreviews** [joomla/jed-issues#60]
When leaving replies to reviews for my extension I receive the following email which makes it seem like a new review was published, when in fact it was my own reply to an existing review.

```
Subject: JED New Review

A NEW REVIEW HAS BEEN POSTED
 
A new review for your extension "{extension}" has been posted.
 
Click here to view it.
```
Also notice the name of the extension is missing and the link to the extension is also wrong leading here [https://extensions.joomla.org//extensions/extension/](https://extensions.joomla.org//extensions/extension/)

**Comment by anibalsanchez** [comment]
We have fixed the inconsistency in the extension assignation issue. Now, it is under control.

I'm closing the issue. Feel free to comment on the issue if it still persists in the system. I'm keeping an eye on the topic.
