### ISSUE TITLE
Number of items on the page and pagination

### ISSUE THREAD

**Issue by brianteeman** [joomla/jed-issues#63]
### Steps to reproduce
From the home page search or backup
On the results page note that is says displays 12 
![image](https://user-images.githubusercontent.com/1296369/50045561-f063bb00-008c-11e9-9e59-53f9ee0dcbc3.png)
Count the number of items on the page and there are 18
ie there are 
6 rows of three items instead of 4
Now click to go to page2
Instead of page 2 starting at item 19 it starts at item 13

**Comment by JoomliC** [comment]
I confirm, and if you navigate from page 1 to page 2, items of the first page are again on the page 2.

The default display value should be 18.

**Comment by anibalsanchez** [comment]
We have merged a fix related to pagination. Thanks, @jreviews 

Still, the pagination remembers the page position from previous navigation. Additionally, when the user selects a page size, it renders the pages numbers OK. But, when the user visits a page, the page limit goes back to the original value.

So, I think this issue is still active.

**Comment by jreviews** [comment]
@anibalsanchez

> Still, the pagination remembers the page position from previous navigation

I believe the selected limit option is stored in a user state session variable and remembered throughout the site for the duration of the session as the user's preference. The alternative to this would require including the "limit" parameter in the URL, which is not how the system currently works. 

> But, when the user visits a page, the page limit goes back to the original value.

I am not seeing this issue on my end. If I change to 36 items per page. Click page 2,3,n the page limit list correctly shows the "36" value selected.

**Comment by anibalsanchez** [comment]
@jreviews 

> Still, the pagination remembers the page position from the previous navigation

Another idea, the user state session variable could be per pagination... but it would require identifying each pagination. So, the variable remembers the position for each pagination.

The original problem is remembering the page position in the session after the user leaves the pagination. The best solution would be removing the pagination state from the use session and keeping the state in each the page request.

> But, when the user visits a page, the page limit goes back to the original value.

1. Extension Pagination OK
2. Review Pagination, it still goes back to 12 in the 2-n pages when the user visits them.

**Comment by anibalsanchez** [comment]
We have confirmed that the original issue is working as expected. 

We'll continue improving the pagination.

Thanks fior reporting. Case solved.
