### ISSUE TITLE
Duplicated reviews in some extensions

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/jed-issues#65]
Reported by Cyril Jooml!C

`‏
@JoomliC
 18h18 hours ago
Hi @anibal_sanchez (and congrats!)
Seems to be a bug in December on the JED: many extensions with duplicated posted reviews (eg. Event Booking (24/12), DP Calendar (14/12),...)
https://extensions.joomla.org/extensions/extension/calendars-a-events/events/event-booking/ …, https://extensions.joomla.org/extensions/extension/calendars-a-events/events/dpcalendar/ … and maybe others...
` 

https://twitter.com/JoomliC/status/1082648873531785222

### Confirmed

Lacking in important sublte features for advance applications.

* https://extensions.joomla.org/extensions/extension/calendars-a-events/events/event-booking/#rev-112143
* https://extensions.joomla.org/extensions/extension/calendars-a-events/events/event-booking/#rev-112144

**Comment by JoomliC** [comment]
Thank you @anibalsanchez !

Just saw later the issue tracker for JED (code anywhere ?)

About this point, could be nice to have a "review report" system, that could help to manage it by team?
About issue, just saw it in calendar & events directory, but maybe this has occured in other parts.

**Comment by anibalsanchez** [comment]
In this particular issue, it seems to be related to the data processing of reviews, so a JED team member will check it on the live site.

About **JED Development**, you can check the current JED code base in a Github repo, but you must sign the JEDCA agreement (about confidentiality, copyright of contributions, etc) https://extensions.joomla.org/support/knowledgebase/item/contributing-code-to-the-jed/.

For more information about JED Development: https://extensions.joomla.org/blog/item/fun-in-jed-bug-smashing-and-feature-development/. And now, we also have a Glip group to chat with other JED Devs.

**Comment by jreviews** [comment]
Another recent example can be seen here https://extensions.joomla.org/extensions/extension/access-a-security/site-security/akeeba-backup/

The last 3 reviews from 07 February 2019 are the same.

![image](https://user-images.githubusercontent.com/31069418/52714653-cfc2bf00-2f70-11e9-80a0-72ae470c053f.png)

**Comment by anibalsanchez** [comment]
We have executed a process to clean the duplicated reviews and optimized the system to avoid delays.

Issue solved.

**Comment by cyrez** [comment]
Thanks! 👍
