### ISSUE TITLE
The classic search results return unrelated extensions 

### ISSUE THREAD

**Issue by tassosm** [joomla/jed-issues#69]
It seems that there's a bug in the classic search results (Not the new Instant Search) which return wrong and unrelated extensions. 

For instance, enter "twitter" in the search box, do not select anything from the Instant Search and hit the Go button.

Here's what you will get:

![wrong_results](https://user-images.githubusercontent.com/6807469/51136038-2b9c0a00-1844-11e9-8388-e1328b1105ee.png)

The results report that AcyMailing Start, Event Booking, EasyBlog are related to Twitter for a reason. As anyone can notice, none of these extensions are related to "twitter". Obviously, something is wrong here. I guess a user searching for "twitter" expects to see something else.

Then I started digging around with the filters and I noticed that if I remove the following parameters from the URL

dir=DESC
clearfilters=1

then we have more accurate and related results.

![correct_results](https://user-images.githubusercontent.com/6807469/51136167-846ba280-1844-11e9-9643-af37c1c097b3.png)

It looks like the default search options return the most popular or most reviewed extensions even if they are not related to the search term.

Is this the expected behavior or a bug?

**Comment by tassosm** [comment]
It looks like the **limitstart** and **clearorders** parameters need to be removed as well in order to get proper results. Keep in mind that this issue affects only the case where the user fills the searchterms field only and hits Go.

@anibalsanchez the filters must have been affected the last month(s). Then the results were more accurate. Until the entire classic search is replaced, this must be resolved as it makes it really hard to find what we are looking for.

@regularlabs if you're going to take a look here're the full URLs demonstrating the issue.

Wrong Results:

https://extensions.joomla.org/extensions/extension/?searchall=twitter&filter%5Btags%5D%5B%5D=&filter%5Bcore_catid%5D=&filter%5Bincludes%5D=&filter%5Bversions%5D=&filter%5Btype%5D=&filter%5Bhasdemo%5D=&filter%5Bnewupdated%5D=&filter%5Bscore%5D=&dir=DESC&limitstart=&controller=filter&view=extension&layout=list&Itemid=145&clearorders=0&clearfilters=1

Correct Results: (Without the dir, limitstart and clearorders params)

https://extensions.joomla.org/extensions/extension/?searchall=twitter&filter%5Btags%5D%5B%5D=&filter%5Bcore_catid%5D=&filter%5Bincludes%5D=&filter%5Bversions%5D=&filter%5Btype%5D=&filter%5Bhasdemo%5D=&filter%5Bnewupdated%5D=&filter%5Bscore%5D=&controller=filter&view=extension&layout=list&Itemid=145&clearfilters=1

The same goes for any search term.

**Comment by anibalsanchez** [comment]
Thanks, @regularlabs . The search results are shown consistently now.

**Comment by tassosm** [comment]
Yes, there's definitely an improvement.

However, there's still an issue with the ranking factors. The results are now ordered by the Title match only. Before the issue arises, the **keyword density in the title and in the description** was the 1st ranking factor where we had more accurate results. 

Here's why:

Let's say there's a top-rated extension about Twitter called "Tweet Pro". The user searches for "twitter" but he never sees that top-rated extension because the "twitter" term appears in its description only.

Your thoughts?

**Comment by anibalsanchez** [comment]
@tassosm The classic search is powered by MySQL, so it is little that we can do about to rank better.

I'm working on full-text search technology, so the plan is completing the new instant search implementation as soon as possible.

The new full-text search engine has everything to tweak and adjust the search results, and it has a whole different text analysis level.

**Comment by tassosm** [comment]
Until the new search is ready, the current ranking issue must be addressed. Would like me to take a look and provide a PR fix once I have the time?

**Comment by anibalsanchez** [comment]
Sure, pls @tassosm go ahead. I suspect that it is related to the recent changes in the general style, but not really sure. You can check the last PR #223, it could be a similar issue.

**Comment by tassosm** [comment]
Please check the PR. By moving body_weight before title_weight we get more accurate results.

**Comment by anibalsanchez** [comment]
Txs @tassosm ! Merged. 

Tomorrow, I'll complete the testing and publishing to the live site.

**Comment by anibalsanchez** [comment]
Published! The new search with weight on the title is live. Thanks @tassosm 

Issue solved.
