### ISSUE TITLE
Unable To Launch Review Editing

### ISSUE THREAD

**Issue by nobicycle** [joomla/jed-issues#7]
Hi, 
The issue below, |Unable to Submit Review" was closed by admin,
https://github.com/joomla/jed-issues/issues/1#issuecomment-292815987
who asked me to submit a support ticket to JED.

Just before doing so I thought I would test if the problem was still there. I tried to open the "Write a Review Page and got into a loop, as illustrated by the screenshot:

![screenshot_2017-04-10_11-44-33](https://cloud.githubusercontent.com/assets/1372447/24845317/b7a847a0-1de3-11e7-8dbd-037bc45094c5.png)

You can see from the screenshot that I am logged in, but every time I click on "Write a Review " the system asks me to create a new profile.

**Comment by anibalsanchez** [comment]
Hi,

We have been unable to reproduce the case.

However, we are checking a similar case, feel free to join to the task here #48
