### ISSUE TITLE
Cannot change my email address

### ISSUE THREAD

**Issue by dryabov** [joomla/jed-issues#70]
I have the same issue as #9 posted in 2017. Detailed steps to reproduce (see attached gif):
- go to Profile
- activate Account tab
- change Email (and to be sure fill Password fields)
- I'm not a robot
- Save
- ... and nothing changed

![cannot-change-email](https://user-images.githubusercontent.com/378044/51205108-2f985c80-1916-11e9-9dae-e90b244b4c59.gif)

**Comment by tlhall** [comment]
I have the same issue

**Comment by anibalsanchez** [comment]
Solved!
