### ISSUE TITLE
Log-in problems

### ISSUE THREAD

**Issue by Cabboss** [joomla/jed-issues#71]
Hello.
I can not log-in to the Joomla! Extensions Directory. I am using Cabboss as username and my e-mailadress is webmaster@cabboss.dk.

Can you help me, please.

Thamk you in advance.

Søren

**Comment by anibalsanchez** [comment]
Hi,

You have not activated the user. Check if you have received email and it is somewhere in your inbox (Spam folder may be?).

Otherwise, in 7 days, the user will be deleted and you can register again with the same email.

BTW: This ticketing system is used to report system issues only.

**Comment by Cabboss** [comment]
Tnx.
Sory, but I am new to this. Where do I adress problems like this?

**Comment by anibalsanchez** [comment]
JED has its own internal ticketing system. However, you must register first. Guest users can't change information on the site.

If you can't find the activation link, try registering with a different email (or, wait 7 days for the automatic user deletion)
