### ISSUE TITLE
Missing error code

### ISSUE THREAD

**Issue by roland-d** [joomla/jed-issues#73]
When you visit this URL:
`https://extensions.joomla.org/extensions/extension/e-commerce/credits-a-point-systems/alphauserpoints/`

You will get a message the reason for unlisting is error code `PE1` and when you click on the link `View error codes` this list has no entry for `PE1`.

**Comment by anibalsanchez** [comment]
PE1 means "under investigation".  I've just added it to the list: https://extensions.joomla.org/support/knowledgebase/item/unpublished-extensions-error-codes/#PE1

## PE1-Under Investigation
The JED team has received one or more user reports. After confirming the issue, or an infringement of JED TOS, the extension has been unpublished under this error code and contacted the developer to solve it. The extensions can be in this state for a long period of time until a decision is finally made.

**Developers**: Please open a ticket under "Current Listing Support" to contact the JED team.

P.S. We can't disclose more information about the case.

Thanks for reporting.
