### ISSUE TITLE
JED listing shows 200 Other extensions when using JED RSS feed

### ISSUE THREAD

**Issue by efduggan** [joomla/jed-issues#74]
**Describe the bug**
The JED page for an extension shows an incorrect number of other extensions when reached via the JED new extension directory feed

**To Reproduce**
1. Click on an entry in the JED RSS feed (http://feeds.joomla.org/JoomlaExtensions)  you are sent to that extension’s listing with a URL **like** : https://extensions.joomla.org/browse/new/extension/CATAGORY/SUB-CATEGORY/EXTENSION NAME/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+JoomlaExtensions+%28Joomla%21+Extensions+Directory%29

2. The Other extensions tab label  will show 200

![image](https://user-images.githubusercontent.com/25716272/51707758-e1025680-1fd6-11e9-8a89-ef9bdf3e65db.png)

3. Click one of the related extension and in that listing the tab label will report the correct number of extensions by that developer.

**Expected behaviour**
The correct number of extensions form that developer show up in the tab’s label when getting to the extension via the RSS feed link.

**Desktop (please complete the following information):**
Safari 12.0.3 / Firefox 64.0

**Comment by efduggan** [comment]
I hope that this minor bug won’t be in the new JED, whenever that comes out. While I can accept that this is a won’t fix issue, it would be nice to know the reason why it won’t be addressed.

**Comment by anibalsanchez** [comment]
We are only a few volunteers running JED. We have to operate and maintain the site and try to find time to develop new parts of the system. 

So, realistically, if we didn't find the time or someone willing to fix it, then we have to close it and move on.

**Comment by efduggan** [comment]
Thanks for the prompt explanation. Balancing new development with maintenance is always tricky; so I now understand the decision is a practical use of resources rather than a lack of technical ability. I’m good with that judgment call.
