### ISSUE TITLE
Reopening the issue of falsely-flagged reviews in joomla.org

### ISSUE THREAD

**Issue by MaghSamana** [joomla/jed-issues#75]
Continuing from the previous thread: 
https://github.com/joomla/jed-issues/issues/68

The reason is a false claim, posted:
--------------------------------------
anibalsanchez
Your reviews have been flagged. The system is detecting a Submission via an IP masking service or VPN. Since the reviews are not disappearing or being deleted, I don't see an issue, and the system is working as expected.
--------------------------------------

I post from my home with a simple internet connection. After checking the posting hours, I am certain to say that all my recent reviews have been from the same internet connection, same IP. Two of them (Gantry 5 and Agosm module) were removed, although they were normal, organic reviews. I have also notified the relevant developers, whose reviews have been affected, so they can form their own opinion about the issue.

Either way, Anibal Sanches, your system is badly configured to attack normal organic reviews. And since the issue has been clarified, and it's been your error, I expect my reviews to be back and visible. And when a system mistake is found out and recognised, the least you can do is reinstate those reviews. Why should I have to make another account simply to post these again?

You have removed important information: the second review about Agosm, was about my attempts to get OpenStreetMaps working from within JCal Pro (there is only the google maps option built-in). The experiment was successful, especially with help from Agosm's developer who responded immediately and helped. He didn't have to and it's a free extension. I appreciated it a lot!!

Now, it is good for many people to read this and know that if they want to get rid of google maps, and wish to display OpenStreetMaps from within a component's environment (like JCal Pro), it is possible and I shared details about how it can be done.

So I don't want to hear any excuses about what a badly configured system does, when you know that the flagged reviews were actually organic. Return the reviews online, and let valuable info be shared.

**Comment by anibalsanchez** [comment]
I'm reponing the original issue. Please, follow #68

**Comment by MaghSamana** [comment]
OK.
