### ISSUE TITLE
Rating Star is no longer shown next to Reviews Count

### ISSUE THREAD

**Issue by tassosm** [joomla/jed-issues#76]
**Expected behavior**
![image](https://user-images.githubusercontent.com/6807469/52193656-eb371700-2858-11e9-9a8a-5bbd08320664.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/6807469/52193682-0570f500-2859-11e9-9549-9c7a61689702.png)

**Comment by anibalsanchez** [comment]
What do you think about the idea @regularlabs ? I think that it can add value to the current card iteration.

**Comment by regularlabs** [comment]
Well, the scores were there a day or 2 ago.
So something changed in the latest pushes you did, removing the scores.

So this is not an idea, this is a bug report.

**Comment by anibalsanchez** [comment]
Ahhhhh .... ok

I updated to the latest J 3.9.2. Could it be related to a view override?

**Comment by regularlabs** [comment]
https://github.com/joomla/jed-dev/blob/develop/public_html/components/com_jed/layouts/bootstrap3-fontawesome/extension/listitem.php#L163-L171

No idea why that is not being done anymore...

**Comment by regularlabs** [comment]
Makes no sense. If there is no score, it would have to output the 'not rated' text.
That isn't there either.

I don't see any other use of `class="info-rating"` anywhere.

**Comment by anibalsanchez** [comment]
We could have broken something with our updates to the review form.... but it should have affected the grid view ...

**Comment by regularlabs** [comment]
Can you double-check if that file is as it should be on the live server?

**Comment by anibalsanchez** [comment]
That's the problem ... I'm reverting back to else :

**Comment by regularlabs** [comment]
Ah, now I see the addition of the `<?php elseif(isset($reviewLink)) : ?>`.
Why is that in there?

**Comment by regularlabs** [comment]
> Fixed ‘undefined variable reviewLink’ in extension list pages

Ok, this would be better:
```
<?php if (!$score || !$item->num_reviews->value) : ?>
	<span class="text-rating muted"><?php echo JText::_('COM_JED_NOT_RATED'); ?></span>
<?php else : ?>
	<div class="score-list-stars">
		<?php echo JedScore::getStarsShort($score); ?>
	</div>
<?php endif; ?>
```
So just remove the `<a>` tag.

**Comment by anibalsanchez** [comment]
Fix applied. Thank you @regularlabs 

Txs for reporting @tassosm 

Issue solved!
