### ISSUE TITLE
Activate account

### ISSUE THREAD

**Issue by pe7er** [joomla/jed-issues#77]
Yesterday I tried to create a new account at https://extensions.joomla.org/
I did not receive the confirmation mail with activation link.

When I try to login with the user details, I get the error:
> 
> Warning
> You have not activated your account yet. Please, check your inbox and confirm your account.
> 
> 
> Error
> Not found!

Could you please resend the activation notification?
I can supply the account details via Glip...
Thanks!

**Comment by jreviews** [comment]
Same as #58

**Comment by anibalsanchez** [comment]
You are right @jreviews 

JED (or Joomla) doesn't have an official way to resend activation links or deleting users not activated. 

The idea is implementing a process to remove unactivated users.

Closing this ticket as duplicate, please, follow #58

**Comment by pe7er** [comment]
Ok, thanks
