### ISSUE TITLE
Cannot reply to a review

### ISSUE THREAD

**Issue by philip-sorokin** [joomla/jed-issues#78]
**Describe the bug**
I have listings on the JED, and cannot reply to reviews I get.

**To Reproduce**
1. Click on the "Reply" link.
2. Write the reply.
3. Submit

**Errors**
1. Functionality is required
2. Ease of use is required

**Screenshots**
![2019-02-06_01-57-12](https://user-images.githubusercontent.com/11632367/52309929-a9ba7f00-29b2-11e9-932e-e660bdd60868.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 72.0.3626.81

**Comment by anibalsanchez** [comment]
Thanks, @philip-sorokin for reporting!

Thanks, @jreviews for fixing the issue :+1:
