### ISSUE TITLE
JED Filter Browse Extensions - New extremely slow

### ISSUE THREAD

**Issue by Gitjk** [joomla/jed-issues#79]
Since a few weeks the 'time to first byte' when selecting 'Browse Extensions' > 'New' usually is between 60 and 90 seconds. The other two options work fine. A problem with the CDN?

BTW - I think the JED would create much less server load, if the thumbnail images would be scaled once to the required size and afterwards be stored and called from the database with the displayed width and height instead of scaling them down every time.

**Comment by anibalsanchez** [comment]
The problem is in the database. It has been working fine for years, but the query is performing badly now.

**Comment by Gitjk** [comment]
Might be too simple, but just in case you didn't try that already. If the query didn't change, maybe running the table maintenance tools in phpmyadmin eventually would fix the issue.

**Comment by anibalsanchez** [comment]
@jreviews nailed it down. 👏👏👏

The issue is solved. Thank you!

**Comment by Gitjk** [comment]
> @jreviews nailed it down.

Just curious - what was the problem? (I suppose the JED is not using jreviews)

**Comment by jreviews** [comment]
> Just curious - what was the problem?

A different database table column was used to improve the performance of the query.

> I suppose the JED is not using jreviews

That is correct.

**Comment by anibalsanchez** [comment]
The JED database is so complex, that a wrong order changes the whole performance.
