### ISSUE TITLE
Extension doesn't appear in Algolia search by extension name 

### ISSUE THREAD

**Issue by GeraintEdwards** [joomla/jed-issues#80]
One of my extensions, YourSites (,https://extensions.joomla.org/extension/yoursites-manager/) has been listed on the JED since August 2018 and appears in the algolia search under various keywords e.g. 'site manage' etc. It also appears if you use a typo in the extension name e.g. 'yoirsites' or 'yoursoites'.  (searching without the single quote of course).

BUT it does not appear if you search for the correct name 'yoursites' or 'YourSites' (unless you click through to the full JED results).

It appears there is something wrong in the way the Algolia search is working

**Comment by anibalsanchez** [comment]
Thanks for reporting.

I've verified that other extensions are returned search by exact name or partial name match, however, YourSites is not matched.

I'll check the case in detail to find out the underlying issue.

**Comment by arzaafshar** [comment]
I have the same issue. Both Simple Facebook Post Embed https://extensions.joomla.org/extensions/extension/social-web/social-display/simple-facebook-post-embed/ and Simple Twitter Embed https://extensions.joomla.org/extensions/extension/social-web/social-display/simple-twitter-embed/ are not showing up on the JED results when you search for Facebook or Twitter. Both of the extensions were listed on JED since February 2016.

**Comment by anibalsanchez** [comment]
Thanks for reporting. I'm preparing an update to the search engine. So, I'll check these cases as part of the new implementation.

**Comment by arzaafshar** [comment]
Hi. Is this issue resolved? Thank you.

**Comment by anibalsanchez** [comment]
Not yet.

**Comment by arzaafshar** [comment]
Hi. Did we get this issue resolved? Thank you.

**Comment by anibalsanchez** [comment]
I've been implementing tweaks to the search settings. In a few weeks, the classic search will be removed and the Algolia Instant Search will replace it on the site.

At this time, the search results are showing the reported case. So, we can safely close this issue.

Thanks!
