### ISSUE TITLE
Twitter cannot load extension images

### ISSUE THREAD

**Issue by jreviews** [joomla/jed-issues#81]
Extension images are stored in the /cache folder which is excluded by robots.txt and prevents them from being used in Twitter cards.

![image](https://user-images.githubusercontent.com/31069418/52856951-1c86d100-30fc-11e9-9212-1d74333ffbba.png)

**Comment by anibalsanchez** [comment]
Please, recheck it now: https://extensions.joomla.org/robots.txt

**Comment by jreviews** [comment]
Change looks good, but it still doesn't work. Maybe Twitter cached the robots.txt file and we need to wait for a refresh.

**Comment by jreviews** [comment]
It's fixed.
