### ISSUE TITLE
Two extensions under the same name

### ISSUE THREAD

**Issue by PhocaCz** [joomla/jed-issues#82]
Hi, there are two extensions stored under the same name.

See example:

**To Reproduce**
Search for "phoca photo" in JED, you get two results:

![Phoca Photo](https://i.imgur.com/ln2ZTRx.png)

which is OK, one is component, second is plugin, but if you click on both, you will be redirected always to component only. Even when I want to edit the plugin, I am redirected to the component page, so in fact I am not able to edit the plugin extension.

**Expected behavior**
Each extension has own page

**Screenshots**
![Phoca Photo](https://i.imgur.com/ln2ZTRx.png)

**Desktop (please complete the following information):**
 - independent to OS or browser

So it seems, both of them have the same "alias".

Jan

**Comment by anibalsanchez** [comment]
Since both are the same extension, it looks that there's a bug in the search query.

**Comment by PhocaCz** [comment]
No, they are not:
1) Phoca Photo Component
2) Phoca Photo Content plugin

both are different extensions. But they have the same alias in JED (phoca-photo)

**Comment by PhocaCz** [comment]
But now I see, it is solved, I added new entry there and it is called "content-phoca-photo", so this solved the problem.

Thank you, Jan
