### ISSUE TITLE
Notice in extension.joomla.org "write a review"

### ISSUE THREAD

**Issue by YGerry** [joomla/jed-issues#83]
Hi,

If I want to write a review, I get this Notice:

> Security checks determined you may be using an IP masking service or VPN. To continue, you need a different Internet connection.

OS: Ubuntu
Browser: Firefox 65.0.1

But I Didn't use IP masking service or VPN . . .
Greetings from Paderborn . . .

**Comment by anibalsanchez** [comment]
Hi,

The system has detected a connection issue. The issue could be even in the neighborhood of your connection, and not directly related to your computer.

To continue, we recommend using a different Internet connection.

Best Regards
