### ISSUE TITLE
Newsletter subscription page looks weird

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/jed-issues#86]
URL: https://extensions.joomla.org/newsletter/

The newsletter subscription module isn't displayed properly.

![immagine](https://user-images.githubusercontent.com/733133/54921090-2b378380-4f05-11e9-93d9-218c5fbc4d67.png)

**Comment by anibalsanchez** [comment]
After an upgrade of the mailing extension, the page looks better now.

Please, re-open the issue if you think that it needs further improvements.
