### ISSUE TITLE
Data Issue: Cannot find my extension in the Profile Tab

### ISSUE THREAD

**Issue by ludek-vesely-phrase-com** [joomla/jed-issues#87]
Hi, I've submitted an extension `Memsource Connector` on JED but I cannot find it, neither submit a new version. When I go to `Extensions` in JED Profile, I see only this message:

![Profile](https://user-images.githubusercontent.com/46561869/55386278-6e11e080-552f-11e9-9e62-bc91a32d6a88.png)

When I try to submit the extension again, it says that given extension already exists:

![Add_an_extension](https://user-images.githubusercontent.com/46561869/55386384-a9141400-552f-11e9-91e6-0740a2199390.png)

When I go to the extensions search, the extension is suggested fine:

![Top_Rated_Joomla__Extensions](https://user-images.githubusercontent.com/46561869/55386519-eed0dc80-552f-11e9-8921-a1601d581826.png)

But after clicking on the name of the extension, nothing is found:

![Joomla__Extensions_Directory](https://user-images.githubusercontent.com/46561869/55386588-1d4eb780-5530-11e9-9cad-a01f69233ce3.png)

After logging out I can finally see my extension:

![Memsource_Connector__by_---_-_Joomla_Extension_Directory](https://user-images.githubusercontent.com/46561869/55386705-5dae3580-5530-11e9-8b49-59aac48cd2cc.png)

I think it is somehow related to empty `Developer Name` at time of submitting the extension:

![Memsource_Connector__by_---_-_Joomla_Extension_Directory_and_Profile](https://user-images.githubusercontent.com/46561869/55386928-ceede880-5530-11e9-8bff-c09b7ce72047.png)

Could you please take a look at this issue and add my extension to my profile? I also tried to fill out developer name, but it didn't help. Thank you!

**Comment by ludek-vesely-phrase-com** [comment]
@anibalsanchez any updates on this?

**Comment by anibalsanchez** [comment]
Not yet. I've been pretty busy in the last months. I hope to find these days to check this issue and other pending points.

**Comment by anibalsanchez** [comment]
Hi,

I've just checked the issue, and the recent changes solved the case.

Thanks for reporting

**Comment by ludek-vesely-phrase-com** [comment]
@anibalsanchez No, the recent changes didn't solve the case. I would say that nothing has changed:
![Profile](https://user-images.githubusercontent.com/46561869/73640386-7286b880-466e-11ea-9005-b7266fc74448.png)

Could you please take a look?

**Comment by anibalsanchez** [comment]
I've found a new data issue that could have affected your case. It is fixed.

Please, check it again and report it back if the issue persists.

**Comment by ludek-vesely-phrase-com** [comment]
Thank you, Developer field seems to be fixed. However, the extension is now in Pending state, so I hope it will be visible on JED soon.

**Comment by anibalsanchez** [comment]
Hi, 

If the extension is still in Pending state after a week, please, send us a ticket to check it.

Regards
