### ISSUE TITLE
Other extensions showing 200 instead of 2?

### ISSUE THREAD

**Issue by tonypartridge** [joomla/jed-issues#89]
![BF8589DD-8032-48BD-8E7F-0F9B0EA4D266](https://user-images.githubusercontent.com/1400982/56486356-3adbc500-64cf-11e9-9529-21dba8511013.png)

See above, on:
https://extensions.joomla.org/browse/new/extension/news-display/articles-display/copy-me/

**Comment by anibalsanchez** [comment]
Duplicated, please follow #74
