### ISSUE TITLE
Filter doesnt work after new/updated - Advanced search

### ISSUE THREAD

**Issue by ssnobben** [joomla/jed-issues#90]
Hi

before you got had an **second filter** after you have choosen Extension ..> **for "New/Updated" for Advanced search**- Now they are not there after you have selected first one of New or Updated ( Advanced Search ).

Hope you get this back though it was the only way to get the latest updated and new extension and you can filtered them for that.

Maybe also have a top menu link as you have for "Browse Extensions" where you have "New" should also have one menu "Last updated"

**Comment by anibalsanchez** [comment]
Fixed! The advanced search box is visible again.
