### ISSUE TITLE
Have two modules for "New" & "Last updated" on front page

### ISSUE THREAD

**Issue by ssnobben** [joomla/jed-issues#91]
Hi 

I have a suggestion to have two rows with nice show case modules for "New" & "Last updated" on front page https://extensions.joomla.org/ where you show case let say the latest 3-4 extension that is new & updated.

Could be between the advertisment and the extension categories..

**Comment by ssnobben** [comment]
There is also a similar request here and this seems not to have any attention https://github.com/joomla/jed-issues/issues/121

**Comment by anibalsanchez** [comment]
Since we are thinking about this point within the effort of the new design, I'm closing this issue and moving the conversation to #139
