### ISSUE TITLE
Not possible to submit reviews for paid extensions

### ISSUE THREAD

**Issue by marcobiagioni76** [joomla/jed-issues#93]
**Describe the bug**
It's not possible to submit a review for paid extensions because the validation for the field 'Value for money' always reports 'Value for money should be longer than 64 characters'

**To Reproduce**
1. Go to a paid extension
2. Click on 'Add review'
3. Fill in all fields including the 'value for money' with the correct length
4. Submit the review
5. See the persistent error 'Value for money should be longer than 64 characters'

**Expected behavior**
The review is correctly submitted

**Screenshots**
![image](https://user-images.githubusercontent.com/49912830/56588064-f3def400-65e2-11e9-8bb8-4f6503fd2597.png)

**Comment by anibalsanchez** [comment]
May be there's an issue on the new validation? @jreviews

**Comment by anibalsanchez** [comment]
I've just fixed the issue introduced in the validation of fields.

@marcobiagioni76 Please, submit your review . Txs.
