### ISSUE TITLE
Links to VitaBook are no longer valid

### ISSUE THREAD

**Issue by Joomi1945** [joomla/jed-issues#94]
in Jed (url = https://extensions.joomla.org/extension/vitabook/) the links under Demo, Support and Documentation lead to a page which displays following text: joomvita.com has expired.
In my opinion VitaBook should be removed from JED. 
Additionally, it appears that Vitabook is targeted by malicious Bots i.e.:
https://peppervoices.ch/index.php/component/vitabook/?start=222950

**Comment by anibalsanchez** [comment]
Hi,

This ticketing system is oriented to manage system issues. 

Please, report the broken link on JED (Report button)

Thanks
