### ISSUE TITLE
Can not write a review

### ISSUE THREAD

**Issue by barkingmoonbat** [joomla/jed-issues#96]
Security checks determined you may be using an IP masking service or VPN. To continue, you need a different Internet connection.

I'm not using any such service.  Tried with both verizon and my home internet system.

**Comment by anibalsanchez** [comment]
The validation is finding an issue. It could be related to your IP or our local network (beyond your personal connection).

Please, try to submit the review from a different location.

Best regards

Original Issue: #85

**Comment by barkingmoonbat** [comment]
Just tried from my phone on another network and am getting this now when
adding a review.
Thanks for your help.
