### ISSUE TITLE
JED Search issue in certain cases %20

### ISSUE THREAD

**Issue by Gitjk** [joomla/jed-issues#98]
**Describe the bug**
If I type _time track_ into the 'Find the extension you're looking for' search field on the JED homepage using the latest Firefox browser, it doesn't find anything and in the small search field on the results page it shows time%20track.
Noticed that the url seems to be double encoded.
See: https://stackoverflow.com/questions/16084935/a-html-space-is-showing-as-2520-instead-of-20

Now if you remove the %20 encoding in the small search field so that it reads time track, the Algolia autocomplete works and shows results.

**To Reproduce**
1. Go to https://extensions.joomla.org/
2. Type 'time track.'
3. See error: No results found "time%20track"

**Expected behavior**
Display: 
![JED-Search-stopped-working-3](https://user-images.githubusercontent.com/10586468/57571576-3e000c00-7410-11e9-8358-a12c2312e76e.jpg)

**Screenshots**
![JED-Search-stopped-working-2](https://user-images.githubusercontent.com/10586468/57571513-a3073200-740f-11e9-8fc1-f0d3a6183fc0.jpg)

**Desktop (please complete the following information):**
 - OS: [Win 7]
 - Browser [Firefox]
 - Version [66.0.5]

**Additional context**
Perhaps the autocomplete script doesn't fire in some cases.

**Comment by anibalsanchez** [comment]
It looks like your setup doesn't correctly interpret the space "%20" and it handles it as part of the query.

Please, try to search here: https://extensions.joomla.org/instant-search

What happens when you type and search for "time track"? 

Is the final URL https://extensions.joomla.org/instant-search/?q=time%20track&hPP=10&idx=jed_live&p=0?

**Comment by Gitjk** [comment]
> Is the final URL https://extensions.joomla.org/instant-search/?q=time%20track&hPP=10&idx=jed_live&p=0?

Yes, that works. I see the same URL. But if I use the search form on the JED homepage and hit the 'Go' button, the %20 encoding error shows up and the url is:
https://extensions.joomla.org/instant-search/?searchall=track+time&q=track%2520time
where the %2520 seems to be the result of double encoding.

**Comment by roland-d** [comment]
I just had this same issue:
![image](https://user-images.githubusercontent.com/359377/71530161-b0aef080-28e8-11ea-9b38-7e2bf6dd2d77.png)

I also used the search form on the frontpage and just type *ro users* and hit enter ignoring the suggestions.

**Comment by anibalsanchez** [comment]
I've just updated to the lastest Algolia API v4.

Please, check if the issue remains active.

**Comment by roland-d** [comment]
@anibalsanchez Not sure if it is fixed, the Enter key has been disabled and clicking on the magnifying glass doesn't do anything.

**Comment by anibalsanchez** [comment]
The new widget search immediately while you type, so the Enter key or the magnifying glass has no function. I'm going to hide the cursor on the magnifying glass to make it clearer.

Thanks!

**Comment by Gitjk** [comment]
Of course the problem with the space character (%20) is gone. However, a general problem with Algolia seems to be that the proximity of two search words is no ranking factor in the search results.

**Comment by anibalsanchez** [comment]
Great,

Let's close this ticket and open a new ticket to follow other search issues. #145
