### ISSUE TITLE
Incorrect extension page rendering - Category = Extension name routing

### ISSUE THREAD

**Issue by dryabov** [joomla/jed-issues#99]
**Describe the bug**
The link to "Mobile" extension page in search results is https://extensions.joomla.org/extension/mobile/ (e.g. try to search for "mobile joomla"), but this page isn't rendered properly: the Home page is displayed again instead of the extension page.

**To Reproduce**
1. Go to 'https://extensions.joomla.org/'.
2. Type 'mobile joomla' in the search field and click Go button.
3. Click on "Mobile" extension in results (URL: https://extensions.joomla.org/extension/mobile/).
4. Content of home page is displayed instead of the extension page.

**Expected behavior**
The extension page is displayed (currently available at https://extensions.joomla.org/extensions/extension/mobile/mobile-display/mobile/).

**Comment by dryabov** [comment]
Why other extensions are accessible via `/extension/[extension-slug]/`, but not `/extension/mobile/`? Was there a buggy update in the com_jed's router?

**Comment by anibalsanchez** [comment]
The JED router hasn't changed recently. However, it is a known issue when an extension name matches a category name, both are available under the same path, and the JED router prefers to serve the path at the category.

Since it is a complex issue that requires extensive testing,  to solve your case, I recommend renaming the extension with a more specific name.

**Comment by dryabov** [comment]
Is it possible to look at the router's source code (maybe under NDA, if necessary)? As far as I can see, links to category pages look like `/extensions/[slug]/` (versus extension's `/extension/[slug]/`), and so I hope it will be possible to localize and fix the issue by scrutinizing router's source with the knowledge of raw URLs of `/extension` and `/extensions` menu item.

**Comment by anibalsanchez** [comment]
Sure. If you prefer to improve the router, we are going to welcome your collaboration. You can join the **JED Dev Team**.

Please, sign the JEDCA and forward me the confirmation to anibal.sanchez@extensions...org.

https://extensions.joomla.org/support/knowledgebase/item/contributing-code-to-the-jed/

After this step, I'm going to send you the rest of the dev tools and repo accesses.

**Comment by anibalsanchez** [comment]
Thank you for your collaboration @dryabov ! The issue is solved.
